### ISSUE TITLE
Improper training parameter setting in train.yaml of MetricGAN ( RuntimeError: Input tensor at index 1 has invalid shape [10,266,257], but expected [10,313,257])

### ISSUE THREAD

**Issue by huskyachao** [speechbrain/speechbrain#1013]
Hi, I've been running the experiment in "speechbrain/recipes/Voicebank/enhance/MetricGAN/". I set the parameters in hparams/train.yaml as follows:
```  Yaml
...
# Training Parameters
number_of_epochs: 5000
number_of_samples: 100
min_mask: 0.05
train_N_batch: 1
valid_N_batch: 20
history_portion: 0.2
G_lr: 0.0005
D_lr: 0.0005
mse_weight: 0
...
```
When I tried to run the training code on 2 GPUs with this command:  CUDA_VISIBLE_DEVICES=0,1   python train.py hparams/train.yaml --data_parallel_backend
I met with the error:
``` Error
(venv) user1@amax:/mnt/DataCenter/user1/mmEve/speechbrain/recipes/Voicebank/enhance/MetricGAN$ CUDA_VISIBLE_DEVICES=0,1   python train.py hparams/train.yaml --data_parallel_backend 
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: ./results/MetricGAN/7230
speechbrain.core - 1.9M trainable parameters in MetricGanBrain
speechbrain.utils.checkpoints - Loading a checkpoint from results/MetricGAN/7230/save/CKPT+2021-09-27+14-42-16+00
speechbrain.utils.epoch_loop - Going into epoch 4
Discriminator training by current data...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:35<00:00,  2.79it/s, train_loss=0.0575]
Discriminator training by historical data...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 39.09it/s, train_loss=0.00605]
Discriminator training by current data again...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:11<00:00,  8.44it/s, train_loss=0.0107]
Generator training by current data...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:07<00:00, 12.89it/s, train_loss=0.512]
Avg G loss: 0.512
Avg D loss: 0.011
MSE distance: 0.144
  0%|                                                                                                                                                              | 0/39 [00:06<?, ?it/s]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 582, in <module>
    se_brain.fit(
  File "/mnt/DataCenter/user1/mmEve/speechbrain/speechbrain/core.py", line 1067, in fit
    loss = self.evaluate_batch(batch, stage=Stage.VALID)
  File "/mnt/DataCenter/user1/mmEve/speechbrain/speechbrain/core.py", line 928, in evaluate_batch
    out = self.compute_forward(batch, stage=stage)
  File "train.py", line 64, in compute_forward
    mask = self.modules.generator(noisy_spec, lengths=lens)
  File "/mnt/DataCenter/user1/mmEve/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/DataCenter/user1/mmEve/venv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.gather(outputs, self.output_device)
  File "/mnt/DataCenter/user1/mmEve/venv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 181, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/mnt/DataCenter/user1/mmEve/venv/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 78, in gather
    res = gather_map(outputs)
  File "/mnt/DataCenter/user1/mmEve/venv/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/mnt/DataCenter/user1/mmEve/venv/lib/python3.8/site-packages/torch/nn/parallel/_functions.py", line 75, in forward
    return comm.gather(inputs, ctx.dim, ctx.target_device)
  File "/mnt/DataCenter/user1/mmEve/venv/lib/python3.8/site-packages/torch/nn/parallel/comm.py", line 235, in gather
    return torch._C._gather(tensors, dim, destination)
RuntimeError: Input tensor at index 1 has invalid shape [10, 266, 257], but expected [10, 313, 257]
```
But when I changed the ## valid_N_batch ## in the train.yaml from 20 to 1, the code worked well. I ran the "nvidia-smi" in the terminal but it seemed that there is only one GPU work but not two GPUs as I set in the command (CUDA_VISIBLE_DEVICES=0,1). The above problems also happened when I changed the train_N_batch from 1 to 20 (other numbers but not 1).
So I wonder why it didn't work with valid_N_batch:20 and what do the parameters in the train.yaml mean (more specifically, the number_of_samples, train_N_batch, valid_N_batchj)? Is there any more detailed  README doc about the parameters of the MetricGAN?  Thanks~

**Comment by mravanelli** [comment]
I'm not sure we even tried the MetricGAN+ code on multiple GPUs. Any insight @JasonSWFu? In the past we had a similar issue for the ASR recipes, but we solve it. Here @popcornell and @TParcollet might have some insight as well.

**Comment by popcornell** [comment]
The MetricGAN+ uses a buffer right ? I would look into that one as it may cause problems with multiple GPUs.

**Comment by huskyachao** [comment]
Hi , is there any detailed description about the parameters in _hparams/train.yaml_ of the MetricGAN?

**Comment by guocj97** [comment]
Hello, may I ask whether the result of your final code reproduction can reach the PESQ described in the paper?

**Comment by Adel-Moumen** [comment]
Hello, 

The error is coming from `data_parallel_backend` which is totally deprecated in PyTorch and SpeechBrain. Instead, please use DDP (see our tutorials: https://speechbrain.readthedocs.io/en/latest/multigpu.html). 

I am closing this issue. Feel free to reopen if you are unable to solve the issue with DDP. 

Best, 
Adel
