### ISSUE TITLE
Inference on ASR

### ISSUE THREAD

**Issue by Aksh97** [speechbrain/speechbrain#1027]
Hi @TParcollet @nauman-daw,
I was following the colab notebook ASRfromScratch. Till step 4, it worked perfectly fine. 
After step 4, In the results the folder has following files:

CKPT.yaml  brain.ckpt  counter.ckpt  dataloader-TRAIN.ckpt  model.ckpt  normalizer.ckpt  optimizer.ckpt  scheduler.ckpt

**It does not have asr.ckpt.**

As Given in [((https://colab.research.google.com/drive/1137MD-gAERblRAVhxDnwNXV3YyAiwtxV?usp=sharing))]
Option 2 : 
```
from speechbrain.pretrained import EncoderDecoderASR

asr_model = EncoderDecoderASR.from_hparams(source="your_folder", hparams_file='your_file.yaml', savedir="pretrained_model")
asr_model.transcribe_file('your_file.wav')
```

So when I ran the command, with full path: 
`asr_model = EncoderDecoderASR.from_hparams(source="/app/speechbrain/templates/speech_recognition/ASR/results/CRDNN_BPE_960h_LM/2602", hparams_file='/app/speechbrain/templates/speech_recognition/ASR/new.yaml', savedir="pretrained_model")`

And new.yaml having the same code given in colab:
I got the error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/speechbrain/speechbrain/pretrained/interfaces.py", line 244, in from_hparams
    pretrainer.load_collected(device="cpu")
  File "/app/speechbrain/speechbrain/utils/parameter_transfer.py", line 203, in load_collected
    self._call_load_hooks(paramfiles, device)
  File "/app/speechbrain/speechbrain/utils/parameter_transfer.py", line 218, in _call_load_hooks
    default_hook(obj, loadpath, device=device)
  File "/app/speechbrain/speechbrain/utils/checkpoints.py", line 143, in torch_parameter_transfer
    torch.load(path, map_location=device), strict=False
  File "/home/user/miniconda/lib/python3.8/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/user/miniconda/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/user/miniconda/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained_model/asr.ckpt'`

Please guide me on this, how to solve this issue.

**Comment by TParcollet** [comment]
Hi, you just have to rename the model.ckpt to asr.ckpt :) But you should read entirely the tutorial before.
