### ISSUE TITLE
the function "download_vctk" in voicebank_prepare.py raises an error

### ISSUE THREAD

**Issue by SitalLiang** [speechbrain/speechbrain#1038]
This may be a relatively simple problem.

When I use the function "download_vctk" in "voicebank_prepare.py", an error has occurred about the tensor dimension.

# Load files and downsample
        for filename in get_all_files(dirname, match_and=[".wav"]):
            signal, rate = torchaudio.load(filename)
            downsampled_signal = downsampler(signal.view(1, -1).to(device))

 # Save downsampled file

            torchaudio.save(
                os.path.join(dirname_16k, filename[-12:]),
                downsampled_signal[0].cpu(),
                sample_rate=16000,
                channels_first=False,
            )

Traceback (most recent call last):
  File "/home/lxt/anaconda3/envs/test2/test2.py", line 91, in <module>
    torchaudio.save(
  File "/home/lxt/anaconda3/envs/test2/lib/python3.8/site-packages/torchaudio/backend/sox_io_backend.py", line 313, in save
    torch.ops.torchaudio.sox_io_save_audio_file(
RuntimeError: Input tensor has to be 2D.

I guess it may be because "downsampled_signal[0]" changes the down sampled tensor data to 1D, but after removing [0], new problems will appear. It can generate files normally, but the generated ".wav" file cannot be read.
Can you provide a solution？Thank you very much.

**Comment by SitalLiang** [comment]
The function parameter setting is incorrect. This is the result of modification.

# Save downsampled file
            torchaudio.save(
                os.path.join(dirname_16k, filename[-12:]),
                downsampled_signal.cpu(),
                sample_rate=16000,
                channels_first=True,
            )
