### ISSUE TITLE
Multi-GPU training on speech separation task, but the memory usage can only be arranged on the first GPU

### ISSUE THREAD

**Issue by YUCHEN005** [speechbrain/speechbrain#1082]
Hi authors, thank you first for such a nice platform for speech processing research.

Recently, I use multiple gpu to train on the Sepformer on libri2mix-360 dataset (speech separation task), but I find that the memory usage can only be arranged on the first gpu, leaving the followings empty. As a result, the batch size cannot be increased, so that the training is slow. I wonder if it is possible to make use of all gpus for memory usage?

Thank you.

**Comment by mravanelli** [comment]
Interesting. According to what I remember, we didn't try the sepformer so far on multiple gpus. I think we can take this opportunity to do some tests and fixes. Could you please take a look @ycemsubakan? @aheba can help you with that as well.

**Comment by ycemsubakan** [comment]
Hi @YUCHEN005 , please take a look at this issue https://github.com/speechbrain/speechbrain/issues/659 

Can you try running with 

```
 python -m torch.distributed.launch --nproc_per_node=2 train.py hparams/sepformer.yaml --data_folder /putin_yourdatapath --distributed_launch --distributed_backend='nccl'
```

At the time we verified that it worked properly with @aheba .

**Comment by YUCHEN005** [comment]
Thank you very much @mravanelli @ycemsubakan , the command works. But I find some new issues that seem strange. 

Now I have a cluster node with 4 gpus (nvidia v100 48g), and my cmd is roughly like: 
`CUDA_VISIBLE_DEVICES=0,1 python -m ... --nproc_per_node=2 train.py ...`

This works okay and I find the gpu 0,1 are both full memory, but when I submit another similar task using gpu 2,3 with cmd:
`CUDA_VISIBLE_DEVICES=2,3` python -m ... --nproc_per_node=2 train.py ...`

A bug is given as follows, I wonder if the first task have occupied not only gpu 0,1?
`Traceback (most recent call last):
  File "/home3/huyuchen/anaconda3/envs/asteroid/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home3/huyuchen/anaconda3/envs/asteroid/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home3/huyuchen/anaconda3/envs/asteroid/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home3/huyuchen/anaconda3/envs/asteroid/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home3/huyuchen/anaconda3/envs/asteroid/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home3/huyuchen/anaconda3/envs/asteroid/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/home3/huyuchen/anaconda3/envs/asteroid/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home3/huyuchen/anaconda3/envs/asteroid/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 237, in launch_agent
    result = agent.run()
  File "/home3/huyuchen/anaconda3/envs/asteroid/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home3/huyuchen/anaconda3/envs/asteroid/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 700, in run
    result = self._invoke_run(role)
  File "/home3/huyuchen/anaconda3/envs/asteroid/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 822, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/home3/huyuchen/anaconda3/envs/asteroid/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home3/huyuchen/anaconda3/envs/asteroid/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 670, in _initialize_workers
    self._rendezvous(worker_group)
  File "/home3/huyuchen/anaconda3/envs/asteroid/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home3/huyuchen/anaconda3/envs/asteroid/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 530, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/home3/huyuchen/anaconda3/envs/asteroid/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(
RuntimeError: Address already in use`

Hope you can help, I have never met such issue with multi-gpu training. Thank you again.

**Comment by ycemsubakan** [comment]
I see, for some reason the DDP is expecting the first 2 gpus it seems. I am not familiar with this issue. But maybe @aheba knows about this?

**Comment by TParcollet** [comment]
This is normal. DDP uses internet connection with a precise port for each job. Hence, if on the same machine you have multiple DDP, different master_port should be given or they will interract with each others and cause this issue. See [this tutorial](https://colab.research.google.com/drive/13pBUacPiotw1IvyffvGZ-HrtBr9T6l15?usp=sharing)

**Comment by YUCHEN005** [comment]
That works @TParcollet  Thank you a lot!
