### ISSUE TITLE
problem ERROR for Voxceleb recipre when use own data

### ISSUE THREAD

**Issue by TianlongKong** [speechbrain/speechbrain#1088]
This problem occurs when the self-owned data is used for speaker recognition tasks
speechbrain.core - 6.2M trainable parameters in LanguageBrain
speechbrain.utils.checkpoints - Loading a checkpoint from olr_results/1999/save/CKPT+2021-11-03+17-15-56+00
speechbrain.utils.epoch_loop - Going into epoch 8
  0%|                                                                     | 3/2954 [00:01<19:34,  2.51it/s, train_loss=11]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 178, in <module>
    language_brain.fit(
  File "/root/anaconda3/lib/python3.8/site-packages/speechbrain/core.py", line 1031, in fit
    for batch in t:
  File "/root/anaconda3/lib/python3.8/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/root/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1183, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/root/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/root/anaconda3/lib/python3.8/site-packages/speechbrain/dataio/batch.py", line 125, in __init__
    padded = PaddedData(*padding_func(values, **padding_kwargs))
  File "/root/anaconda3/lib/python3.8/site-packages/speechbrain/utils/data_utils.py", line 414, in batch_pad_right
    padded, valid_percent = pad_right_to(
  File "/root/anaconda3/lib/python3.8/site-packages/speechbrain/utils/data_utils.py", line 342, in pad_right_to
    assert len(target_shape) == tensor.ndim
AssertionError

**Comment by TParcollet** [comment]
you might habe multi_channel audio.

**Comment by aheba** [comment]
@TianlongKong , are you able to solve your problem? Can you add some print on the shape of your target tensor... 


other tips for speaker ID (I saw you have 2954 iteration, so your corpus is about ((2954*32*3)/360~78Hours) where voxceleb 1&2 is about 700H...
So, for learning a good embeddings, make sure that you have more than 40 chunks (chunk=3.0) per speaker, otherwise, you may have worth performance...

**Comment by TianlongKong** [comment]
> you might habe multi_channel audio.

Thank you, I am removing dual-channel data from my own data. 
I will give feedback in time when there is a result.

**Comment by TianlongKong** [comment]
> @TianlongKong , are you able to solve your problem? Can you add some print on the shape of your target tensor...
> 
> other tips for speaker ID (I saw you have 2954 iteration, so your corpus is about ((2954_32_3)/360~78Hours) where voxceleb 1&2 is about 700H... So, for learning a good embeddings, make sure that you have more than 40 chunks (chunk=3.0) per speaker, otherwise, you may have worth performance...



> @TianlongKong , are you able to solve your problem? Can you add some print on the shape of your target tensor...
> 
> other tips for speaker ID (I saw you have 2954 iteration, so your corpus is about ((2954_32_3)/360~78Hours) where voxceleb 1&2 is about 700H... So, for learning a good embeddings, make sure that you have more than 40 chunks (chunk=3.0) per speaker, otherwise, you may have worth performance...

Thank you, I removed the dual-channel data and the code can run. Also I will try your suggestion.

**Comment by TianlongKong** [comment]
> you might habe multi_channel audio.

Thank you, I removed the dual-channel data and the code can run.
