### ISSUE TITLE
How to modify configs to run on multigpus

### ISSUE THREAD

**Issue by Jxu-Thu** [speechbrain/speechbrain#1121]
Thanks for your great codes!

 I am conducting experiments in 
https://github.com/speechbrain/speechbrain/blob/13798b9576779b82f70c8f65dc0e166da5c09c10/recipes/fluent-speech-commands/direct/hparams/train.yaml#L60

There is 

--
run_opts: {"device":"cuda:0"}
--

I  follow the https://speechbrain.readthedocs.io/en/latest/multigpu.html to run the command 

python -m torch.distributed.launch --nproc_per_node=2 train.py hparams/train.yaml \
--distributed_launch \
--distributed_backend='nccl' 

But I got the error.

FileNotFoundError: [Errno 2] No such file or directory: 'pretrained_models/EncoderDecoderASR-4492157775201762583/normalizer.ckpt'

Should I modify the yaml to run on multigpus? How can I modify?

**Comment by aheba** [comment]
Hi @Jxu-Thu ,

Generally we call DDP using Speechbrain like:
```
python -m torch.distributed.launch --nproc_per_node=2 experiment.py hyperparams.yaml --distributed_launch=True --distributed_backend='nccl'
```

this mean that `torch.distributed.launch` run two process with hidden bash args like `RANK/LOCAL_RANK` and are used by the toolkit, for more information, check this:
https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/utils/distributed.py

About your issue, in our core program, we force the switch to the right GPU (local_rank process) using:
https://github.com/speechbrain/speechbrain/blob/13798b9576779b82f70c8f65dc0e166da5c09c10/speechbrain/core.py#L288


Do you see any problem on running DDP with this recipe ?

**Comment by Jxu-Thu** [comment]
I run the config in speechbrain/recipes/fluent-speech-commands/direct with command 

 
`python -m torch.distributed.launch --nproc_per_node=1 train.py hparams/train.yaml --distributed_launch `--distributed_backend=nccl`

It runs normally.

When I change to multi GPUs 

`python -m torch.distributed.launch --nproc_per_node=2 train.py hparams/train.yaml --distributed_launch --distributed_backend=nccl`

I got the error 

Traceback (most recent call last):
  File "train.py", line 288, in <module>
    hparams = load_hyperpyyaml(fin, overrides)
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/hyperpyyaml/core.py", line 182, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=yaml.Loader)
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/yaml/constructor.py", line 107, in construct_object
    for dummy in generator:
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/yaml/constructor.py", line 102, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/hyperpyyaml/core.py", line 487, in _apply_function
    return callable_(*args, **kwargs)
  File "/blob/v-jinx/acent_asr/speechbrain-059/speechbrain/pretrained/interfaces.py", line 239, in from_hparams
    pretrainer.load_collected(device="cpu")
  File "speechbrain-059/speechbrain/utils/parameter_transfer.py", line 203, in load_collected
    self._call_load_hooks(paramfiles, device)
  File "speechbrain-059/speechbrain/utils/parameter_transfer.py", line 218, in _call_load_hooks
    default_hook(obj, loadpath, device=device)
  File "speechbrain-059/speechbrain/processing/features.py", line 1210, in _load
    stats = torch.load(path, map_location=device)
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained_models/EncoderDecoderASR--2122307461367217928/normalizer.ckpt'



I suspect the error is caused by 
https://github.com/speechbrain/speechbrain/blob/13798b9576779b82f70c8f65dc0e166da5c09c10/recipes/fluent-speech-commands/direct/hparams/train.yaml#L60

Could you help me solve the issue？

**Comment by Jxu-Thu** [comment]
Here is another issue. When I manually put the normalozer.ckpt at the target path. The previous bug seems to be fixed. But I got another bug as follows:

Traceback (most recent call last):
  File "train.py", line 336, in <module>
    slu_brain.fit(
  File "speechbrain-059/speechbrain/core.py", line 1022, in fit
    loss = self.fit_batch(batch)
  File "train.py", line 148, in fit_batch
    predictions = self.compute_forward(batch, sb.Stage.TRAIN)
  File "train.py", line 69, in compute_forward
    encoder_out = self.hparams.slu_enc(ASR_encoder_out)
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "speechbrain-059/speechbrain/nnet/containers.py", line 144, in forward
    x = layer(x)
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "speechbrain-059/speechbrain/nnet/RNN.py", line 271, in forward
    output, hn = self.rnn(x)
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 661, in forward
    result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cuda:1
Killing subprocess 68695
Killing subprocess 68696
Traceback (most recent call last):
  File "/home/.conda/envs/slu/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/.conda/envs/slu/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/.conda/envs/slu/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)

**Comment by Jxu-Thu** [comment]
I have found the root issue!

Please see here

https://github.com/speechbrain/speechbrain/blob/13798b9576779b82f70c8f65dc0e166da5c09c10/speechbrain/pretrained/interfaces.py#L97

this self.device is different from the device in core.py

So I delete 
https://github.com/speechbrain/speechbrain/blob/13798b9576779b82f70c8f65dc0e166da5c09c10/speechbrain/pretrained/interfaces.py#L97

and manually put modules into the device (run_opts) at the train.py as follows:
   ```
if 'asr_model' in hparams:
        hparams['asr_model'].device = run_opts['device']
        for mod in hparams['asr_model'].modules:
            hparams['asr_model'].modules[mod].to(run_opts['device'])
```

The bugs can be fixed

**Comment by TParcollet** [comment]
Honestly, I think that the only thing missing is that asr_model should be added to modules: in hyperparams. Could you try ? If this works, I'll fix with a PR. It should work. (modules in yaml is what will be pushed to the right device).

**Comment by Jxu-Thu** [comment]
Thanks!
 When I add it to modules, I got
TypeError: speechbrain.pretrained.interfaces.EncoderDecoderASR is not a Module subclass

**Comment by TParcollet** [comment]
Oh right, this sucks but I thought it would be solved @Gastron isn't it merged already ?

**Comment by TParcollet** [comment]
@Jxu-Thu are you on the master or develop branch ?

**Comment by Jxu-Thu** [comment]
I am on the code version 0.5.9 (tag)

**Comment by TParcollet** [comment]
Oh ok, this is why. I think that we changed only recently that. If you switch to the develop branch (I am not even sure that we issued a new version with this fix), it will work.

**Comment by Jxu-Thu** [comment]
Thanks for your time and kind reply @TParcollet @aheba. 

I close the issue since I think it has been solved.
