### ISSUE TITLE
Mismatch of output when trying the model 

### ISSUE THREAD

**Issue by sentient-22** [speechbrain/speechbrain#1187]
I was looking for something related to speech recognition where they can use speech tool to achieve their day to day task such as save Mahesh as contact, please call sandeep if they have poor vision strength etc.

The linguistic culture is Indian, tried speechbrain/asr-wav2vec2-commonvoice-en
I spoke PLEASE CALL MAHESH got.

![image](https://user-images.githubusercontent.com/30064883/145747774-a76c8c65-61f3-4d9d-b9e0-c1819a41fc8b.png)

In order to resolve the difference, I thought to train on data available from here 
[raw speech datset](https://github.com/AI4Bharat/NPTEL2020-Indian-English-Speech-Dataset#nptel2020---indian-english-speech-dataset)

However upon running I faced this issue:
`!python train.py hparams/train_en_with_wav2vec.yaml --data_folder=/content/nptel-pure
got this error 
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 310, in <module>
    character_coverage=hparams["character_coverage"],
  File "/content/speechbrain/recipes/CommonVoice/ASR/seq2seq/speechbrain/speechbrain/tokenizers/SentencePiece.py", line 170, in __init__
    run_on_main(self._train_BPE)
  File "/content/speechbrain/recipes/CommonVoice/ASR/seq2seq/speechbrain/speechbrain/utils/distributed.py", line 61, in run_on_main
    func(*args, **kwargs)
  File "/content/speechbrain/recipes/CommonVoice/ASR/seq2seq/speechbrain/speechbrain/tokenizers/SentencePiece.py", line 304, in _train_BPE
    spm.SentencePieceTrainer.train(query)
  File "/usr/local/lib/python3.7/dist-packages/sentencepiece/__init__.py", line 407, in Train
    return SentencePieceTrainer._TrainFromString(arg)
  File "/usr/local/lib/python3.7/dist-packages/sentencepiece/__init__.py", line 385, in _TrainFromString
    return _sentencepiece.SentencePieceTrainer__TrainFromString(arg)
RuntimeError: Internal: src/trainer_interface.cc(406) [!sentences_.empty()] `

It would be great if anyone could help me translate the error language

**Comment by TParcollet** [comment]
As this this related to the tokeniser, I would suggest you to do some data preparation cleaning. E.g., from the error, consider checking that some sentences aren't empty or only containing character that are not decoded properly.

**Comment by Adel-Moumen** [comment]
Hello, 

The issue seems to be inactive and this [comment](https://github.com/speechbrain/speechbrain/issues/1187#issuecomment-992282751) is giving the right path to follow. I am therefore closing this issue. Please, feel free to reopen it if needed. 

Best, 
Adel
