### ISSUE TITLE
DDP error with transformer wav2vec2.0 ASR

### ISSUE THREAD

**Issue by JaheimLee** [speechbrain/speechbrain#1231]
Here is my running command:'
```python
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 train_with_wav2vect.py hparams/train_ASR_transformer_with_wav2vect.yaml --data_folder ../../aishell/ --distributed_launch --distributed_backend='nccl' --find_unused_parameters
```
And when going into epoch 1, an runtime error raised:
```python
Traceback (most recent call last):
  File "/data/lijinghui/speechbrain/recipes/AISHELL-1/ASR/transformer/train_with_wav2vect.py", line 421, in <module>
    asr_brain.fit(
  File "/data/miniconda3/envs/ljh_py_latest/lib/python3.9/site-packages/speechbrain/core.py", line 1033, in fit
    loss = self.fit_batch(batch)
  File "/data/lijinghui/speechbrain/recipes/AISHELL-1/ASR/transformer/train_with_wav2vect.py", line 124, in fit_batch
    predictions = self.compute_forward(batch, sb.Stage.TRAIN)
  File "/data/lijinghui/speechbrain/recipes/AISHELL-1/ASR/transformer/train_with_wav2vect.py", line 40, in compute_forward
    feats = self.hparams.augmentation(feats)
  File "/data/miniconda3/envs/ljh_py_latest/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/miniconda3/envs/ljh_py_latest/lib/python3.9/site-packages/speechbrain/lobes/augment.py", line 109, in forward
    x = self.time_warp(x)
  File "/data/miniconda3/envs/ljh_py_latest/lib/python3.9/site-packages/speechbrain/lobes/augment.py", line 147, in time_warp
    x[:, :, :w] = left
RuntimeError: Output 0 of SliceBackward0 is a view and is being modified inplace. This view was created inside a custom Function (or because an input was returned as-is) and the autograd logic to handle view+inplace would override the custom backward associated with the custom Function, leading to incorrect gradients. This behavior is forbidden. You can fix this by cloning the output of the custom Function.
```

**Comment by mravanelli** [comment]
That's for you @aheba ;)

**Comment by mravanelli** [comment]
@aheba any idea about this?

**Comment by Adel-Moumen** [comment]
Hello @JaheimLee, 

Is your issue still up? 

Thanks and sorry for the delay....
