### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode when using a dataset that cannot be fully decoded by "utf-8" (dutch language dataset)

### ISSUE THREAD

**Issue by Yibin-Lei** [speechbrain/speechbrain#1238]
Hi,
I am now using your ASR recipe to train my Dutch ASR models. But when training the language model, there is a bug that the dataset with some special Dutch token can be decoded by "UTF-8" properly. Do you have some solutions to solve this problem? Thanks! 

Traceback (most recent call last):
  File "train.py", line 252, in <module>
    train_data, valid_data, test_data = dataio_prepare(hparams)
  File "train.py", line 185, in dataio_prepare
    datasets = load_dataset(
  File "/home/nfs/yuanyuanzhang/.conda/envs/sb38/lib/python3.8/site-packages/datasets/load.py", line 1694, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/nfs/yuanyuanzhang/.conda/envs/sb38/lib/python3.8/site-packages/datasets/builder.py", line 595, in download_and_prepare
    self._download_and_prepare(
  File "/home/nfs/yuanyuanzhang/.conda/envs/sb38/lib/python3.8/site-packages/datasets/builder.py", line 683, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/home/nfs/yuanyuanzhang/.conda/envs/sb38/lib/python3.8/site-packages/datasets/builder.py", line 1135, in _prepare_split
    for key, table in utils.tqdm(
  File "/home/nfs/yuanyuanzhang/.conda/envs/sb38/lib/python3.8/site-packages/tqdm/std.py", line 1168, in __iter__
    for obj in iterable:
  File "/home/nfs/yuanyuanzhang/.conda/envs/sb38/lib/python3.8/site-packages/datasets/packaged_modules/text/text.py", line 60, in _generate_tables
    batch = f.read(self.config.chunksize)
  File "/home/nfs/yuanyuanzhang/.conda/envs/sb38/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 1483: invalid continuation byte

**Comment by Gastron** [comment]
The first thing to check is: is your data encoded in UTF-8?

**Comment by Yibin-Lei** [comment]
Thanks! I have converted my data to UTF-8 encoding format and it works.
