### ISSUE TITLE
Solving circular dependency error

### ISSUE THREAD

**Issue by Dabuk** [speechbrain/speechbrain#1240]
on custom dataset of mine, I see this

speechbrain.utils.epoch_loop - Going into epoch 1
  0%|                                                                                                                              | 0/119126 [00:00<?, ?it/s]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 401, in <module>
    asr_brain.fit(
  File "/home/dabuk/software/speechbrain/speechbrain/core.py", line 1032, in fit
    for batch in t:
  File "/home/dabuk/anaconda3/envs/speechbrain/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/dabuk/anaconda3/envs/speechbrain/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/dabuk/anaconda3/envs/speechbrain/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 563, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/dabuk/anaconda3/envs/speechbrain/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dabuk/anaconda3/envs/speechbrain/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dabuk/software/speechbrain/speechbrain/dataio/dataset.py", line 165, in __getitem__
    return self.pipeline.compute_outputs({"id": data_id, **data_point})
  File "/home/dabuk/software/speechbrain/speechbrain/utils/data_pipeline.py", line 454, in compute_outputs
    self._prepare_run(data)
  File "/home/dabuk/software/speechbrain/speechbrain/utils/data_pipeline.py", line 508, in _prepare_run
    self._exec_order = list(
  File "/home/dabuk/software/speechbrain/speechbrain/utils/depgraph.py", line 242, in get_evaluation_order
    for ind in toposort(start_ind, []):
  File "/home/dabuk/software/speechbrain/speechbrain/utils/depgraph.py", line 232, in toposort
    for ind in toposort(to_ind, visited=here):
  File "/home/dabuk/software/speechbrain/speechbrain/utils/depgraph.py", line 232, in toposort
    for ind in toposort(to_ind, visited=here):
  File "/home/dabuk/software/speechbrain/speechbrain/utils/depgraph.py", line 232, in toposort
    for ind in toposort(to_ind, visited=here):
  File "/home/dabuk/software/speechbrain/speechbrain/utils/depgraph.py", line 221, in toposort
    raise CircularDependencyError(
speechbrain.utils.depgraph.CircularDependencyError: f258521d-e5f0-489d-bfbb-9f5458ed89e1 -> e1496a28-51b6-46ea-bd82-c3f8d3d4e737 -> 52dfe0e4-0045-4803-a9dc-8b521e9630c6 -> 52dfe0e4-0045-4803-a9dc-8b521e9630c6

Is there a way to go about debugging this ?
what artifacts in the dataset can cause this ?

**Comment by Dabuk** [comment]
it was an issue with dynamic data keys

**Comment by alamnasim** [comment]
Hi @Dabuk 
I am also facing same issue while training on SAVEE and RAVDESS. Can You please let me know how did you solved this issue.
