### ISSUE TITLE
librispeech conformer multiigpu error

### ISSUE THREAD

**Issue by Dabuk** [speechbrain/speechbrain#1245]
I'm seeing this error for mult-gpu case with the librispeech conformer small model. Any ideas on what this could be ?

speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: results/transformer/7775
librispeech_prepare - Skipping preparation, completed in previous run.
speechbrain.pretrained.fetching - Fetch lm.ckpt: Using existing file/symlink in results/transformer/7775/save/lm.ckpt.
speechbrain.pretrained.fetching - Fetch tokenizer.ckpt: Using existing file/symlink in results/transformer/7775/save/tokenizer.ckpt.
speechbrain.utils.parameter_transfer - Loading pretrained files for: lm, tokenizer
speechbrain.core - 13.3M trainable parameters in ASR
speechbrain.utils.checkpoints - Loading a checkpoint from results/transformer/7775/save/CKPT+2022-01-11+23-43-40+00
speechbrain.utils.epoch_loop - Going into epoch 16
100%|███████████████████████████████████████████████████████████████████████████████████████████████▉| 17577/17578 [3:51:14<00:00,  1.27it/s, train_loss=18.9]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 445, in <module>
    asr_brain.fit(
  File "/home/dabuk/software/speechbrain/speechbrain/core.py", line 1034, in fit
    loss = self.fit_batch(batch)
  File "train.py", line 152, in fit_batch
    predictions = self.compute_forward(batch, sb.Stage.TRAIN)
  File "train.py", line 75, in compute_forward
    enc_out, pred = self.modules.Transformer(
  File "/home/dabuk/envs/speechbrain/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dabuk/envs/speechbrain/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/dabuk/envs/speechbrain/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/dabuk/envs/speechbrain/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/dabuk/envs/speechbrain/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
TypeError: Caught TypeError in replica 5 on device 5.
Original Traceback (most recent call last):
  File "/home/dabuk/envs/speechbrain/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/dabuk/envs/speechbrain/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 2 required positional arguments: 'src' and 'tgt'

**Comment by b-med** [comment]
Hi, I faced this error too. I think it's something related to DataParallel when it finds itself with a batch of size 1 in one of the gpus at the end of the epoch.
The main workaround I found were to use bigger batch sizes in order to reduce the probability of this condition.
Also I think the drop_last option may make the problem disappear since you omit the last batch.
To be confirmed...

**Comment by TParcollet** [comment]
Hi everyone, indeed the drop_last parameter may help you with that. HOWEVER, I would highly encourage you to switch to DDP instead of DP (improved multi GPU performance).

**Comment by Dabuk** [comment]
where is the drop_last option available ?

**Comment by Gastron** [comment]
> where is the drop_last option available ?

It is an argument to the PyTorch DataLoader. If using Brain to create the DataLoader, use the train_loader_kwargs argument: https://speechbrain.readthedocs.io/en/latest/API/speechbrain.core.html#speechbrain.core.Brain.fit

**Comment by mravanelli** [comment]
@Dabuk @b-med, does drop_last solve your problem?

**Comment by Dabuk** [comment]
started using distributed data parallel instead. that is working
