### ISSUE TITLE
I tried to run a librispeech transformer recipe with 8 GPU but a word error rate remains very large.

### ISSUE THREAD

**Issue by ken57** [speechbrain/speechbrain#1319]
I tried to run a librispeech transformer recipe with 8 GPU by using DDP (https://github.com/speechbrain/speechbrain/blob/develop/recipes/LibriSpeech/ASR/transformer/train.py) but a word error rate remains very large(around 100%) in spite of 10 epochs.
```
epoch: 1, lr: 1.00e+00, steps: 4056, optimizer: Adam - train loss: 2.50e+02 - valid loss: 1.32e+02, valid ACC: 1.97e-01
epoch: 2, lr: 1.17e-04, steps: 12845, optimizer: Adam - train loss: 2.11e+02 - valid loss: 1.27e+02, valid ACC: 2.24e-01
epoch: 3, lr: 1.97e-04, steps: 21634, optimizer: Adam - train loss: 2.04e+02 - valid loss: 1.25e+02, valid ACC: 2.43e-01
epoch: 4, lr: 2.07e-04, steps: 30423, optimizer: Adam - train loss: 1.98e+02 - valid loss: 1.23e+02, valid ACC: 2.58e-01
epoch: 5, lr: 1.82e-04, steps: 39212, optimizer: Adam - train loss: 1.93e+02 - valid loss: 1.21e+02, valid ACC: 2.67e-01
epoch: 6, lr: 1.65e-04, steps: 48001, optimizer: Adam - train loss: 1.89e+02 - valid loss: 1.21e+02, valid ACC: 2.71e-01
epoch: 7, lr: 1.51e-04, steps: 56790, optimizer: Adam - train loss: 1.85e+02 - valid loss: 1.21e+02, valid ACC: 2.70e-01
epoch: 8, lr: 1.41e-04, steps: 65579, optimizer: Adam - train loss: 1.82e+02 - valid loss: 1.22e+02, valid ACC: 2.67e-01
epoch: 9, lr: 1.32e-04, steps: 74368, optimizer: Adam - train loss: 1.79e+02 - valid loss: 1.23e+02, valid ACC: 2.64e-01
epoch: 10, lr: 1.25e-04, steps: 83157, optimizer: Adam - train loss: 1.76e+02 - valid loss: 1.24e+02, valid ACC: 2.61e-01, valid WER: 96.31
```
I ran the following command.
```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node=8 train.py hparams/transformer.yaml --distributed_launch --distributed_backend='nccl'
```
I reduced batch_size from 16 to 4 in order to avoid Out Of Memory Error and changed gradient_accumulation from 4 to 1 according to https://github.com/speechbrain/speechbrain/issues/899.
I also tried to train setting gradient_accumulation to 4 and 2, but the results were no different.
My environment is as follows.

```
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.27

Python version: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-1063-aws-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB

Nvidia driver version: 460.106.00
```

A commit hash of the speechbrain is d6bfe13.
Could you give me any hint?
Thanks for your help.

**Comment by TParcollet** [comment]
Hi, may I ask you why the first epoch is only 4K steps while the others are 8k +? It looks like you changed the hyperparameters in between or something? Or maybe restarted from a previous checkpoint with different hyperparameters ?

**Comment by TParcollet** [comment]
The LR is also not increasing. Could you please remove all checkpoints (clean your exp folder) and restart the experiment ? I don't understand what is going on here from the logs.

**Comment by ken57** [comment]
Thank you for your quick response.
Please wait a moment while I check it.

**Comment by ken57** [comment]
I'm sorry.
I am not available for a while, so @kenro515 will do the experiment instead of me.

**Comment by kenro515** [comment]
Hi. I'm @kenRo515.
When I ran this script of training Transformer, I got the same results above it.
My experimental environment is as follows.
```
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A
OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.27
Python version: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-1063-aws-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB
Nvidia driver version: 450.142.00
Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.18.5
[pip3] numpydoc==1.1.0
[pip3] torch==1.10.0
[pip3] torch-model-archiver==0.5.0b20211117
[pip3] torch-workflow-archiver==0.2.0b20211118
[pip3] torchaudio==0.10.0
[pip3] torchserve==0.5.0b20211117
[pip3] torchtext==0.11.0
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl
[conda] captum                    0.4.1                         0    pytorch
[conda] cudatoolkit               11.1.1               h6406543_9    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0            12_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            12_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            12_linux64_mkl    conda-forge
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py38h95df7f1_0    conda-forge
[conda] mkl_fft                   1.3.1            py38h8666266_1    conda-forge
[conda] mkl_random                1.2.2            py38h1abd341_0    conda-forge
[conda] mypy_extensions           0.4.3            py38h578d9bd_4    conda-forge
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] numpydoc                  1.1.0                      py_1    conda-forge
[conda] pytorch                   1.10.0          py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch-model-archiver      0.5.0                    py38_0    pytorch
[conda] torch-workflow-archiver   0.2.0                    py38_0    pytorch
[conda] torchaudio                0.10.0               py38_cu111    pytorch
[conda] torchserve                0.5.0                    py38_0    pytorch
[conda] torchtext                 0.11.0                     py38    pytorch
[conda] torchvision               0.11.1               py38_cu111    pytorch
```

Referring to your advice, I tried to remove all checkpoints and experimented with the condition, the batch size is 4, and gradient accumulation is 1.
The command of running the script is as follows.
```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 nohup python -m torch.distributed.launch --nproc_per_node=8 train.py hparams/transformer.yaml --distributed_launch --distributed_backend='nccl' & disown
```
However, we can not train the model with this script.
These results are as follows.
```
epoch: 1, lr: 8.02e-05, steps: 8789, optimizer: Adam - train loss: 2.35e+02 - valid loss: 1.31e+02, valid ACC: 2.07e-01
epoch: 2, lr: 1.60e-04, steps: 17578, optimizer: Adam - train loss: 2.06e+02 - valid loss: 1.26e+02, valid ACC: 2.38e-01
epoch: 3, lr: 2.22e-04, steps: 26367, optimizer: Adam - train loss: 2.03e+02 - valid loss: 1.24e+02, valid ACC: 2.47e-01
epoch: 4, lr: 1.92e-04, steps: 35156, optimizer: Adam - train loss: 1.95e+02 - valid loss: 1.22e+02, valid ACC: 2.61e-01
epoch: 5, lr: 1.72e-04, steps: 43945, optimizer: Adam - train loss: 1.91e+02 - valid loss: 1.21e+02, valid ACC: 2.69e-01
epoch: 6, lr: 1.57e-04, steps: 52734, optimizer: Adam - train loss: 1.87e+02 - valid loss: 1.21e+02, valid ACC: 2.71e-01
epoch: 7, lr: 1.45e-04, steps: 61523, optimizer: Adam - train loss: 1.83e+02 - valid loss: 1.22e+02, valid ACC: 2.70e-01
epoch: 8, lr: 1.36e-04, steps: 70312, optimizer: Adam - train loss: 1.80e+02 - valid loss: 1.22e+02, valid ACC: 2.67e-01
epoch: 9, lr: 1.28e-04, steps: 79101, optimizer: Adam - train loss: 1.77e+02 - valid loss: 1.24e+02, valid ACC: 2.63e-01
epoch: 10, lr: 1.22e-04, steps: 87890, optimizer: Adam - train loss: 1.74e+02 - valid loss: 1.25e+02, valid ACC: 2.59e-01, valid WER: 95.34
epoch: 11, lr: 1.16e-04, steps: 96679, optimizer: Adam - train loss: 1.71e+02 - valid loss: 1.26e+02, valid ACC: 2.56e-01
epoch: 12, lr: 1.11e-04, steps: 105468, optimizer: Adam - train loss: 1.68e+02 - valid loss: 1.28e+02, valid ACC: 2.52e-01
epoch: 13, lr: 1.07e-04, steps: 114257, optimizer: Adam - train loss: 1.66e+02 - valid loss: 1.29e+02, valid ACC: 2.49e-01
epoch: 14, lr: 1.03e-04, steps: 123046, optimizer: Adam - train loss: 1.64e+02 - valid loss: 1.31e+02, valid ACC: 2.47e-01
epoch: 15, lr: 9.94e-05, steps: 131835, optimizer: Adam - train loss: 1.61e+02 - valid loss: 1.32e+02, valid ACC: 2.44e-01
epoch: 16, lr: 9.62e-05, steps: 140624, optimizer: Adam - train loss: 1.59e+02 - valid loss: 1.33e+02, valid ACC: 2.40e-01
epoch: 17, lr: 9.34e-05, steps: 149413, optimizer: Adam - train loss: 1.57e+02 - valid loss: 1.35e+02, valid ACC: 2.39e-01
epoch: 18, lr: 9.07e-05, steps: 158202, optimizer: Adam - train loss: 1.56e+02 - valid loss: 1.36e+02, valid ACC: 2.35e-01
epoch: 19, lr: 8.83e-05, steps: 166991, optimizer: Adam - train loss: 1.54e+02 - valid loss: 1.38e+02, valid ACC: 2.33e-01
epoch: 20, lr: 8.61e-05, steps: 175780, optimizer: Adam - train loss: 1.53e+02 - valid loss: 1.39e+02, valid ACC: 2.32e-01, valid WER: 95.16
epoch: 21, lr: 8.40e-05, steps: 184569, optimizer: Adam - train loss: 1.51e+02 - valid loss: 1.40e+02, valid ACC: 2.29e-01
epoch: 22, lr: 8.21e-05, steps: 193358, optimizer: Adam - train loss: 1.50e+02 - valid loss: 1.41e+02, valid ACC: 2.27e-01
epoch: 23, lr: 8.03e-05, steps: 202147, optimizer: Adam - train loss: 1.48e+02 - valid loss: 1.43e+02, valid ACC: 2.27e-01
epoch: 24, lr: 7.86e-05, steps: 210936, optimizer: Adam - train loss: 1.47e+02 - valid loss: 1.44e+02, valid ACC: 2.24e-01
epoch: 25, lr: 7.70e-05, steps: 219725, optimizer: Adam - train loss: 1.46e+02 - valid loss: 1.45e+02, valid ACC: 2.24e-01
epoch: 26, lr: 7.55e-05, steps: 228514, optimizer: Adam - train loss: 1.45e+02 - valid loss: 1.46e+02, valid ACC: 2.22e-01
epoch: 27, lr: 7.41e-05, steps: 237303, optimizer: Adam - train loss: 1.44e+02 - valid loss: 1.47e+02, valid ACC: 2.22e-01
epoch: 28, lr: 7.27e-05, steps: 246092, optimizer: Adam - train loss: 1.43e+02 - valid loss: 1.48e+02, valid ACC: 2.22e-01
epoch: 29, lr: 7.15e-05, steps: 254881, optimizer: Adam - train loss: 1.42e+02 - valid loss: 1.49e+02, valid ACC: 2.21e-01
epoch: 30, lr: 7.03e-05, steps: 263670, optimizer: Adam - train loss: 1.41e+02 - valid loss: 1.50e+02, valid ACC: 2.19e-01, valid WER: 1.09e+02
```
I apologize for the trouble, but could you give me a hint?

**Comment by kenro515** [comment]
Hello, @TParcollet

This comment is just a friendly reminder that I am waiting for your response to the following URL.
[https://github.com/speechbrain/speechbrain/issues/1319#issuecomment-1062580459](url)

Could you give me some hints?

**Comment by TParcollet** [comment]
This is buzzing us, we are refactoring a bit this recipe now and we'll release a better and smaller model and recipe very soon.

**Comment by kenro515** [comment]
Hello, @TParcollet

Thanks for your message.

> There is an issue with the LR scheduling, lemme investigate. Could you please try with grad accumulation = 2 or BS = 8 ?
> I tried with batch size = 8 and gradient accumulation = 1.

The command and result are as follows.

・command

```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 nohup python -m torch.distributed.launch --nproc_per_node=8 train.py hparams/transformer.yaml --distributed_launch --distributed_backend='nccl' & disown
```

・results

```
speechbrain.utils.parameter_transfer - Loading pretrained files for: lm, tokenizer
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - 161.6M trainable parameters in ASR
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
speechbrain.utils.epoch_loop - Going into epoch 1
root - Reducer buckets have been rebuilt in this iteration.
root - Reducer buckets have been rebuilt in this iteration.
root - Reducer buckets have been rebuilt in this iteration.
root - Reducer buckets have been rebuilt in this iteration.
 26%|██▌       | 1150/4395 [10:10<28:44,  1.88it/s, train_loss=329]Traceback (most recent call last):
  File "/home/asris/speechbrain-transformer/train.py", line 445, in <module>
    asr_brain.fit(
  File "/home/asris/.local/lib/python3.8/site-packages/speechbrain/core.py", line 1034, in fit
    loss = self.fit_batch(batch)
  File "/home/asris/speechbrain-transformer/train.py", line 152, in fit_batch
    predictions = self.compute_forward(batch, sb.Stage.TRAIN)
  File "/home/asris/speechbrain-transformer/train.py", line 75, in compute_forward
    enc_out, pred = self.modules.Transformer(
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/asris/.local/lib/python3.8/site-packages/speechbrain/lobes/models/transformer/TransformerASR.py", line 197, in forward
    decoder_out, _, _ = self.decoder(
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/asris/.local/lib/python3.8/site-packages/speechbrain/lobes/models/transformer/Transformer.py", line 716, in forward
    output, self_attn, multihead_attn = dec_layer(
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/asris/.local/lib/python3.8/site-packages/speechbrain/lobes/models/transformer/Transformer.py", line 595, in forward
    tgt2, multihead_attention = self.mutihead_attn(
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/asris/.local/lib/python3.8/site-packages/speechbrain/nnet/attention.py", line 762, in forward
    output = self.att(
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 1003, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/nn/functional.py", line 5101, in multi_head_attention_forward
    attn_output, attn_output_weights = _scaled_dot_product_attention(q, k, v, attn_mask, dropout_p)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/nn/functional.py", line 4847, in _scaled_dot_product_attention
    attn = softmax(attn, dim=-1)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/nn/functional.py", line 1680, in softmax
    ret = input.softmax(dim)
RuntimeError: CUDA out of memory. Tried to allocate 22.00 MiB (GPU 2; 15.78 GiB total capacity; 13.74 GiB already allocated; 15.75 MiB free; 14.06 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3695 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3696 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3698 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3699 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3700 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3701 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3702 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 2 (pid: 3697) of binary: /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python3
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/home/asris/speechbrain-transformer/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-03-14_15:20:13
  host      : ip-172-31-28-108.us-west-2.compute.internal
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 3697)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

However, I got the error ``CUDA OUT OF MEMORY.''

Now, I'm running the script with batch size=4 and gradient accumuration=2.
As soon as I finish, I report on this thread.

**Comment by TParcollet** [comment]
Thanks, we are on the refactoring. The model will be much smaller and faster to train.

**Comment by kenro515** [comment]
Hello, @TParcollet

I got the result with batch_size=4 and gradient_accumulation=2.
Unfortunately, in this condition, the model did not learn.
This result is as follows.

```
epoch: 1, lr: 4.01e-05, steps: 4394, optimizer: Adam - train loss: 2.51e+02 - valid loss: 1.34e+02, valid ACC: 1.93e-01
epoch: 2, lr: 8.02e-05, steps: 8788, optimizer: Adam - train loss: 2.10e+02 - valid loss: 1.27e+02, valid ACC: 2.32e-01
epoch: 3, lr: 1.20e-04, steps: 13182, optimizer: Adam - train loss: 2.02e+02 - valid loss: 1.24e+02, valid ACC: 2.42e-01
epoch: 4, lr: 1.60e-04, steps: 17576, optimizer: Adam - train loss: 1.98e+02 - valid loss: 1.23e+02, valid ACC: 2.54e-01
epoch: 5, lr: 2.01e-04, steps: 21970, optimizer: Adam - train loss: 1.95e+02 - valid loss: 1.22e+02, valid ACC: 2.57e-01
epoch: 6, lr: 2.22e-04, steps: 26364, optimizer: Adam - train loss: 1.92e+02 - valid loss: 1.22e+02, valid ACC: 2.58e-01
epoch: 7, lr: 2.06e-04, steps: 30758, optimizer: Adam - train loss: 1.89e+02 - valid loss: 1.22e+02, valid ACC: 2.60e-01
epoch: 8, lr: 1.92e-04, steps: 35152, optimizer: Adam - train loss: 1.85e+02 - valid loss: 1.22e+02, valid ACC: 2.60e-01
epoch: 9, lr: 1.81e-04, steps: 39546, optimizer: Adam - train loss: 1.82e+02 - valid loss: 1.23e+02, valid ACC: 2.61e-01
epoch: 10, lr: 1.72e-04, steps: 43940, optimizer: Adam - train loss: 1.79e+02 - valid loss: 1.24e+02, valid ACC: 2.60e-01, valid WER: 95.56
epoch: 11, lr: 1.64e-04, steps: 48334, optimizer: Adam - train loss: 1.76e+02 - valid loss: 1.25e+02, valid ACC: 2.55e-01
epoch: 12, lr: 1.57e-04, steps: 52728, optimizer: Adam - train loss: 1.73e+02 - valid loss: 1.26e+02, valid ACC: 2.52e-01
epoch: 13, lr: 1.51e-04, steps: 57122, optimizer: Adam - train loss: 1.70e+02 - valid loss: 1.28e+02, valid ACC: 2.48e-01
epoch: 14, lr: 1.45e-04, steps: 61516, optimizer: Adam - train loss: 1.67e+02 - valid loss: 1.29e+02, valid ACC: 2.45e-01
epoch: 15, lr: 1.41e-04, steps: 65910, optimizer: Adam - train loss: 1.65e+02 - valid loss: 1.30e+02, valid ACC: 2.41e-01
epoch: 16, lr: 1.36e-04, steps: 70304, optimizer: Adam - train loss: 1.63e+02 - valid loss: 1.32e+02, valid ACC: 2.38e-01
epoch: 17, lr: 1.32e-04, steps: 74698, optimizer: Adam - train loss: 1.60e+02 - valid loss: 1.33e+02, valid ACC: 2.35e-01
epoch: 18, lr: 1.28e-04, steps: 79092, optimizer: Adam - train loss: 1.58e+02 - valid loss: 1.35e+02, valid ACC: 2.33e-01
epoch: 19, lr: 1.25e-04, steps: 83486, optimizer: Adam - train loss: 1.56e+02 - valid loss: 1.36e+02, valid ACC: 2.31e-01
epoch: 20, lr: 1.22e-04, steps: 87880, optimizer: Adam - train loss: 1.54e+02 - valid loss: 1.38e+02, valid ACC: 2.28e-01, valid WER: 94.14
```

> Thanks, we are on the refactoring. The model will be much smaller and faster to train.

I understand. I am looking forward to the new version.

**Comment by TParcollet** [comment]
Hey folks, we updated the whole librispeech recipe. Now the model should be 1. better; 2. much smaller and therefore easier to train with less GPUs :-)

**Comment by kenro515** [comment]
Hi, @TParcollet.

I ran a new script, and the model started training!
The command and results are as follows.

・command
```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node=8 train.py hparams/transformer.yaml --distributed_launch --distributed_backend='nccl'
```
・results
```
epoch: 1, lr: 3.51e-04, steps: 0, optimizer: Adam - train loss: 2.76e+02 - valid loss: 76.84, valid ACC: 4.88e-01
epoch: 2, lr: 7.03e-04, steps: 0, optimizer: Adam - train loss: 93.05 - valid loss: 26.57, valid ACC: 8.21e-01
epoch: 3, lr: 9.74e-04, steps: 0, optimizer: Adam - train loss: 51.10 - valid loss: 20.37, valid ACC: 8.64e-01
epoch: 4, lr: 8.43e-04, steps: 0, optimizer: Adam - train loss: 38.48 - valid loss: 14.59, valid ACC: 9.04e-01
epoch: 5, lr: 7.54e-04, steps: 0, optimizer: Adam - train loss: 30.65 - valid loss: 12.06, valid ACC: 9.22e-01
epoch: 6, lr: 6.89e-04, steps: 0, optimizer: Adam - train loss: 26.35 - valid loss: 10.67, valid ACC: 9.31e-01
epoch: 7, lr: 6.37e-04, steps: 0, optimizer: Adam - train loss: 23.55 - valid loss: 9.69, valid ACC: 9.36e-01
epoch: 8, lr: 5.96e-04, steps: 0, optimizer: Adam - train loss: 21.41 - valid loss: 8.90, valid ACC: 9.43e-01
epoch: 9, lr: 5.62e-04, steps: 0, optimizer: Adam - train loss: 19.77 - valid loss: 8.36, valid ACC: 9.46e-01
epoch: 10, lr: 5.33e-04, steps: 0, optimizer: Adam - train loss: 18.52 - valid loss: 7.97, valid ACC: 9.49e-01, valid WER: 6.49
epoch: 11, lr: 5.09e-04, steps: 0, optimizer: Adam - train loss: 17.50 - valid loss: 7.65, valid ACC: 9.51e-01
epoch: 12, lr: 4.87e-04, steps: 0, optimizer: Adam - train loss: 16.63 - valid loss: 7.32, valid ACC: 9.54e-01
epoch: 13, lr: 4.68e-04, steps: 0, optimizer: Adam - train loss: 15.80 - valid loss: 7.20, valid ACC: 9.54e-01
```

Thanks for your support!

ps: I found and fixed some bug. I am preparing the pull request. As soon as it is ready, I will contact you.

**Comment by prasanna-kothalkar** [comment]
@kenro515 Thanks for your output results. Also you mentioned some bug in the code. Did the WER improve after fixing that bug or was it from the change in librispeech recipe model itself? Can you please share the bug if it is a small one? Thanks.

**Comment by ken57** [comment]
Thank you for very kind supports.
We could train models by using the new script.
So, I will close this issue.
