### ISSUE TITLE
Devices can only use 'CUDA', not 'CPU'

### ISSUE THREAD

**Issue by cyd12345** [speechbrain/speechbrain#1342]
The device can only use 'CUDA: 0' when using '**\ speechBrain -develop\recipes\TIMIT\Alignment**'. Cuda is still used after changing train.yaml.
The code：

```
if __name__ == "__main__":

    # CLI:
    hparams_file, run_opts, overrides = sb.parse_arguments(sys.argv[1:])

    # Load hyperparameters file with command-line overrides
    with open(hparams_file) as fin:
        hparams = load_hyperpyyaml(fin, overrides)

    # Dataset prep (parsing TIMIT and annotation into csv files)
    from timit_prepare import prepare_timit  # noqa

    # Initialize ddp (useful only for multi-GPU DDP training)
    sb.utils.distributed.ddp_init_group(run_opts)

    # Create experiment directory
    sb.create_experiment_directory(
        experiment_directory=hparams["output_folder"],
        hyperparams_to_save=hparams_file,
        overrides=overrides,
    )

    # multi-gpu (ddp) save data preparation
    run_on_main(
        prepare_timit,
        kwargs={
            "data_folder": hparams["data_folder"],
            "save_json_train": hparams["train_annotation"],
            "save_json_valid": hparams["valid_annotation"],
            "save_json_test": hparams["test_annotation"],
            "phn_set": hparams["phn_set"],
            "skip_prep": hparams["skip_prep"],
        },
    )

    # Dataset IO prep: creating Dataset objects and proper encodings for phones
    train_data, valid_data, test_data, label_encoder = dataio_prep(hparams)

    # Trainer initialization
    align_brain = AlignBrain(
        modules=hparams["modules"],
        opt_class=hparams["opt_class"],
        hparams=hparams,
        run_opts=run_opts,
        checkpointer=hparams["checkpointer"],
    )
    align_brain.label_encoder = label_encoder
```

The input:

`python train.py train.yaml  # I did not enter 'run_opts'.`

The output：

```
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: results/augment_noise_CRDNN/1986
timit_prepare - Skipping preparation, completed in previous run.
speechbrain.core - Info: device arg overridden by command line input to: cuda:0
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 280, in <module>
    align_brain = AlignBrain(
  File "C:\ProgramData\Anaconda3\envs\spbr\lib\site-packages\speechbrain\core.py", line 493, in __init__
    torch.cuda.set_device(int(self.device[-1]))
  File "C:\ProgramData\Anaconda3\envs\spbr\lib\site-packages\torch\cuda\__init__.py", line 311, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
```

The train.yaml:

```
# Training parameters
number_of_epochs: 10
batch_size: 256
lr: 0.0003
sorting: ascending # choose between ascending, descending and random
device: 'cpu'#------------the 'device' has been modifide
```

The 'device' was originally 'cuda: 0'
**The reason seems to be 'device: CUDa: 0' in 'run_opts', but I didn't type 'run_opts' and didn't find the default value for 'run_opts'.**

when i enter 'print(run_opts)':

`{'debug': False, 'debug_batches': 2, 'debug_epochs': 2, 'device': 'cuda:0', 'data_parallel_backend': False, 'distributed_launch': False, 'distributed_backend': 'nccl', 'find_unused_parameters': False}`

**Comment by Adel-Moumen** [comment]
Hello @cyd12345, 

Sorry for the delay!

I might have an idea. Could you please launch the script with the following command:
`python train.py train.yaml --device=cpu` 

I think the problem is that `run_opts` have the default parameter `device` set to `cuda:0` which overrides the value given in the yaml (but I am not sure and this is why ask you to re run with this command).

Best.

**Comment by Adel-Moumen** [comment]
Hello @cyd12345,

I'm closing this issue as it has been inactive for a significant amount of time. If this is still an ongoing concern, I would encourage you to open a new issue with the updated issue template so that we have all the necessary information to investigate further.

Let me know if you have any questions or concerns.
