### ISSUE TITLE
AttributeError: 'ModuleDict' object has no attribute 'encoder'

### ISSUE THREAD

**Issue by CaeTism** [speechbrain/speechbrain#1343]
### When I'm going to evaluate  an  ASR Transformer module trained on AISHELL, an error occurred.

I use the demo command for inference:
```
from speechbrain.pretrained import EncoderDecoderASR
asr_model = EncoderDecoderASR.from_hparams("/home/nvidia/code/speechbrain-develop/recipes/AISHELL-1/ASR/transformer/results/transformer/xxx")
asr_model.transcribe_file("/home/nvidia/code/speechbrain-develop/recipes/AISHELL-1/ASR/transformer/results/transformer/xxxx/xxx.wav")
```

Following are ERROR codes:
```
Traceback (most recent call last):
  File "/home/nvidia/code/speechbrain-develop/infer.py", line 5, in <module>
    asr_model.transcribe_file("/home/nvidia/code/speechbrain-develop/recipes/AISHELL-1/ASR/transformer/results/transformer/xxxx/xxx.wav")
  File "/home/nvidia/code/speechbrain-develop/speechbrain/pretrained/interfaces.py", line 525, in transcribe_file
    predicted_words, predicted_tokens = self.transcribe_batch(
  File "/home/nvidia/code/speechbrain-develop/speechbrain/pretrained/interfaces.py", line 589, in transcribe_batch
    encoder_out = self.encode_batch(wavs, wav_lens)
  File "/home/nvidia/code/speechbrain-develop/speechbrain/pretrained/interfaces.py", line 558, in encode_batch
    encoder_out = mds.encoder(wavs, wav_lens)
  File "/home/nvidia/anaconda2021/envs/centrods/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ModuleDict' object has no attribute 'encoder'
```
I checked in the interfaces.py:

```
self.mods = torch.nn.ModuleDict(modules)
...
...
...
encoder_out = self.mods.encoder(wavs, wav_lens)
```
and could not find function **encoder.()** in official pytorch "module.py--->torch.nn.ModuleDict()" .

How could I fix this, appreciate for your reply.

**Comment by TParcollet** [comment]
Hi, did you follow the tutorial on inference ? If you wish to use the interface, you need to do some processing on your yaml. This is necessary to ensure that exported models are stable, clean and production-ready.

**Comment by Adel-Moumen** [comment]
Hello @CaeTism,

is the issue still up?

**Comment by Adel-Moumen** [comment]
Hello, 

There has been no activity for a very long time. Therefore, I am closing this issue. 

Feel free to reopen if needed. Thanks! :)
