### ISSUE TITLE
Tensors are not on the same device

### ISSUE THREAD

**Issue by jiaweiru** [speechbrain/speechbrain#1346]
Hi,
I ran into some problems when I tried to use complex networks, but I set the device to cuda:0

Traceback (most recent call last):
  File "/home/rujiawei/Gitprojects/f2net/train.py", line 301, in <module>
    se_brain.fit(
  File "/home/rujiawei/Softwares/anaconda/envs/f1net/lib/python3.9/site-packages/speechbrain/core.py", line 1034, in fit
    loss = self.fit_batch(batch)
  File "/home/rujiawei/Softwares/anaconda/envs/f1net/lib/python3.9/site-packages/speechbrain/core.py", line 854, in fit_batch
    outputs = self.compute_forward(batch, Stage.TRAIN)
  File "/home/rujiawei/Gitprojects/f2net/train.py", line 57, in compute_forward
    predict_spec = self.modules.model(noisy_feats)
  File "/home/rujiawei/Softwares/anaconda/envs/f1net/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rujiawei/Gitprojects/f2net/custom_model.py", line 69, in forward
    x = layer(x)
  File "/home/rujiawei/Softwares/anaconda/envs/f1net/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rujiawei/Softwares/anaconda/envs/f1net/lib/python3.9/site-packages/speechbrain/nnet/complex_networks/c_RNN.py", line 143, in forward
    output, hh = self._forward_rnn(x, hx=hx)
  File "/home/rujiawei/Softwares/anaconda/envs/f1net/lib/python3.9/site-packages/speechbrain/nnet/complex_networks/c_RNN.py", line 170, in _forward_rnn
    x = rnn_lay(x, hx=None)
  File "/home/rujiawei/Softwares/anaconda/envs/f1net/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rujiawei/Softwares/anaconda/envs/f1net/lib/python3.9/site-packages/speechbrain/nnet/complex_networks/c_RNN.py", line 289, in forward
    h = self._complexlstm_cell(w, self.h_init)
  File "/home/rujiawei/Softwares/anaconda/envs/f1net/lib/python3.9/site-packages/speechbrain/nnet/complex_networks/c_RNN.py", line 325, in _complexlstm_cell
    it * torch.tanh(torch.cat([ctr, cti], dim=-1)) * drop_mask
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by TParcollet** [comment]
Hi, I see that this is one custom code ? Can you please give us more context ?

**Comment by Adel-Moumen** [comment]
Hello @jiaweiru,

Are you still facing this problem?

**Comment by Adel-Moumen** [comment]
Hello, 

There has been no activity for a very long time. Therefore, I am closing this issue. 

Feel free to reopen if needed. Thanks! :)
