### ISSUE TITLE
Usage of Speechbrain functions breaks PyTorch computation graph

### ISSUE THREAD

**Issue by KacperKubara** [speechbrain/speechbrain#1396]
Hi, 

I've been trying to obtain gradients from CRDNN loss with respect to the input data. I am using the CRDNN recipe for Librispeech with minor modifications.
``` Python
            loss = model.compute_objectives((p_seq, wav_lens), x, stage=Stage.TRAIN) # Not sure about the length param
            print(loss)
            print(torch.autograd.grad(loss, wavs, retain_graph=True))
```
However, I receive an error:
``` bash
speechbrain.core - Exception:
Traceback (most recent call last):
  File "uncertainty_baselines/pipeline_correlation_scores.py", line 169, in <module>
    pipeline_uncertainty(hparams, test=hparams["test_mode"])
  File "uncertainty_baselines/pipeline_correlation_scores.py", line 94, in pipeline_uncertainty
    _, _, confs, confs_raw = uncertainty_method.split_samples(dataloader, brain, conf_cnt=None)
  File "/home/kacper/Desktop/repos/uncertainty_baselines/uncertainty_baselines/baselines/baseline_methods.py", line 36, in split_samples
    confs, confs_raw = self.get_confidence_scores(data_loader, model)
  File "/home/kacper/Desktop/repos/uncertainty_baselines/uncertainty_baselines/baselines/baseline_methods.py", line 214, in get_confidence_scores
    print(torch.autograd.grad(loss, wav_lens, retain_graph=True))
  File "/home/kacper/miniconda3/envs/uncertain/lib/python3.8/site-packages/torch/autograd/__init__.py", line 234, in grad
    return Variable._execution_engine.run_backward(
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.
```
This means that most likely the computation graph is broken somewhere.  This issue highlights this problem: https://discuss.pytorch.org/t/example-for-one-of-the-differentiated-tensors-appears-to-not-have-been-used-in-the-graph/58396/4

There might be the case where some feature engineering step converts the data to numpy or other non-PyTorch tensor which will break computation graph. 

I know that it's like looking for a needle in a hay but are you aware feature extraction/engineering steps that might break the computation graph? I need to have gradients computed with respect to the input for my research.

Possible functions that I suspect are currently 
``` yaml
compute_features: !new:speechbrain.lobes.features.Fbank
   sample_rate: !ref <sample_rate>
   n_fft: !ref <n_fft>
   n_mels: !ref <n_mels>

augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
   sample_rate: !ref <sample_rate>
   speeds: [95, 100, 105]

normalize: !new:speechbrain.processing.features.InputNormalization
   norm_type: global
```
Forward loop for reference. I am using the CRDNN recipe for Librispeech with minor modifications.
``` Python
    def compute_forward(self, batch, stage, wav_raw=None, wav_lens_raw=None, turn_off_augment=False):
        """Forward computations from the waveform batches to the output probabilities."""
        batch = batch.to(self.device)
        if wav_raw is not None and wav_lens_raw is not None:
            wavs, wav_lens = wav_raw, wav_lens_raw
        else:
            wavs, wav_lens = batch.signal
        
        print(wavs.requires_grad)
        tokens_bos, _ = batch.tokens_bos
        wavs, wav_lens = wavs.to(self.device), wav_lens.to(self.device)

        # Add augmentation if specified
        if stage == sb.Stage.TRAIN:
            if hasattr(self.modules, "env_corrupt"):
                print("in env corrupt")
                wavs_noise = self.modules.env_corrupt(wavs, wav_lens)
                wavs = torch.cat([wavs, wavs_noise], dim=0)
                wav_lens = torch.cat([wav_lens, wav_lens])
                tokens_bos = torch.cat([tokens_bos, tokens_bos], dim=0)
            if turn_off_augment is False:
                if hasattr(self.hparams, "augmentation"):
                    print("Before augmentation")
                    print(wavs.requires_grad)
                    wavs = self.hparams.augmentation(wavs, wav_lens)
                    print(wavs.requires_grad)
                    print("After augmentation")


        # Forward pass
        print(wavs.requires_grad)
        feats = self.hparams.compute_features(wavs)
        print(wavs.requires_grad)
        feats = self.modules.normalize(feats, wav_lens)
        print(wavs.requires_grad)
        x = self.modules.enc(feats.detach())
        e_in = self.modules.emb(tokens_bos)  # y_in bos + tokens
        h, _ = self.modules.dec(e_in, x, wav_lens)

        # Output layer for seq2seq log-probabilities
        logits = self.modules.seq_lin(h)
        p_seq = self.hparams.log_softmax(logits)
        print(wavs.requires_grad)
        # Compute outputs
        if stage == sb.Stage.TRAIN:
            current_epoch = self.hparams.epoch_counter.current
            if current_epoch <= self.hparams.number_of_ctc_epochs:
                # Output layer for ctc log-probabilities
                logits = self.modules.ctc_lin(x)
                p_ctc = self.hparams.log_softmax(logits)
                print(wavs.requires_grad)
                return p_ctc, p_seq, wav_lens
            else:
                return p_seq, wav_lens, logits
        else:
            if stage == sb.Stage.VALID:
                p_tokens, scores = self.hparams.valid_search(x, wav_lens)
            else:
                p_tokens, scores = self.hparams.test_search(x, wav_lens)
            return p_seq, wav_lens, p_tokens
```

Everywhere in this code, `print(wavs.requires_grad)` is equal to True when I disable augmentation of the input. This means that probably somewhere in Speechbrain function computation graph is broken due to the Numpy conversion (perhaps)

**Comment by KacperKubara** [comment]
Hi I think I actually found the culprit:
``` Python
        x = self.modules.enc(feats.detach())
```
This detaches the tensor from the computation graph. After removing the detach() option I can now compute the gradient w.r.t input.

Do you know perhaps why the tensor is detached at this stage? Are steps until this point considered as feature engineering/extraction?
