### ISSUE TITLE
 cuDNN error: CUDNN_STATUS_EXECUTION_FAILED when training models from recipes 

### ISSUE THREAD

**Issue by Asma-droid** [speechbrain/speechbrain#1447]
Dear all,

I would like to use SpeechBrain. I have started by creating models when based on the LibriSpeech recipe. 

I am trying to create LM model. I have gor the bellow errer despite i have two GPU and 128 Go Ram

speechbrain.utils.epoch_loop - Going into epoch 1
  0%|                                                                                                                                    | 0/10172552 [00:02<?, ?it/s]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "/srv/nas_data/atrabelsi/speechbrain/recipes/LibriSpeech/LM/train.py", line 207, in <module>
    lm_brain.fit(
  File "/srv/nas_data/atrabelsi/speechbrain/speechbrain/core.py", line 1129, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/srv/nas_data/atrabelsi/speechbrain/speechbrain/core.py", line 985, in _fit_train
    loss = self.fit_batch(batch)
  File "/srv/nas_data/atrabelsi/speechbrain/recipes/LibriSpeech/LM/train.py", line 54, in fit_batch
    predictions = self.compute_forward(batch, sb.Stage.TRAIN)
  File "/srv/nas_data/atrabelsi/speechbrain/recipes/LibriSpeech/LM/train.py", line 39, in compute_forward
    logits = self.hparams.model(tokens_bos)
  File "/home/jupyter-atrabels/.conda/envs/speech_brain/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/srv/nas_data/atrabelsi/speechbrain/speechbrain/lobes/models/RNNLM.py", line 112, in forward
    x, hidden = self.rnn(x, hx)
  File "/home/jupyter-atrabels/.conda/envs/speech_brain/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/srv/nas_data/atrabelsi/speechbrain/speechbrain/nnet/RNN.py", line 271, in forward
    output, hn = self.rnn(x)
  File "/home/jupyter-atrabels/.conda/envs/speech_brain/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jupyter-atrabels/.conda/envs/speech_brain/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 661, in forward
    result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

Best regards

**Comment by TParcollet** [comment]
Hi, this typically is due to OOM. Reduce the batch size and increase the gradient_accumulation to compensate.

**Comment by Adel-Moumen** [comment]
Hello,

Any news on this issue, please? Thanks!

**Comment by Adel-Moumen** [comment]
Hello,

it seems that there has been no activity for a long time, so I am closing this issue.

Feel free to reopen it if you still encounter the problem. Thank you. 🙂
