### ISSUE TITLE
Loss is NaN for LibriSpeech receipe 

### ISSUE THREAD

**Issue by Asma-droid** [speechbrain/speechbrain#1462]
Hello,

I am trying to test how can train model with speech brain. I have chosen the Librispeech recipe.  when training LM, i have got this following error.

2022-06-21 20:40:24,602 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/srv/nas_data/atrabelsi/speechbrain/recipes/LibriSpeech/LM/train.py", line 208, in <module>
    lm_brain.fit(
  File "/srv/nas_data/atrabelsi/speechbrain/speechbrain/core.py", line 1129, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/srv/nas_data/atrabelsi/speechbrain/speechbrain/core.py", line 985, in _fit_train
    loss = self.fit_batch(batch)
  File "/srv/nas_data/atrabelsi/speechbrain/recipes/LibriSpeech/LM/train.py", line 62, in fit_batch
    self.check_gradients(loss)
  File "/srv/nas_data/atrabelsi/speechbrain/speechbrain/core.py", line 915, in check_gradients
    raise ValueError(
ValueError: Loss is not finite and patience is exhausted. To debug, wrap `fit()` with autograd's `detect_anomaly()`, e.g.

with torch.autograd.detect_anomaly():
	brain.fit(...)

Best regards
[log.txt](https://github.com/speechbrain/speechbrain/files/8955460/log.txt)

**Comment by TParcollet** [comment]
Hi, are you training with the recommended yaml file ? Did you change anything ? How many GPUs are you using?

**Comment by Asma-droid** [comment]
@TParcollet , i have not changed the recommended yaml file. i use one GPU.

**Comment by TParcollet** [comment]
Ok, if you only use one GPU you will have to increase gradient_accumulation to compensate :-)

**Comment by Adel-Moumen** [comment]
Hello, 

Any news on this issue, please? Thanks!

**Comment by thibault-roux** [comment]
I met this issue for multiples reasons : the env corruption was not compatible with my data apparently ; and of course, some of my data were problematics (empty files, etc). Unfortunately, I still meet this issue depending of the batch_size : when training with a batch_size of 4, I could train my model for 1 epoch ; but with a batch_size of 7, my model crash at 81% of the first epoch with this error.

**Comment by Adel-Moumen** [comment]
Hello @thibault-roux,

thanks for reaching out. Are you still facing this problem? Thank you. 🙂

**Comment by thibault-roux** [comment]
Somehow, filtering again worked ! This is the magic of Speechbrain 😃

**Comment by Adel-Moumen** [comment]
Good to know! 

I close this issue as it seems that there is no more activity. If you need, please create a new issue following the issue template. Thanks. :-)

**Comment by Lokesh97Bansal** [comment]
Hi I am having the same issue, I am training a model performing multitasking ASR and emotion recognition, in first epoch it was showing this error, then somehow by changing the optimizer to AdamW first two epochs got completed, but in the third epoch again it is showing this error. Can someone help in this regard?
Thanks.

**Comment by AsuMagic** [comment]
> Hi I am having the same issue, I am training a model performing multitasking ASR and emotion recognition, in first epoch it was showing this error, then somehow by changing the optimizer to AdamW first two epochs got completed, but in the third epoch again it is showing this error. Can someone help in this regard? Thanks.

Do you use the LibriSpeech dataset or did you plug your own?

If you use CTC for that ASR task on a custom dataset make sure the output neuron count matches the symbol count.

**Comment by Lokesh97Bansal** [comment]
Hi I am using IEMOCAP data instead of Librispeech. I have created the json files consisting of Uppercased transcripts with removal of all the characters like (?,! etc.). Before removal of the characters and lowercased transcripts I was having nan in the loss. But now I am having error: ZeroDivisionError: float division by zero
![image](https://user-images.githubusercontent.com/52260398/212769811-5f3ce77f-3610-4b6d-be9e-b215cff59962.png)
<img width="685" alt="Capture" src="https://user-images.githubusercontent.com/52260398/212769871-82065e97-da7a-469c-825c-f5c4a4805a38.PNG">

**Comment by Lokesh97Bansal** [comment]
Hi I am using IEMOCAP data instead of Librispeech. I have created the json
files consisting of Uppercased transcripts with removal of all the
characters like (?,! etc.). Before removal of the characters and lowercased
transcripts I was having nan in the loss. But now I am having error:
ZeroDivisionError: float division by zero
[image: image.png]

Can we connect on google meet if possible?

Thanks & Regards
Lokesh Bansal
MTech, Robotics
Indian Institute of Science, Bangalore, India
+91 9079425698

**Comment by AsuMagic** [comment]
I think this could be caused by an empty utterance in the dataset (maybe or maybe not due to the filtering you have done).

Also, even if you don't encounter the NaN loss anymore I would still recommend double-checking if the vocabulary size and the neuron count match if you haven't already, just in case.

**Comment by cs6910-pg-2024** [comment]
@asumagic Hi, I am trying to run the hyperconformer for my custom dataset I didn't change the script and I also checked if there were any empty audio files but there were none. In the first epoch after 30% progress, my code is stopped and giving this error patience exhausted. Kindly help.

**Comment by Vaibhavsun** [comment]
from speechbrain.processing.features import InputNormalization
class Model(torch.nn.Module):
    def __init__(self,n_class):
        super(Model,self).__init__()
        self.feature_extractor=cls.mods.compute_features
        self.norm1=InputNormalization()
        self.mod=cls.mods.embedding_model
        # self.mod.register_forward_hook(self.hook_fun)
        self.classifier=AAMsoftmax(n_class,0.2,30)
        self.batch_norm=torch.nn.BatchNorm1d(num_features=192)
        self.norm2=InputNormalization()
    def forward(self,x,label=None):
        fet=self.feature_extractor(x)
        fet=self.norm1(fet,torch.ones(len(fet)))
        pred=self.mod(fet)S
        pred=pred.view(32,192)
        pred=self.batch_norm(pred)
        if label!=None:
            loss,prec1=self.classifier(pred.view(32,192),label)
            return loss,prec1
        return loss,prec1
    # def hook_fun(self,module,input,output):
    #     self.out=output
    #     return output
        


i was using speech brain EncoderClassifier to basically train the model from scratch and i have just created a custom class but i am getting nan values after few epochs if anyone can help?
