### ISSUE TITLE
Can't run speechbrain/sepformer-whamr16k on Windows

### ISSUE THREAD

**Issue by a-v-ebrahimi** [speechbrain/speechbrain#1539]
I installed pytorch, speechbrain and other packages, now when I run speech enhancement sample, I receive this error :

```
Traceback (most recent call last):
  File "D:\gits\audio\SpeechBrain\main.py", line 1, in <module>
    from speechbrain.pretrained import SepformerSeparation as separator
  File "C:\Users\ABD\anaconda3\envs\SpeechBrain\lib\site-packages\speechbrain\__init__.py", line 4, in <module>
    from .core import Stage, Brain, create_experiment_directory, parse_arguments
  File "C:\Users\ABD\anaconda3\envs\SpeechBrain\lib\site-packages\speechbrain\core.py", line 35, in <module>
    from speechbrain.utils.distributed import run_on_main
  File "C:\Users\ABD\anaconda3\envs\SpeechBrain\lib\site-packages\speechbrain\utils\__init__.py", line 11, in <module>
    from . import *  # noqa
  File "C:\Users\ABD\anaconda3\envs\SpeechBrain\lib\site-packages\speechbrain\utils\Accuracy.py", line 7, in <module>
    from speechbrain.dataio.dataio import length_to_mask
  File "C:\Users\ABD\anaconda3\envs\SpeechBrain\lib\site-packages\speechbrain\dataio\__init__.py", line 11, in <module>
    from . import *  # noqa
  File "C:\Users\ABD\anaconda3\envs\SpeechBrain\lib\site-packages\speechbrain\dataio\dataio.py", line 20, in <module>
    import torchaudio
  File "C:\Users\ABD\anaconda3\envs\SpeechBrain\lib\site-packages\torchaudio\__init__.py", line 2, in <module>
    from torchaudio import (
  File "C:\Users\ABD\anaconda3\envs\SpeechBrain\lib\site-packages\torchaudio\pipelines\__init__.py", line 1, in <module>
    from ._wav2vec2 import (
ImportError: cannot import name 'Wav2Vec2Bundle' from 'torchaudio.pipelines._wav2vec2' (C:\Users\ABD\anaconda3\envs\SpeechBrain\lib\site-packages\torchaudio\pipelines\_wav2vec2\__init__.py)

Process finished with exit code 1

```

**Comment by anautsch** [comment]
Hi @a-v-ebrahimi please provide a minimal example of what went wrong, so we are on the same page.

There's work on wav2vec2 at the moment. Which versions are you using of pytorch, torchaudio & SpeechBrain?
(Perhaps worth a try to update all packages to their latest versions; some pipelines changed recently.)

@TParcollet @ycemsubakan  the above error lines suggest issues with wav2vec2?
```
speechbrain\dataio\dataio.py", line 20, in <module>
    import torchaudio

torchaudio\pipelines\__init__.py", line 1, in <module>
    from ._wav2vec2 import (

ImportError: cannot import name 'Wav2Vec2Bundle' from 'torchaudio.pipelines._wav2vec2' 
```

**Comment by Adel-Moumen** [comment]
Hello @a-v-ebrahimi,

Is the issue still up? Thanks.

**Comment by fmbao** [comment]
same question

**Comment by anautsch** [comment]
Hi @fmbao please share a minimal code snippet (of what does not work), so we can try to reproduce the error on our side.

**Comment by Adel-Moumen** [comment]
Hello, 

it seems that there has been no activity for a long time, so I am closing this issue. 

Please @fmbao, if you encounter the same problem, open a new issue with the necessary information. Thank you. 🙂
