### ISSUE TITLE
Finetune Text-to-Speech: Tacotron2 and HifiGAN

### ISSUE THREAD

**Issue by olahsymbo100** [speechbrain/speechbrain#1542]
Hi,

I have been able to set up speechbrain on my linux server. And I am currently training the Text-to-Speech Tacotron2 and HifiGAN. However, I would really like to use transfer learning instead of training from scratch. I’ve searched the entire documentation but cant find how to finetune either Tacotron2 or HifiGAN to smaller dataset. Please guide me on this/point me to existing implementation for this. I would really appreciate your help.

Thank you.
Kind regards.

**Comment by BenoitWang** [comment]
Hi @olahsymbo100 thank you for your interest. We don't have a TTS fine-tuning tuto. But if you want to fine-tune a TTS model, you can load the model and fine-tune it with the `pretrainer` [class](https://colab.research.google.com/drive/1LN7R3U3xneDgDRK2gC5MzGkLysCWxuC3#scrollTo=l7qb4lrtG8G-
). 

And if you use an English fine-tuning dataset, you only need to prepare train/valid json files with the same format as LJSpeech. But if you want to fine-tune the model to other languages, you'll need a new text pipeline as in `speechbrain.utils.text_to_sequence`.

**Comment by olahsymbo100** [comment]
Hi @BenoitWang Thank you very much for your response. I have tried the pretrainer class as:

```
from speechbrain.utils.parameter_transfer import Pretrainer

    # Initialization of the pre-trainer
    pretrain = Pretrainer(collect_in='model_local',
                          loadables={'model': Tacotron2Brain()},
                          paths={'model': 'speechbrain/tts-tacotron2-ljspeech/model.ckpt'})

    # We download the pretrained model from HuggingFace in this case
    pretrain.collect_files()
    pretrain.load_collected(device='cpu')
```
`Tacotron2Brain()` loads default TTS parameters from `sb.Brain` class.`


However, it keeps giving this error:

```
ljspeech_prepare - ./results/tacotron2/1234/save/train.json successfully created!
ljspeech_prepare - ./results/tacotron2/1234/save/valid.json successfully created!
speechbrain.core - 28.2M trainable parameters in Tacotron2Brain
speechbrain.pretrained.fetching - Fetch model.ckpt: Using existing file/symlink in model_local/model.ckpt.
speechbrain.utils.parameter_transfer - Loading pretrained files for: model
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 404, in <module>
    pretrain.load_collected(device='cpu')
  File "/home/olasimbo/phyna/speechbrain/speechbrain/utils/parameter_transfer.py", line 249, in load_collected
    self._call_load_hooks(paramfiles, device)
  File "/home/olasimbo/phyna/speechbrain/speechbrain/utils/parameter_transfer.py", line 273, in _call_load_hooks
    default_hook(obj, loadpath, end_of_epoch, device)
  File "/home/olasimbo/phyna/speechbrain/speechbrain/core.py", line 1355, in _recover
    save_dict = yaml.safe_load(f)
  File "/home/olasimbo/phyna/speechbrain/venv/lib/python3.8/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/home/olasimbo/phyna/speechbrain/venv/lib/python3.8/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
  File "/home/olasimbo/phyna/speechbrain/venv/lib/python3.8/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/home/olasimbo/phyna/speechbrain/venv/lib/python3.8/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/home/olasimbo/phyna/speechbrain/venv/lib/python3.8/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/home/olasimbo/phyna/speechbrain/venv/lib/python3.8/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte
```

**Comment by olahsymbo100** [comment]
Hi @BenoitWang Thank you very much for your response. I have been able to implement the pretrainer class using the link you shared and its able to load the pretrained model. However, I'm a bit confuse on how to proceed with finetuning (fit) the pretrained model to my dataset. I've checked the PreTrainer class it doesnt include any `fit` function and neither does it have a routine to pass the loaded model to an existing training class. 

In other words, PreTrainer class just fetches and loads the model, there is no way to continue training. 
Could you please clarify.

Thank you

**Comment by BenoitWang** [comment]
Hi @olahsymbo100, the `pretrainer` class does not have a fit method. Once the `pretrainer` loads the modules, you only need to launch the same training pipeline as in `train.py` with your own data. You can read the entire tuto in the same link.

**Comment by olahsymbo100** [comment]
Hi @BenoitWang thank you for the clarification. I'm currently implementing it as:

```
    datasets = dataio_prepare(hparams)

    # Brain class initialization
    tacotron2_brain = Tacotron2Brain(
        modules=hparams["modules"],
        opt_class=hparams["opt_class"],
        hparams=hparams,
        run_opts=run_opts,
        checkpointer=hparams["checkpointer"],
    )

    tac = Tacotron2.Tacotron2()

    # Initialization of the pre-trainer
    pretrain = Pretrainer(collect_in='model_local',
                          loadables={'model': Tacotron2.Tacotron2()},
                          paths={'model': 'speechbrain/tts-tacotron2-ljspeech/model.ckpt'})

    # We download the pretrained model from HuggingFace in this case
    pretrain.collect_files()
    pretrain.load_collected(device='cpu')

    tacotron2_brain.fit(
        tacotron2_brain.hparams.epoch_counter,
        train_set=datasets["train"],
        valid_set=datasets["valid"],
        train_loader_kwargs=hparams["train_dataloader_opts"],
        valid_loader_kwargs=hparams["valid_dataloader_opts"],
    )

```

I'm just wondering if ` checkpointer=hparams["checkpointer"]` will not make it override the loaded pretrained model.
