### ISSUE TITLE
RuntimeError when I use cuda (vad-crdnn-libriparty)

### ISSUE THREAD

**Issue by matt1209** [speechbrain/speechbrain#1545]
My test script:

`import torchaudio
from speechbrain.pretrained import VAD

test_file = 'a.wav'
vad_final = 'bond_vad.wav'

######

VAD = VAD.from_hparams(run_opts={"device":"cuda"}, source="speechbrain/vad-crdnn-libriparty", savedir="pretrained_models/vad-crdnn-libriparty")

boundaries = VAD.get_speech_segments(test_file)

VAD.save_boundaries(boundaries, save_path='VAD_file.txt')

upsampled_boundaries = VAD.upsample_boundaries(boundaries, test_file)
torchaudio.save(vad_final, upsampled_boundaries.cpu(), 16000)`

When I run it, the following error goes:
`Traceback (most recent call last):
  File "test.py", line 12, in <module>
    boundaries = VAD.get_speech_segments(test_file)
  File "/home/yehor/Tools/anaconda3/envs/my/lib/python3.8/site-packages/speechbrain/pretrained/interfaces.py", line 1861, in get_speech_segments
    prob_chunks = self.get_speech_prob_file(
  File "/home/yehor/Tools/anaconda3/envs/my/lib/python3.8/site-packages/speechbrain/pretrained/interfaces.py", line 1092, in get_speech_prob_file
    small_chunks_prob = self.get_speech_prob_chunk(small_chunks)
  File "/home/yehor/Tools/anaconda3/envs/my/lib/python3.8/site-packages/speechbrain/pretrained/interfaces.py", line 1203, in get_speech_prob_chunk
    outputs = self.mods.cnn(feats)
  File "/home/yehor/Tools/anaconda3/envs/my/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yehor/Tools/anaconda3/envs/my/lib/python3.8/site-packages/speechbrain/nnet/containers.py", line 144, in forward
    x = layer(x)
  File "/home/yehor/Tools/anaconda3/envs/my/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yehor/Tools/anaconda3/envs/my/lib/python3.8/site-packages/speechbrain/nnet/normalization.py", line 222, in forward
    return self.norm(x)
  File "/home/yehor/Tools/anaconda3/envs/my/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yehor/Tools/anaconda3/envs/my/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 189, in forward
    return F.layer_norm(
  File "/home/yehor/Tools/anaconda3/envs/my/lib/python3.8/site-packages/torch/nn/functional.py", line 2486, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper__native_layer_norm)`

**Comment by anautsch** [comment]
Hi @matt1209 is the error still happening on the latest version?

I deviated a bit from your snippet, also ran it on cpu, and it works - I used an `example.wav` file from SpeechBrain. 
(Perhaps the issue doesn't appear with this audio file, which would be good to know - then our tests might need improvement.)

```python
import torchaudio
from speechbrain.pretrained import VAD
test_file = 'example.wav'
VAD = VAD.from_hparams(run_opts={"device":"cpu"}, source="speechbrain/vad-crdnn-libriparty", savedir="pretrained_models/vad-crdnn-libriparty")
vad_final = 'example_vad.wav'
boundaries = VAD.get_speech_segments(test_file)
VAD.save_boundaries(boundaries, save_path='VAD_file.txt')
upsampled_boundaries = VAD.upsample_boundaries(boundaries, test_file)
torchaudio.save(vad_final, upsampled_boundaries.cpu(), 16000)
```
> segment_001  0.00  8.60 SPEECH

I had difficulties reading through the formatting of the tracelog - is it that the error already happened here?
`boundaries = VAD.get_speech_segments(test_file)`
which could be because of the file?

Are there any properties to the audio that are much different than the SpeechBrain example audios?
https://github.com/speechbrain/speechbrain/tree/develop/tests/samples
https://github.com/speechbrain/speechbrain/tree/develop/tests/samples/VAD

**Comment by Adel-Moumen** [comment]
Hello,

any news on this PR, please?

**Comment by Adel-Moumen** [comment]
Hello, 

it seems that there has been no activity for a long time, so I am closing this issue. Feel free to reopen it if the problem reappears on your side. 🙂

**Comment by Lakshmi-bashyam** [comment]
Hello,

I seem to have the same issue while getting the speech segment. This occurs only when I use cuda for VAD. 

This is my code,

```
VAD = VAD.from_hparams(
                source="speechbrain/vad-crdnn-libriparty",
                savedir='pretrained/',
                run_opts={"device":"cuda"}
            )
speech = VAD.get_speech_segments(audio_file='file.wav')
```
Traceback (most recent call last):
 File "/home/lakshmi/Documents/project/machinelearninglibrary/ml/speakerDiarization/vad.py", line 38, in get_speech_interval
speech = VAD.get_speech_segments(audio_file=audio_path, small_chunk_size=0.5, large_chunk_size=3.5)
  File "/home/lakshmi/miniconda3/envs/LSM/lib/python3.9/site-packages/speechbrain/pretrained/interfaces.py", line 1895, in get_speech_segments
    prob_chunks = self.get_speech_prob_file(
  File "/home/lakshmi/miniconda3/envs/LSM/lib/python3.9/site-packages/speechbrain/pretrained/interfaces.py", line 1119, in get_speech_prob_file
    small_chunks_prob = self.get_speech_prob_chunk(small_chunks)
  File "/home/lakshmi/miniconda3/envs/LSM/lib/python3.9/site-packages/speechbrain/pretrained/interfaces.py", line 1230, in get_speech_prob_chunk
    outputs = self.mods.cnn(feats)
  File "/home/lakshmi/miniconda3/envs/LSM/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lakshmi/miniconda3/envs/LSM/lib/python3.9/site-packages/speechbrain/nnet/containers.py", line 144, in forward
    x = layer(x)
  File "/home/lakshmi/miniconda3/envs/LSM/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lakshmi/miniconda3/envs/LSM/lib/python3.9/site-packages/speechbrain/nnet/normalization.py", line 223, in forward
    return self.norm(x)
  File "/home/lakshmi/miniconda3/envs/LSM/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lakshmi/miniconda3/envs/LSM/lib/python3.9/site-packages/torch/nn/modules/normalization.py", line 189, in forward
    return F.layer_norm(
  File "/home/lakshmi/miniconda3/envs/LSM/lib/python3.9/site-packages/torch/nn/functional.py", line 2486, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper__native_layer_norm)
