### ISSUE TITLE
speechbrain foreign_class AttributeError

### ISSUE THREAD

**Issue by lindagaw** [speechbrain/speechbrain#1562]
Hello,

I'm trying to run the following code:

`from speechbrain.pretrained.interfaces import foreign_class`

` classifier = foreign_class(source="speechbrain/emotion-recognition-wav2vec2-IEMOCAP",
                pymodule_file="custom_interface.py",
                classname="CustomEncoderWav2vec2Classifier")
`

And I get the following error:
`AttributeError:
'str' object has no attribute 'keys'
`

I tried all possible ways to try to solve this issue. I even re-installed python 3.9 and all the dependencies. I tried to install speechbrain via pip and github, and the installation process did not throw any exceptions. However, I just cannot get the code to run.

I was able to get it run on another computer and I did exactly what I did here. I don't understand what happened ... can anyone give me a hint?

Thank you so much!

**Comment by Adel-Moumen** [comment]
Hello, 

Thanks for pointing out this potential issue. 

I tried to reproduce your example, and unfortunately, I was not able to reproduce the problem that you are facing. 

Could you please share more details about your current python environment (e.g pip list)? Which OS are you using? On your other computer, do you have the same speechbrain version with the same python environment? 🙂

**Comment by lindagaw** [comment]
Hello,

Thank you so much for the quick response! I'm using Windows 11. On the other computer, it is Windows 10. The speechbrain versions are the same - they are all the newest.

Here's the result of pip list:
Package                       Version
----------------------------- --------------------
absl-py                       1.2.0
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
altgraph                      0.17.2
anaconda-client               1.10.0
anaconda-navigator            2.2.0
anaconda-project              0.11.1
analytics-python              1.4.0
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astor                         0.8.1
astroid                       2.6.6
astropy                       5.1
asttokens                     2.0.5
astunparse                    1.6.3
async-timeout                 4.0.1
atomicwrites                  1.4.0
attrs                         21.4.0
audio2numpy                   0.1.2
audioread                     3.0.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backoff                       1.10.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bce-python-sdk                0.8.74
bcrypt                        3.2.0
beautifulsoup4                4.11.1
binaryornot                   0.4.4
biopython                     1.79
bitarray                      2.5.1
bkcharts                      0.2
black                         22.8.0
bleach                        4.1.0
blosum                        1.1.2
bokeh                         2.4.3
boto3                         1.24.28
botocore                      1.27.28
Bottleneck                    1.3.5
brotlipy                      0.7.0
cachetools                    4.2.2
certifi                       2022.6.15
cffi                          1.15.1
cfgv                          3.3.1
chardet                       4.0.0
charset-normalizer            2.0.4
click                         8.0.4
cloudpickle                   2.0.0
clyent                        1.2.2
colorama                      0.4.5
colorcet                      3.0.0
colorlog                      6.7.0
comtypes                      1.1.10
conda                         4.14.0
conda-build                   3.22.0
conda-content-trust           0.1.3
conda-pack                    0.6.0
conda-package-handling        1.8.1
conda-repo-cli                1.0.5
conda-token                   0.3.0
conda-verify                  3.4.2
configparser                  5.3.0
constantly                    15.1.0
cookiecutter                  1.7.3
cryptography                  37.0.1
cssselect                     1.1.0
cycler                        0.11.0
Cython                        0.29.30
cytoolz                       0.11.0
daal4py                       2021.5.0
dask                          2022.7.0
datasets                      2.4.0
datashader                    0.14.1
datashape                     0.5.4
debugpy                       1.5.1
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.4
distlib                       0.3.6
distributed                   2022.7.0
docutils                      0.18.1
easydict                      1.9
entrypoints                   0.3
et-xmlfile                    1.1.0
executing                     0.8.3
ez-setup                      0.9
fastapi                       0.81.0
fastjsonschema                2.16.2
ffmpeg                        1.4
ffmpy                         0.3.0
filelock                      3.6.0
flake8                        4.0.1
Flask                         1.1.2
Flask-Babel                   2.0.0
flatbuffers                   1.12
fonttools                     4.25.0
frozenlist                    1.2.0
fsspec                        2022.7.1
func-timeout                  4.3.5
future                        0.18.2
gast                          0.4.0
gensim                        4.1.2
glob2                         0.7
google-api-core               1.32.0
google-auth                   2.6.0
google-auth-oauthlib          0.4.6
google-cloud-core             2.2.2
google-cloud-dialogflow-cx    1.13.1
google-cloud-speech           2.15.1
google-cloud-storage          1.43.0
google-crc32c                 1.1.2
google-pasta                  0.2.0
google-resumable-media        1.3.1
googleapis-common-protos      1.56.4
gradio                        3.2
graphviz                      0.20.1
greenlet                      1.1.1
grpcio                        1.47.0
grpcio-status                 1.47.0
h11                           0.12.0
h5py                          3.7.0
HeapDict                      1.0.1
holoviews                     1.15.0
httpcore                      0.15.0
httpx                         0.23.0
huggingface-hub               0.9.1
hvplot                        0.8.0
hyperlink                     21.0.0
HyperPyYAML                   1.0.1
identify                      2.5.3
idna                          3.3
imagecodecs                   2021.8.26
imageio                       2.19.3
imagesize                     1.4.1
importlib-metadata            4.11.3
incremental                   21.3.0
inflection                    0.5.1
iniconfig                     1.1.1
intake                        0.6.5
intervaltree                  3.1.0
ipykernel                     6.15.2
ipython                       8.4.0
ipython-genutils              0.2.0
ipywidgets                    7.6.5
isort                         5.9.3
itemadapter                   0.3.0
itemloaders                   1.0.4
itsdangerous                  2.0.1
jarowinkler                   1.2.1
jdcal                         1.4.1
jedi                          0.18.1
jellyfish                     0.9.0
jieba                         0.42.1
Jinja2                        2.11.3
jinja2-time                   0.2.0
jiwer                         2.4.0
jmespath                      0.10.0
joblib                        1.1.0
json5                         0.9.6
jsonschema                    4.4.0
jupyter                       1.0.0
jupyter_client                7.3.5
jupyter-console               6.4.0
jupyter-core                  4.10.0
jupyter-server                1.18.1
jupyterlab                    3.4.4
jupyterlab-pygments           0.1.2
jupyterlab-server             2.10.3
jupyterlab-widgets            1.0.0
keras                         2.9.0
Keras-Preprocessing           1.1.2
keyring                       23.4.0
kiwisolver                    1.4.2
lazy-object-proxy             1.6.0
Levenshtein                   0.20.2
libarchive-c                  2.9
libclang                      14.0.6
librosa                       0.9.2
linkify-it-py                 1.0.3
llvmlite                      0.38.0
locket                        1.0.0
lxml                          4.9.1
lz4                           3.1.3
Markdown                      3.3.4
markdown-it-py                2.1.0
MarkupSafe                    2.0.1
matplotlib                    3.5.2
matplotlib-inline             0.1.6
mccabe                        0.6.1
mdit-py-plugins               0.3.0
mdurl                         0.1.2
menuinst                      1.4.19
mistune                       0.8.4
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
mock                          4.0.3
monotonic                     1.6
more-itertools                8.14.0
mpmath                        1.2.1
msgpack                       1.0.3
multidict                     5.2.0
multipledispatch              0.6.0
multiprocess                  0.70.12.2
munkres                       1.1.4
mypy-extensions               0.4.3
navigator-updater             0.2.1
nbclassic                     0.3.5
nbclient                      0.5.13
nbconvert                     6.4.4
nbformat                      5.3.0
nest-asyncio                  1.5.5
networkx                      2.8.4
nltk                          3.7
nodeenv                       1.7.0
nose                          1.3.7
notebook                      6.4.12
numba                         0.55.1
numexpr                       2.8.3
numpy                         1.22.4
numpydoc                      1.4.0
oauthlib                      3.2.0
olefile                       0.46
opencv-python                 4.6.0.66
openpyxl                      3.0.10
opt-einsum                    3.3.0
orjson                        3.8.0
packaging                     21.3
paddle-bfloat                 0.1.7
paddle2onnx                   1.0.0
paddlefsl                     1.1.0
paddlehub                     2.3.0
paddlenlp                     2.3.7
paddlepaddle                  2.3.2
pandas                        1.4.3
pandocfilters                 1.5.0
panel                         0.13.1
param                         1.12.0
paramiko                      2.8.1
parsel                        1.6.0
parso                         0.8.3
partd                         1.2.0
pathlib                       1.0.1
pathspec                      0.10.1
patsy                         0.5.2
pefile                        2022.5.30
pep8                          1.7.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.2.0
pip                           22.2.2
pkginfo                       1.8.2
platformdirs                  2.5.2
plotly                        5.9.0
pluggy                        1.0.0
pokemons                      1.0.3
pooch                         1.6.0
poyo                          0.5.0
pre-commit                    2.20.0
pretty-errors                 1.2.25
prometheus-client             0.14.1
prompt-toolkit                3.0.20
Protego                       0.1.16
proto-plus                    1.22.1
protobuf                      3.20.1
psutil                        5.9.0
ptyprocess                    0.7.0
pure-eval                     0.2.2
py                            1.11.0
pyarrow                       9.0.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
PyAudio                       0.2.12
pycodestyle                   2.8.0
pycosat                       0.6.3
pycparser                     2.21
pycryptodome                  3.15.0
pyct                          0.4.8
pycurl                        7.45.1
pydantic                      1.10.1
PyDispatcher                  2.0.5
pydocstyle                    6.1.1
pydot                         1.4.2
pydub                         0.25.1
pyerfa                        2.0.0
pyflakes                      2.4.0
Pygments                      2.11.2
PyHamcrest                    2.0.2
pyinstaller                   5.3
pyinstaller-hooks-contrib     2022.10
PyJWT                         2.4.0
pylint                        2.9.6
pyls-spyder                   0.4.0
PyNaCl                        1.5.0
pyodbc                        4.0.34
pyOpenSSL                     22.0.0
pyparsing                     3.0.9
PyQt5                         5.15.7
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.11.0
PyQtWebEngine                 5.15.6
PyQtWebEngine-Qt5             5.15.2
pyreadline                    2.1
pyrsistent                    0.18.0
PySocks                       1.7.1
pytest                        5.4.1
python-dateutil               2.8.2
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.5.0
python-multipart              0.0.5
python-slugify                5.0.2
python-snappy                 0.6.0
pytz                          2022.1
pyviz-comms                   2.0.2
PyWavelets                    1.3.0
pywin32                       302
pywin32-ctypes                0.2.0
pywinpty                      2.0.2
PyYAML                        6.0
pyzmq                         23.2.1
QDarkStyle                    3.0.2
qstylizer                     0.1.10
QtAwesome                     1.0.3
qtconsole                     5.3.2
QtPy                          2.2.0
queuelib                      1.5.0
rapidfuzz                     2.6.0
rarfile                       4.0
regex                         2022.7.9
requests                      2.28.1
requests-file                 1.5.1
requests-oauthlib             1.3.1
resampy                       0.4.0
responses                     0.18.0
rfc3986                       1.5.0
rope                          0.22.0
rsa                           4.7.2
Rtree                         0.9.7
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.6
ruamel-yaml-conda             0.15.100
s3transfer                    0.6.0
sacremoses                    0.0.43
scikit-image                  0.19.2
scikit-learn                  1.1.2
scikit-learn-intelex          2021.20220215.102710
scipy                         1.7.3
Scrapy                        2.6.2
seaborn                       0.11.2
Send2Trash                    1.8.0
sentencepiece                 0.1.97
seqeval                       1.2.2
service-identity              18.1.0
setuptools                    65.3.0
sip                           4.19.13
six                           1.16.0
smart-open                    5.2.1
sniffio                       1.2.0
snowballstemmer               2.2.0
sortedcollections             2.1.0
sortedcontainers              2.4.0
SoundFile                     0.10.3.post1
soupsieve                     2.3.1
sox                           1.4.1
speechbrain                   0.5.13
SpeechRecognition             3.8.1
Sphinx                        5.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.3.3
spyder-kernels                2.3.3
SQLAlchemy                    1.4.39
srt                           3.5.2
stack-data                    0.2.0
starlette                     0.19.1
statsmodels                   0.13.2
sympy                         1.10.1
tables                        3.6.1
tabulate                      0.8.10
TBB                           0.2
tblib                         1.7.0
tenacity                      8.0.1
tensorboard                   2.9.1
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorflow-cpu                2.9.1
tensorflow-estimator          2.9.0
tensorflow-io-gcs-filesystem  0.26.0
termcolor                     1.1.0
terminado                     0.13.1
testpath                      0.6.0
text-unidecode                1.3
textdistance                  4.2.1
threadpoolctl                 2.2.0
three-merge                   0.1.1
tifffile                      2021.7.2
timm                          0.6.7
tinycss                       0.4
tldextract                    3.2.0
tokenizers                    0.12.1
toml                          0.10.2
tomli                         2.0.1
toolz                         0.11.2
torch                         1.12.1
torchaudio                    0.12.1
torchvision                   0.13.1
tornado                       6.2
tqdm                          4.64.0
traitlets                     5.1.1
transformers                  4.21.2
Twisted                       22.2.0
twisted-iocpsupport           1.0.2
typed-ast                     1.4.3
typing_extensions             4.3.0
uc-micro-py                   1.0.1
ujson                         5.4.0
Unidecode                     1.2.0
urllib3                       1.26.11
uvicorn                       0.18.3
virtualenv                    20.16.4
visualdl                      2.4.0
vosk                          0.3.42
w3lib                         1.21.0
watchdog                      2.1.6
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              0.58.0
websockets                    10.3
Werkzeug                      2.0.3
whatthepatch                  1.0.2
wheel                         0.37.1
widgetsnbextension            3.5.2
win-inet-pton                 1.1.0
win-unicode-console           0.5
wincertstore                  0.2
wrapt                         1.12.1
xarray                        0.20.1
xlrd                          2.0.1
XlsxWriter                    3.0.3
xlwings                       0.24.9
xxhash                        3.0.0
yamllint                      1.23.0
yapf                          0.31.0
yarl                          1.8.1
zict                          2.1.0
zipp                          3.8.0
zope.interface                5.4.0

Thank you so much! I really need this model to run for a project that I'm working on...

**Comment by Adel-Moumen** [comment]
Are you using WSL on windows?

**Comment by Adel-Moumen** [comment]
I finished the installation on windows 10, and everything is working as expected (i.e, no python errors). 

I can't conclude that the problem is windows 11 because I don't have any computer running this OS to try out. I can suggest you two things: 
1. Try to create a new conda env (don't use the previous one) and follow the speechbrain installation (I guess you only tried to remove and re-install speechbrain in the same env?),
2. Use WSL on windows. It might tackle the problem. 

Let me know if it's working or not! 🤗

**Comment by lindagaw** [comment]
Hi Adel-Moumen,

Thank you so much for your quick response! I tried both creating a new conda environment and using WSL on windows and it doesn't seem to work. In addition I have access to a 3rd computer that is Windows 10 and it gives me this error as well.

I reinstalled Anaconda and directly went to install speechbrain without installing any other packages. It was installed correctly but I still saw this error ... (on the Windows 11 computer)...

**Comment by Adel-Moumen** [comment]
> Hi Adel-Moumen,
> 
> Thank you so much for your quick response! I tried both creating a new conda environment and using WSL on windows and it doesn't seem to work. In addition, I have access to a 3rd computer that is Windows 10 and it gives me this error as well.
> 
> I reinstalled Anaconda and directly went to install speechbrain without installing any other packages. It was installed correctly but I still saw this error ... (on the Windows 11 computer)...

Hmmm, are you using an NVIDIA GPU? I tried successfully on windows 10 with a ryzen 7 & an RTX 3080 ti.

Could you please give the exact error stack?

**Comment by lindagaw** [comment]
Thank you so much! I'm not using an NVIDIA GPU ... Here's the error stack:

(base) E:\commercial_package>python emotion_detection.py
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Traceback (most recent call last):
  File "E:\commercial_package\emotion_detection.py", line 8, in <module>
    classifier = foreign_class(source="speechbrain/emotion-recognition-wav2vec2-IEMOCAP",
  File "C:\Users\gaoye\anaconda3\lib\site-packages\speechbrain\pretrained\interfaces.py", line 97, in foreign_class
    hparams = load_hyperpyyaml(fin, overrides)
  File "C:\Users\gaoye\AppData\Roaming\Python\Python39\site-packages\hyperpyyaml\core.py", line 189, in load_hyperpyyaml
    removal_keys = [k for k in hparams.keys() if k.startswith("__")]
AttributeError: 'str' object has no attribute 'keys'

**Comment by Adel-Moumen** [comment]
Ok. We will need to do a little bit of remote debugging.

Could you please install locally speechbrain and modify the file `interfaces.py` located in `speechbrain.pretrained` and add some `print` around line 95: 
```python
    # Load the modules
    print(f"hparams_local_path = {hparams_local_path}")
    with open(hparams_local_path) as fin:
        hparams = load_hyperpyyaml(fin, overrides)
        print(f"hparams = {hparams}")
```  

(don't forget to then run `python setup.py install; pip install -e .` after some modifications) 

It will help us to understand a little bit more about what is currently happening. :smiley:

**Comment by lindagaw** [comment]
Hi Adel-Moumen,

Here's the result after I changed interfaces.py:

(base) C:\Users\gaoye\Documents\commercial_package>python emotion_detection.py
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
hparams_local_path = pretrained_models\CustomEncoderWav2vec2Classifier-6d849d67d0260d5a3ea6b156bb50a54b\hyperparams.yaml ; type = <class 'pathlib.WindowsPath'>
Traceback (most recent call last):
  File "C:\Users\gaoye\Documents\commercial_package\emotion_detection.py", line 8, in <module>
    classifier = foreign_class(source="speechbrain/emotion-recognition-wav2vec2-IEMOCAP",
  File "C:\Users\gaoye\anaconda3\lib\site-packages\speechbrain\pretrained\interfaces.py", line 98, in foreign_class
    hparams = load_hyperpyyaml(fin, overrides)
  File "C:\Users\gaoye\AppData\Roaming\Python\Python39\site-packages\hyperpyyaml\core.py", line 189, in load_hyperpyyaml
    removal_keys = [k for k in hparams.keys() if k.startswith("__")]
AttributeError: 'str' object has no attribute 'keys'

**Comment by lindagaw** [comment]
Hello Adel-Moumen,

I got the module running by deleting the wav2vec2_checkpoints and pretrained_models folders.

Thank you for your help and I'm so sorry for all the trouble!

Best,
lindagaw

**Comment by Adel-Moumen** [comment]
Hello @lindagaw,

It's good news that you successfully solved the issue! 

No worries :)
