### ISSUE TITLE
Multi GPU training cause padding issue on Libri speech

### ISSUE THREAD

**Issue by berniewang8177** [speechbrain/speechbrain#1580]
Hi, this is what I'm doing with speechbrain

/speechbrain/recipes/LibriSpeech/ASR/transformer$ CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python train.py ./hparams/transformer.yaml --data_parallel_backend

and this is what I got
speechbrain.utils.parameter_transfer - Loading pretrained files for: lm, tokenizer
speechbrain.core - Info: max_grad_norm arg from hparam file is used
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - Info: grad_accumulation_factor arg from hparam file is used
speechbrain.core - 71.5M trainable parameters in ASR
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
speechbrain.utils.epoch_loop - Going into epoch 1
  0%|                                                                                                   | 0/2198 [00:22<?, ?it/s]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 486, in <module>
    asr_brain.fit(
  File "/home/ubuntu/speechbrain/speechbrain/core.py", line 1154, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/ubuntu/speechbrain/speechbrain/core.py", line 1011, in _fit_train
    loss = self.fit_batch(batch)
  File "train.py", line 174, in fit_batch
    outputs = self.compute_forward(batch, sb.Stage.TRAIN)
  File "train.py", line 77, in compute_forward
    enc_out, pred = self.modules.Transformer(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
AssertionError: Caught AssertionError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/speechbrain/speechbrain/lobes/models/transformer/TransformerASR.py", line 177, in forward
    encoder_out, _ = self.encoder(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/speechbrain/speechbrain/lobes/models/transformer/Transformer.py", line 477, in forward
    output, attention = enc_layer(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/speechbrain/speechbrain/lobes/models/transformer/Transformer.py", line 349, in forward
    output, self_attn = self.self_att(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/speechbrain/speechbrain/nnet/attention.py", line 762, in forward
    output = self.att(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 1153, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 5155, in multi_head_attention_forward
    assert key_padding_mask.shape == (bsz, src_len), \
AssertionError: expecting key_padding_mask shape of (16, 437), but got torch.Size([16, 401])

**Comment by Adel-Moumen** [comment]
Hello,

Could you try DDP instead (see:https://speechbrain.readthedocs.io/en/latest/multigpu.html) please? 

Also, could you share your YAML file, please? 

Many thanks!

**Comment by berniewang8177** [comment]
Hi,
Thank you for your suggestion. The command below works for me now!

python -m torch.distributed.launch --nproc_per_node=8 --nnodes=1 --node_rank=0  train.py ./hparams/transformer.yaml --distributed_launch --distributed_backend='nccl'

**Comment by Adel-Moumen** [comment]
Nice :) 

I will close this issue as it seems that now everything is working. Feel free to reopen it if needed. 🙂
