### ISSUE TITLE
Add new speakers and resume training from checkpoint in speaker_id 

### ISSUE THREAD

**Issue by eviltypha** [speechbrain/speechbrain#1583]
Hi,

I've used your speaker_id module to train a model on a custom dataset. Initially the `n_classes` parameter has been set to 4 in `train.yaml`. Now I would like to increase this parameter and add new speakers and resume training from the saved checkpoint. I've tried doing this but encountered the following error:
```
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
torchvision is not available - cannot save figures
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
./data\rirs_noises.zip exists. Skipping download
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: ./results/custom_augment
mini_librispeech_prepare - Creating train.json, valid.json, and test.json
mini_librispeech_prepare - train.json successfully created!
mini_librispeech_prepare - valid.json successfully created!
mini_librispeech_prepare - test.json successfully created!
speechbrain.dataio.encoder - Load called, but CategoricalEncoder is not empty. Loaded data will overwrite everything. This is normal if there is e.g. an unk label defined at init.
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - 4.5M trainable parameters in SpkIdBrain
speechbrain.utils.checkpoints - Loading a checkpoint from results\custom_augment\save\CKPT+2022-09-26+05-27-32+00
speechbrain.core - Exception:
Traceback (most recent call last):
  File "E:\SpeechBrain\speechbrain\templates\speaker_id\train.py", line 328, in <module>
    spk_id_brain.fit(
  File "E:\SpeechBrain\long-speech\lib\site-packages\speechbrain\core.py", line 1143, in fit
    self.on_fit_start()
  File "E:\SpeechBrain\long-speech\lib\site-packages\speechbrain\core.py", line 797, in on_fit_start
    self.checkpointer.recover_if_possible(
  File "E:\SpeechBrain\long-speech\lib\site-packages\speechbrain\utils\checkpoints.py", line 840, in recover_if_possible
    self.load_checkpoint(chosen_ckpt, device)
  File "E:\SpeechBrain\long-speech\lib\site-packages\speechbrain\utils\checkpoints.py", line 853, in load_checkpoint
    self._call_load_hooks(checkpoint, device)
  File "E:\SpeechBrain\long-speech\lib\site-packages\speechbrain\utils\checkpoints.py", line 988, in _call_load_hooks
    default_hook(obj, loadpath, end_of_epoch, device)
  File "E:\SpeechBrain\long-speech\lib\site-packages\speechbrain\utils\checkpoints.py", line 93, in torch_recovery
    obj.load_state_dict(torch.load(path, map_location=device), strict=True)
  File "E:\SpeechBrain\long-speech\lib\site-packages\torch\nn\modules\module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Classifier:
        size mismatch for out.w.weight: copying a param with shape torch.Size([4, 512]) from checkpoint, the shape in current model is torch.Size([7, 512]).
        size mismatch for out.w.bias: copying a param with shape torch.Size([4]) from checkpoint, the shape in current model is torch.Size([7]).
```

I've tried to increase the `n_classes` parameter to 7 and made the additions in `label_encoder.txt` manually. I understand that this addition of new speakers in causing this issue. Is there any solution or workaround for this, to continue building on the existing model by taking advantage of the checkpointing feature?

**Comment by anautsch** [comment]
Hi @eviltypha the mismatching dimensions correspond to the `n_classes` as you well mentioned. The hparams are instantiated at the loading of the YAML file. You could either try to manipulate the loading function (will take time), or load the old model with the old yaml, exchange the layers that relate to `n_classes` (ideally the final layer only), and save it to a new path - that one should be loadable with the new yaml then. (Haven't studied the recipe/yaml); just a gut feeling.

Where does `n_classes` play a role in the recipe?
Could the model be well adjusted to the 4 speakers setting - does it make sense to continue training vs retraining from scratch?

**Comment by anautsch** [comment]
Hi @eviltypha yes, you can use `torch.load` - SpeechBrain provides wrappers through the yaml files. 

It could be simple: use the old yaml file, and then, after loading, manipulate the layers outlined  by `n_classes`. 
Yet, I'm araid that the mindset behind most deep learning technology is: the model is exhaustively defining/outlining the world it models. In that regard, any change in the number of speakers for diarization might imply a different world, hence a different model is required. 

If you have results on simply changing the last layer/s (e.g. while having the other, unchanged, layers frozen during retraining/finetuning), please let us know. In the best case, this is just loading an old model, manipulating it, storing it as a new checkpoint (which can be loaded witth a yaml file that has a different `n_classes`), and tackling an increase in `n_classes` as a fine-tuning task. Yet, one could also expect that the results would not be as satisfying as a complete retraining.

Btw, speaker recognition systems rely on embeddings - the data just before the final layers. If you are willing to go through PLDA modeling/other comparison approaches, you might be able to use the network as a feature extractor and to continue then with a more statistical approach (which on the other hand means needing to curate training, development, and testing datasets as well).

**Comment by eviltypha** [comment]
Hi @anautsch, I've been able to add new speakers and resume training from the checkpoint. I had to edit the `classifier.ckpt`, `optimizer.ckpt` and the `train.yaml` files to make this happen.

**Comment by anautsch** [comment]
Hi @eviltypha good to hear you found a solution!

Please share, if you like, how you edited the three files.

Out of curiosity, did the training continue at a learning rate that was within reasonable limits for you?
(or did training continue at a worse point?)

If you know and would like to share, how much did the performance change on a testing dataset?

**Comment by anautsch** [comment]
Thank you, @eviltypha !

<i>Curious if someone picks this up and would be so kind to then reach out again.</i>

Closing this issue - please feel free to re-open :)

**Comment by eviltypha** [comment]
Thanks for your help and support

**Comment by Hamana0509** [comment]
Hi @anautsch @eviltypha 

I am also working on speaker recognition problem, I have got pretrained ECAPA-TDNN model on dataset of 4000 different ids. Now I want to continue training this model on another dataset of 2000 ids (this dataset is different from pretrained data).

I tried to load checkpoint of pretrained ECAPA-TDNN but when training I got dimension mismatch error, I found out that I mismatch dimension of classifier layers. Can you give me a way to solve my problem? Can you suggest me how to fix training code or edit yaml file (I use speechbrain recipe)?

I tried just loading the weight of the pretrained ECAPA-TDNN and creating a new classifer and connecting to ECAPA-TDNN but still getting the missmatch dimensions error.

below is the log when running command `python training_voice_embedding.py training_hparams.yaml`

```
/home/jovyan/data-center/tridao/vs-code/speechbrain/speechbrain/utils/autocast.py:188: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  wrapped_fwd = torch.cuda.amp.custom_fwd(fwd, cast_inputs=cast_inputs)
/home/jovyan/data-center/tridao/vs-code/voice_embedding/voice_embedding_training_set//noise/data.zip exists. Skipping download
/home/jovyan/data-center/tridao/vs-code/voice_embedding/voice_embedding_training_set//rir/data.zip exists. Skipping download
speechbrain.utils.quirks - Applied quirks (see `speechbrain.utils.quirks`): [allow_tf32, disable_jit_profiling]
speechbrain.utils.quirks - Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: /home/jovyan/data-center/tridao/vs-code/voice_embedding/training_voice_embedding/results/2001
Nạp embedding model đã được huấn luyện từ: /home/jovyan/data-center/tridao/vs-code/voice_embedding/training_voice_embedding/results/2001/ngoan_best_ckpt/embedding_model.ckpt
Đã nạp thành công embedding model đã huấn luyện trước từ: /home/jovyan/data-center/tridao/vs-code/voice_embedding/training_voice_embedding/results/2001/ngoan_best_ckpt/embedding_model.ckpt
Xóa 'classifier' khỏi danh sách khôi phục của checkpointer để đảm bảo nó luôn được tạo mới.
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - Gradscaler enabled: `False`
speechbrain.core - Using training precision: `--precision=fp32`
speechbrain.core - Using evaluation precision: `--eval_precision=fp32`
speechbrain.core - SpeakerBrain Model `Statistics:`
Total Number of Trainable Parameters: 21.2M
Total Number of Parameters: 21.2M
Trainable Parameters represent 100.0000% of the total size.
speechbrain.utils.checkpoints - Loading a checkpoint from /home/jovyan/data-center/tridao/vs-code/voice_embedding/training_voice_embedding/results/2001/save/CKPT+2024-09-28+11-06-05+00
speechbrain.utils.epoch_loop - Going into epoch 21
speechbrain.dataio.encoder - CategoricalEncoder.expect_len was never called: assuming category count of 2345 to be correct! Sanity check your encoder using `.expect_len`. Ensure that downstream code also uses the correct size. If you are sure this does not apply to you, use `.ignore_len`.
speechbrain.dataio.encoder - CategoricalEncoder.expect_len was never called: assuming category count of 2345 to be correct! Sanity check your encoder using `.expect_len`. Ensure that downstream code also uses the correct size. If you are sure this does not apply to you, use `.ignore_len`.
speechbrain.dataio.encoder - CategoricalEncoder.expect_len was never called: assuming category count of 2345 to be correct! Sanity check your encoder using `.expect_len`. Ensure that downstream code also uses the correct size. If you are sure this does not apply to you, use `.ignore_len`.
speechbrain.dataio.encoder - CategoricalEncoder.expect_len was never called: assuming category count of 2345 to be correct! Sanity check your encoder using `.expect_len`. Ensure that downstream code also uses the correct size. If you are sure this does not apply to you, use `.ignore_len`.
  0%|                                                                                                            | 0/47437 [00:14<?, ?it/s]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "/home/jovyan/data-center/tridao/vs-code/voice_embedding/training_voice_embedding/training_voice_embedding.py", line 274, in <module>
    speaker_brain.fit(
  File "/home/jovyan/data-center/tridao/vs-code/speechbrain/speechbrain/core.py", line 1585, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/jovyan/data-center/tridao/vs-code/speechbrain/speechbrain/core.py", line 1410, in _fit_train
    loss = self.fit_batch(batch)
  File "/home/jovyan/data-center/tridao/vs-code/speechbrain/speechbrain/core.py", line 1218, in fit_batch
    self.optimizers_step()
  File "/home/jovyan/data-center/tridao/vs-code/speechbrain/speechbrain/core.py", line 1309, in optimizers_step
    self.scaler.step(opt)
  File "/home/jovyan/envs/tridao/lib/python3.10/site-packages/torch/amp/grad_scaler.py", line 384, in step
    return optimizer.step(*args, **kwargs)
  File "/home/jovyan/envs/tridao/lib/python3.10/site-packages/torch/optim/optimizer.py", line 485, in wrapper
    out = func(*args, **kwargs)
  File "/home/jovyan/envs/tridao/lib/python3.10/site-packages/torch/optim/optimizer.py", line 79, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/jovyan/envs/tridao/lib/python3.10/site-packages/torch/optim/adam.py", line 246, in step
    adam(
  File "/home/jovyan/envs/tridao/lib/python3.10/site-packages/torch/optim/optimizer.py", line 147, in maybe_fallback
    return func(*args, **kwargs)
  File "/home/jovyan/envs/tridao/lib/python3.10/site-packages/torch/optim/adam.py", line 933, in adam
    func(
  File "/home/jovyan/envs/tridao/lib/python3.10/site-packages/torch/optim/adam.py", line 673, in _multi_tensor_adam
    torch._foreach_lerp_(device_exp_avgs, device_grads, 1 - device_beta1)
RuntimeError: The size of tensor a (4296) must match the size of tensor b (2345) at non-singleton dimension 0
```
