### ISSUE TITLE
[Bug]: o such file or directory: 'speechbrain/version.txt' while running :" pip install --editable ."

### ISSUE THREAD

**Issue by BattashB** [speechbrain/speechbrain#1601]
### Describe the bug

Hi all, trying to install the package from source, 
I ran:
`pip install -r requirements.txt`, which completed with no errors.
Then, I ran the next command:
`pip install --editable .`
But it returns:
```

  FileNotFoundError: [Errno 2] No such file or directory: 'speechbrain/version.txt'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /workspace/speechbrain/speechbrain_env/bin/python /workspace/speechbrain/speechbrain_env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp07ba0j_f Check the logs for full command output.
```
(Full log below)
Thanks for your help!

### Expected behaviour

Finish installation successfully.

### Versions

I have python 3.85
speechbrain version -  did git clone on 10/13/22
entrypoints==0.3
filelock==3.8.0
flake8==3.7.9
huggingface-hub==0.10.1
HyperPyYAML==1.0.1
identify==2.5.6
idna==3.4
joblib==1.2.0
mccabe==0.6.1
more-itertools==8.14.0
nodeenv==1.7.0
numpy==1.23.4
packaging==21.3
pathspec==0.10.1
platformdirs==2.5.2
pluggy==0.13.1
pre-commit==2.20.0
py==1.11.0
pycodestyle==2.5.0
pyflakes==2.1.1
pyparsing==3.0.9
pytest==5.4.1
PyYAML==6.0
regex==2022.9.13
requests==2.28.1
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.6
scipy==1.8.1
sentencepiece==0.1.97
toml==0.10.2
torch==1.12.1
torchaudio==0.12.1
tqdm==4.64.1
typed-ast==1.5.4
typing-extensions==4.4.0
urllib3==1.26.12
virtualenv==20.16.5
wcwidth==0.2.5
yamllint==1.23.0

### Relevant log output

```shell
Obtaining file:///workspace/speechbrain
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /workspace/speechbrain/speechbrain_env/bin/python /workspace/speechbrain/speechbrain_env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp07ba0j_f
       cwd: /workspace/speechbrain
  Complete output (17 lines):
  Traceback (most recent call last):
    File "/workspace/speechbrain/speechbrain_env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/workspace/speechbrain/speechbrain_env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/workspace/speechbrain/speechbrain_env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-cyzj6spx/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-cyzj6spx/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-cyzj6spx/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 482, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-cyzj6spx/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 16, in <module>
```
```


### Additional context

_No response_

**Comment by BattashB** [comment]
For some reason my git clone did not work properly, thats was theissue, closing
