### ISSUE TITLE
[Bug]: Multi-GPU training using Data Parallel

### ISSUE THREAD

**Issue by QDPeng** [speechbrain/speechbrain#1604]
### Describe the bug

I fellow the mutigpu training docs in "docs/multigpu.md", 
## Multi-GPU training using Data Parallel
command is :
CUDA_VISIBLE_DEVICES=0,1 python experiment.py params.yaml --data_parallel_backend

But the batch data is not same length,
Errors like this:
multi_head_attention_forward
    assert key_padding_mask.shape == (bsz, src_len), \
AssertionError: expecting key_padding_mask shape of (1, 30), but got torch.Size([1, 29])

use one gpu is ok, but use multigpu will be size error, How should I do?

### Expected behaviour

can use multi gpu in one server

### To Reproduce

this code is same with recipe/AISHELL-1, I just want to use multigpu to train model

### Versions

I download a zip file(speechbrain-develop.zip ) , in 9/7/2022,

### Relevant log output

```shell
Original Traceback (most recent call last):
  File "~/miniconda3/envs/wenet12/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "~/miniconda3/envs/wenet12/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "~/miniconda3/envs/wenet12/lib/python3.8/site-packages/speechbrain/lobes/models/transformer/TransformerASR.py", line 177, in forward
    encoder_out, _ = self.encoder(
  File "~/miniconda3/envs/wenet12/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "~/miniconda3/envs/wenet12/lib/python3.8/site-packages/speechbrain/lobes/models/transformer/Transformer.py", line 464, in forward
    output, attention = enc_layer(
  File "~/miniconda3/envs/wenet12/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "~/miniconda3/envs/wenet12/lib/python3.8/site-packages/speechbrain/lobes/models/transformer/Transformer.py", line 347, in forward
    output, self_attn = self.self_att(
  File "~/miniconda3/envs/wenet12/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "~/miniconda3/envs/wenet12/lib/python3.8/site-packages/speechbrain/nnet/attention.py", line 762, in forward
    output = self.att(
  File "~/miniconda3/envs/wenet12/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "~/miniconda3/envs/wenet12/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 1153, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "~/miniconda3/envs/wenet12/lib/python3.8/site-packages/torch/nn/functional.py", line 5155, in multi_head_attention_forward
    assert key_padding_mask.shape == (bsz, src_len), \
AssertionError: expecting key_padding_mask shape of (1, 30), but got torch.Size([1, 29])
```

### Additional context

the training data is csv format file:
ID,duration,wav,transcript
0,1.918,~/AD00121-AD0012W0001.wav,打开 电视
1,1.931,~/AD00121-AD0012W0002.wav,继续 播放
2,1.279,~/AD00121-AD0012W0003.wav,晚安
........................

I use DynamicItemDataset

train_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
        csv_path=hparams["train_data"], replacements={"data_root": data_folder},
    )

**Comment by toby1123yjh** [comment]
I have same problem, hope for some solutions..

**Comment by TParcollet** [comment]
With DP, please add drop_last: True to your dataloader (in the YAML) :-)

**Comment by toby1123yjh** [comment]
> With DP, please add drop_last: True to your dataloader (in the YAML) :-)

I added drop_last: True in the YAML , but it didn't work. I try DDP instead and it works for me.
refer to this: https://github.com/speechbrain/speechbrain/issues/1580

**Comment by QDPeng** [comment]
> With DP, please add drop_last: True to your dataloader (in the YAML) :-)

add drop_last: True works well in train stage, but in valid stage it's failed，because the drop_last is not used in valid data loader

**Comment by TParcollet** [comment]
Good thanks!
