### ISSUE TITLE
[Bug]: Test TTS/LJ/hifi-gan

### ISSUE THREAD

**Issue by N1r** [speechbrain/speechbrain#1694]
### Describe the bug

Try to learn the recipe in Hifigan vocoder, and something wrong like this, maybe be related to torchaudio, to my best knowledge, can't debug this. I am very appreciated for your help 

### Expected behaviour

Some torch audio version solution or related.

### To Reproduce

python train.py hparams/train.yaml --data_folder /home/dingyr/data1/LJ/LJSpeech-1.1

### Relevant log output

```shell
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: ./results/hifi_gan/1234
ljspeech_prepare -      Creating json file for ljspeech Dataset..
ljspeech_prepare - ./results/hifi_gan/1234/save/train.json successfully created!
ljspeech_prepare - ./results/hifi_gan/1234/save/valid.json successfully created!
speechbrain.core - 84.7M trainable parameters in HifiGanBrain
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
speechbrain.utils.epoch_loop - Going into epoch 1
  0%|                                                                                           | 0/368 [00:00<?, ?it/s]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 388, in <module>
    valid_loader_kwargs=hparams["valid_dataloader_opts"],
  File "/home/dingyr/speechbrain/speechbrain/core.py", line 1154, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/dingyr/speechbrain/speechbrain/core.py", line 1006, in _fit_train
    for batch in t:
  File "/home/dingyr/miniconda3/envs/speechbrain/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/dingyr/miniconda3/envs/speechbrain/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/dingyr/miniconda3/envs/speechbrain/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/dingyr/miniconda3/envs/speechbrain/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/dingyr/miniconda3/envs/speechbrain/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/dingyr/miniconda3/envs/speechbrain/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/dingyr/miniconda3/envs/speechbrain/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dingyr/miniconda3/envs/speechbrain/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dingyr/speechbrain/speechbrain/dataio/dataset.py", line 165, in __getitem__
    return self.pipeline.compute_outputs({"id": data_id, **data_point})
  File "/home/dingyr/speechbrain/speechbrain/utils/data_pipeline.py", line 464, in compute_outputs
    return self._compute(data, self._exec_order, self.output_mapping)
  File "/home/dingyr/speechbrain/speechbrain/utils/data_pipeline.py", line 496, in _compute
    values = item(*args)  # Call the DynamicItem to produce output
  File "/home/dingyr/speechbrain/speechbrain/utils/data_pipeline.py", line 72, in __call__
    return self.func(*args)
  File "train.py", line 310, in audio_pipeline
    mel = hparams["mel_spectogram"](audio=audio.squeeze(0))
  File "/home/dingyr/speechbrain/speechbrain/lobes/models/HifiGAN.py", line 111, in mel_spectogram
    mel = audio_to_mel(audio)
  File "/home/dingyr/miniconda3/envs/speechbrain/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dingyr/miniconda3/envs/speechbrain/lib/python3.7/site-packages/torchaudio/transforms/_transforms.py", line 642, in forward
    specgram = self.spectrogram(waveform)
  File "/home/dingyr/miniconda3/envs/speechbrain/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dingyr/miniconda3/envs/speechbrain/lib/python3.7/site-packages/torchaudio/transforms/_transforms.py", line 119, in forward
    self.onesided,
  File "/home/dingyr/miniconda3/envs/speechbrain/lib/python3.7/site-packages/torchaudio/functional/functional.py", line 114, in spectrogram
    frame_length_norm, window_norm = _get_spec_norms(normalized)
  File "/home/dingyr/miniconda3/envs/speechbrain/lib/python3.7/site-packages/torchaudio/functional/functional.py", line 239, in _get_spec_norms
    raise TypeError("Input type not supported")
TypeError: Input type not supported
```

**Comment by BenoitWang** [comment]
Hi @N1r , did you install the latest version of torch & torchaudio? If this doesn't solve the issue maybe try a new env with python3.8? Hope this can help.

**Comment by QuchenFu** [comment]
same issue

**Comment by AsuMagic** [comment]
The error seems to originate from `mel_spectogram` in `HifiGAN.py` because of the `normalized` parameter. `torchaudio` (now) raises an error when `normalized` is not a `bool` or a `str` that defines the normalization type.

It seems like `hifi_gan` (and possibly `tacotron2`) LJSpeech recipes define `mel_normalized: null` in the hyperparameters file. I imagine this translates into a `None` value in practice, hence the error.

See:
- `recipes/LJSpeech/TTS/vocoder/hifi_gan/hparams/train.yaml`
- `recipes/LJSpeech/TTS/tacotron2/hparams/train.yaml`

Maybe if you set `mel_normalized: False` instead it will work.

**Comment by BenoitWang** [comment]
Hi @N1r @QuchenFu @AsuMagic , sorry that I almost ignored this issue, it's quite an important one. I reproduced the error, and by changing `normalized: null` into `normalized: False` does solve the issue, thanks for the catch @AsuMagic.
I'll open a PR for the fix, thank you all for reporting.
