### ISSUE TITLE
[Bug]: Training on CommonVoice Transformer recipe with data_parallel crashes

### ISSUE THREAD

**Issue by thibault-roux** [speechbrain/speechbrain#1713]
### Describe the bug

Bug similar to https://github.com/speechbrain/speechbrain/issues/651.

When trying to train a transformer using the Common Voice recipe (https://github.com/speechbrain/speechbrain/tree/develop/recipes/CommonVoice/ASR/transformer) with --data_parallel, I have the following error:

```
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
speechbrain.utils.epoch_loop - Going into epoch 1
  0%|          | 0/61736 [00:08<?, ?it/s]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "/gpfsdswork/projects/rech/rbg/ujc17nz/expe/train/transformer/ASR/train_transformer.py", line 433, in <module>
    asr_brain.fit(
  File "/gpfsdswork/projects/rech/rbg/ujc17nz/expe/train/speechbrain/speechbrain/core.py", line 1154, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/gpfsdswork/projects/rech/rbg/ujc17nz/expe/train/speechbrain/speechbrain/core.py", line 1011, in _fit_train
    loss = self.fit_batch(batch)
  File "/gpfsdswork/projects/rech/rbg/ujc17nz/expe/train/transformer/ASR/train_transformer.py", line 136, in fit_batch
    predictions = self.compute_forward(batch, sb.Stage.TRAIN)
  File "/gpfsdswork/projects/rech/rbg/ujc17nz/expe/train/transformer/ASR/train_transformer.py", line 62, in compute_forward
    enc_out, pred = self.modules.Transformer(
  File "/linkhome/rech/genlsn01/ujc17nz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/linkhome/rech/genlsn01/ujc17nz/.local/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/linkhome/rech/genlsn01/ujc17nz/.local/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/linkhome/rech/genlsn01/ujc17nz/.local/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/linkhome/rech/genlsn01/ujc17nz/.local/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
AssertionError: Caught AssertionError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/linkhome/rech/genlsn01/ujc17nz/.local/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/linkhome/rech/genlsn01/ujc17nz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/gpfsdswork/projects/rech/rbg/ujc17nz/expe/train/speechbrain/speechbrain/lobes/models/transformer/TransformerASR.py", line 177, in forward

    encoder_out, _ = self.encoder(
  File "/linkhome/rech/genlsn01/ujc17nz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/gpfsdswork/projects/rech/rbg/ujc17nz/expe/train/speechbrain/speechbrain/lobes/models/transformer/Transformer.py", line 477, in forward
    output, attention = enc_layer(
  File "/linkhome/rech/genlsn01/ujc17nz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/gpfsdswork/projects/rech/rbg/ujc17nz/expe/train/speechbrain/speechbrain/lobes/models/transformer/Transformer.py", line 349, in forward
    output, self_attn = self.self_att(
  File "/linkhome/rech/genlsn01/ujc17nz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/gpfsdswork/projects/rech/rbg/ujc17nz/expe/train/speechbrain/speechbrain/nnet/attention.py", line 762, in forward
    output = self.att(
  File "/linkhome/rech/genlsn01/ujc17nz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/linkhome/rech/genlsn01/ujc17nz/.local/lib/python3.9/site-packages/torch/nn/modules/activation.py", line 1167, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "/linkhome/rech/genlsn01/ujc17nz/.local/lib/python3.9/site-packages/torch/nn/functional.py", line 5130, in multi_head_attention_forward
    assert key_padding_mask.shape == (bsz, src_len), \
AssertionError: expecting key_padding_mask shape of (2, 205), but got torch.Size([2, 93])
```

When running without --data_parallel with one GPU, it seemed to work. At the moment, the training is at 22% of first epoch.

I test it on different HPC and with different conda environments. Still the same trouble.

### Expected behaviour

The training should have launched as without --data_parallel.

**Comment by TParcollet** [comment]
Hi, we will soon drop the support for data_parallel as it is being deprecated by PyTorch and is really not good compared to DDP. Please use DDP
