### ISSUE TITLE
[Bug]: There is no such class as speechbrain.lobes.models.FastSpeech2.FastSpeech2

### ISSUE THREAD

**Issue by chaiv** [speechbrain/speechbrain#1726]
### Describe the bug

Hi, I try to follow the tutorial https://huggingface.co/speechbrain/tts-fastspeech2-ljspeech. I did "pip install speechbrain"
and then: 

`from speechbrain.pretrained import Tacotron2`
`tacotron2 = Tacotron2.from_hparams(source="speechbrain/tts-tacotron2-ljspeech", savedir="tmpdir_tts")`

throws this: 

`ImportError: There is no such class as speechbrain.lobes.models.FastSpeech2.FastSpeech2`

Am I missing something? 

### Expected behaviour

Tutorial example works

### To Reproduce

pip install speechbrain
`from speechbrain.pretrained import Tacotron2`
`tacotron2 = Tacotron2.from_hparams(source="speechbrain/tts-tacotron2-ljspeech", savedir="tmpdir_tts")`

### Versions

Version: 0.5.13

### Relevant log output

```shell
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
C:\Users\vital\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: Could not find module 'C:\Users\vital\AppData\Local\Programs\Python\Python310\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  warn(f"Failed to load image Python extension: {e}")
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Traceback (most recent call last):
  File "C:\Users\vital\git\ezlan\elzan\main\ezlanTTSTacotronTest.py", line 12, in <module>
    tacotron2 = Tacotron2.from_hparams(source="speechbrain/tts-tacotron2-ljspeech", savedir="tmpdir_tts")
  File "C:\Users\vital\AppData\Local\Programs\Python\Python310\lib\site-packages\speechbrain\pretrained\interfaces.py", line 362, in from_hparams
    hparams = load_hyperpyyaml(fin, overrides)
  File "C:\Users\vital\AppData\Local\Programs\Python\Python310\lib\site-packages\hyperpyyaml\core.py", line 184, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=yaml.Loader)
  File "C:\Users\vital\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\vital\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "C:\Users\vital\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "C:\Users\vital\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\constructor.py", line 107, in construct_object
    for dummy in generator:
  File "C:\Users\vital\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "C:\Users\vital\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "C:\Users\vital\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "C:\Users\vital\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\constructor.py", line 102, in construct_object
    data = constructor(self, tag_suffix, node)
  File "C:\Users\vital\AppData\Local\Programs\Python\Python310\lib\site-packages\hyperpyyaml\core.py", line 455, in _construct_object
    raise ImportError("There is no such class as %s" % callable_string)
ImportError: There is no such class as speechbrain.lobes.models.FastSpeech2.FastSpeech2
```

**Comment by TParcollet** [comment]
Hi, could you please report your entire environment as well as OS? I just tried in a fresh conda env with a Linux plateform and it worked as expected.

**Comment by mravanelli** [comment]
Hi,
as mentioned in the README, fastspeech2 is still a work in progress. To
avoid misunderstandings, I made this model private again.

Best,

Mirco
