### ISSUE TITLE
[Bug]: Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now

### ISSUE THREAD

**Issue by makaveli10** [speechbrain/speechbrain#1765]
### Describe the bug

Hello, thanks for sharing the work.
I have been trying to finetune the speaker classification model but I see this padding issue with my custom dataset. I resampled all my audio files to ```16000```.
Any help on this would be much appreciated.
thanks.
```
peechbrain.dataio.encoder - Load called, but CategoricalEncoder is not empty. Loaded data will overwrite everything. This is normal if there is e.g. an unk label defined at init.
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - 4.5M trainable parameters in SpkIdBrain
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
speechbrain.utils.epoch_loop - Going into epoch 1
  0%|                                                                                             | 0/66 [00:00<?, ?it/s]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "/opt/vineet-workspace/speechbrain/templates/speaker_id/custom_model.py", line 111, in forward
    x = layer(x, lengths=lens)
  File "/opt/vineet-workspace/miniconda3/envs/sbrain/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'lengths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/vineet-workspace/speechbrain/templates/speaker_id/train.py", line 326, in <module>
    spk_id_brain.fit(
  File "/opt/vineet-workspace/speechbrain/speechbrain/core.py", line 1197, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/opt/vineet-workspace/speechbrain/speechbrain/core.py", line 1050, in _fit_train
    loss = self.fit_batch(batch)
  File "/opt/vineet-workspace/speechbrain/speechbrain/core.py", line 921, in fit_batch
    outputs = self.compute_forward(batch, Stage.TRAIN)
  File "/opt/vineet-workspace/speechbrain/templates/speaker_id/train.py", line 61, in compute_forward
    embeddings = self.modules.embedding_model(feats, lens)
  File "/opt/vineet-workspace/miniconda3/envs/sbrain/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/vineet-workspace/speechbrain/templates/speaker_id/custom_model.py", line 113, in forward
    x = layer(x)
  File "/opt/vineet-workspace/miniconda3/envs/sbrain/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/vineet-workspace/speechbrain/speechbrain/nnet/CNN.py", line 419, in forward
    x = self._manage_padding(
  File "/opt/vineet-workspace/speechbrain/speechbrain/nnet/CNN.py", line 471, in _manage_padding
    x = F.pad(x, padding, mode=self.padding_mode)
NotImplementedError: Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now
```

### Expected behaviour

To train the model on custom dataset.

**Comment by makaveli10** [comment]
My audio inputs were dual channel so I had to convert them to mono. and voila!!

**Comment by fabiocat93** [comment]
hi @makaveli10 , were able to extract the embeddings from a batch of audio files or one only? I am facing the same issue as you when I extract embeddings from a batch of >1 files (batch_size, channels, audio_lenght), but with only one file (channels, audio_lenght) is fine. thank you

**Comment by a897456** [comment]
/home/rian0532/anaconda3/bin/conda run -n speechbrain --no-capture-output python /mnt/e/000/speechbrain-SE/recipes/AudioMNIST/diffusion/train.py /mnt/e/000/speechbrain-SE/recipes/AudioMNIST/diffusion/hparams/train.yaml --data_folder=/mnt/e/000/speechbrain-SE/recipes/AudioMNIST/diffusion/DataAudioMNIST 
 
 Could not enable Tensorboard logging - Tensorboard is not available
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: ./results/diffusion/baseline/1986
audiomnist_prepare - Skipping preparation, completed in previous run.
speechbrain.core - Info: max_grad_norm arg from hparam file is used
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - Gradscaler enabled: False. Using precision: fp32.
speechbrain.core - DiffusionBrain Model Statistics:
* Total Number of Trainable Parameters: 398.9M
* Total Number of Parameters: 398.9M
* Trainable Parameters represent 100.0000% of the total size.
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
speechbrain.utils.epoch_loop - Going into epoch 1
speechbrain.utils.fetching - Fetch hyperparams.yaml: Using existing file/symlink in pretrained_models/HIFIGAN-92ca03b8a61b04650be053125e9597a9/hyperparams.yaml.
speechbrain.utils.fetching - Fetch custom.py: Delegating to Huggingface hub, source speechbrain/tts-hifigan-libritts-16kHz.
/home/rian0532/anaconda3/envs/speechbrain/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
speechbrain.utils.fetching - Fetch generator.ckpt: Using existing file/symlink in pretrained_models/HIFIGAN-92ca03b8a61b04650be053125e9597a9/generator.ckpt.
speechbrain.utils.parameter_transfer - Loading pretrained files for: generator
  0%|          | 0/1783 [00:01<?, ?it/s]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "/mnt/e/000/speechbrain-SE/recipes/AudioMNIST/diffusion/train.py", line 1648, in <module>
    diffusion_brain.fit(
  File "/mnt/e/000/speechbrain-SE/speechbrain/core.py", line 1607, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/mnt/e/000/speechbrain-SE/speechbrain/core.py", line 1430, in _fit_train
    loss = self.fit_batch(batch)
  File "/mnt/e/000/speechbrain-SE/recipes/AudioMNIST/diffusion/train.py", line 307, in fit_batch
    outputs = self.compute_forward(batch, sb.Stage.TRAIN)
  File "/mnt/e/000/speechbrain-SE/recipes/AudioMNIST/diffusion/train.py", line 180, in compute_forward
    pred, noise, noisy_sample = self.modules.diffusion.train_sample(
  File "/mnt/e/000/speechbrain-SE/speechbrain/nnet/diffusion.py", line 102, in train_sample
    pred = self.model(noisy_sample, timesteps, **kwargs)
  File "/home/rian0532/anaconda3/envs/speechbrain/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/rian0532/anaconda3/envs/speechbrain/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'lens'
ERROR conda.cli.main_run:execute(49): `conda run python /mnt/e/000/speechbrain-SE/recipes/AudioMNIST/diffusion/train.py /mnt/e/000/speechbrain-SE/recipes/AudioMNIST/diffusion/hparams/train.yaml --data_folder=/mnt/e/000/speechbrain-SE/recipes/AudioMNIST/diffusion/DataAudioMNIST` failed. (See above for error)

进程已结束，退出代码为 1

### same problem:TypeError: forward() got an unexpected keyword argument 'lens'

**Comment by asumagic** [comment]
@a897456 This is not the same issue, also if you are using a `develop` version of SpeechBrain as I said make sure you are merging #2598 locally. If the issue persists, make a new issue.

**Comment by a897456** [comment]
> @a897456 This is not the same issue, also if you are using a `develop` version of SpeechBrain as I said make sure you are merging #2598 locally. If the issue persists, make a new issue. (Marking this as off-topic to reduce clutter on this issue)

Hi @asumagic 
I didn't understand what you meant by develop and V1.0 until I found this（as follows）, and should I choose V1.01 and then download the code?
![image](https://github.com/speechbrain/speechbrain/assets/28752526/ecf0fb73-43d8-460e-bc6d-f22df3237de7)

**Comment by asumagic** [comment]
@a897456 Please rather move this to a new discussion, because posting on existing issues might notify participants and is harder to search.
