### ISSUE TITLE
[Bug]: Wav2Vec2 training on multiple GPUs

### ISSUE THREAD

**Issue by RaphaelOlivier** [speechbrain/speechbrain#1770]
### Describe the bug

Are we supposed to use the `--data_parallel_backend` argument with the Speechbrain wav2vec2 training recipe? It seems to raise a lot of issues when I use it.

### Expected behaviour

I am trying to use [this recipe](https://github.com/speechbrain/speechbrain/tree/develop/recipes/LibriSpeech/self-supervised-learning/wav2vec2).
If I run `python train_sb_wav2vec2.py hparams/wav2vec2_base.yaml --data_folder=$PROJECT/data` then training looks fine at the beginning. The loss decreases at least for the first 5k steps. But I am not sure whether it is using the 8 GPUs on my node or not.
On the other hand, when I run `python train_sb_wav2vec2.py hparams/wav2vec2_base.yaml --data_folder=$PROJECT/data --data_parallel_backend`, depending on the GPUs I make visible I get different kinds of errors, like:

```
Traceback (most recent call last):
  File "/jet/home/rolivier/workspace/speechbrain/recipes/LibriSpeech/self-supervised-learning/wav2vec2/train_sb_wav2vec2.py", line 384, in <module>
    main()
  File "/jet/home/rolivier/workspace/speechbrain/recipes/LibriSpeech/self-supervised-learning/wav2vec2/train_sb_wav2vec2.py", line 374, in main
    brain.fit(
  File "/jet/home/rolivier/workspace/speechbrain/speechbrain/core.py", line 1197, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/jet/home/rolivier/workspace/speechbrain/speechbrain/core.py", line 1050, in _fit_train
    loss = self.fit_batch(batch)
  File "/jet/home/rolivier/workspace/speechbrain/recipes/LibriSpeech/self-supervised-learning/wav2vec2/train_sb_wav2vec2.py", line 164, in fit_batch
    self.on_fit_batch_end(objectives)
  File "/jet/home/rolivier/workspace/speechbrain/recipes/LibriSpeech/self-supervised-learning/wav2vec2/train_sb_wav2vec2.py", line 175, in on_fit_batch_end
    w2v_model.quantiser.update_temp(self.optimizer_step)
  File "/jet/home/rolivier/anaconda3/envs/speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DataParallel' object has no attribute 'quantiser'
```

or 

```
Traceback (most recent call last):
  File "/jet/home/rolivier/workspace/speechbrain/recipes/LibriSpeech/self-supervised-learning/wav2vec2/train_sb_wav2vec2.py", line 384, in <module>
    main()
  File "/jet/home/rolivier/workspace/speechbrain/recipes/LibriSpeech/self-supervised-learning/wav2vec2/train_sb_wav2vec2.py", line 374, in main
    brain.fit(
  File "/jet/home/rolivier/workspace/speechbrain/speechbrain/core.py", line 1197, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/jet/home/rolivier/workspace/speechbrain/speechbrain/core.py", line 1050, in _fit_train
    loss = self.fit_batch(batch)
  File "/jet/home/rolivier/workspace/speechbrain/recipes/LibriSpeech/self-supervised-learning/wav2vec2/train_sb_wav2vec2.py", line 128, in fit_batch
    outputs = self.compute_forward(batch, Stage.TRAIN)
  File "/jet/home/rolivier/workspace/speechbrain/recipes/LibriSpeech/self-supervised-learning/wav2vec2/train_sb_wav2vec2.py", line 51, in compute_forward
    latents = self.modules.latent_extractor(wavs, normalize_signal=False)
  File "/jet/home/rolivier/anaconda3/envs/speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/jet/home/rolivier/anaconda3/envs/speech/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/jet/home/rolivier/anaconda3/envs/speech/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/jet/home/rolivier/anaconda3/envs/speech/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/jet/home/rolivier/anaconda3/envs/speech/lib/python3.10/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
TypeError: Caught TypeError in replica 7 on device 7.
Original Traceback (most recent call last):
  File "/jet/home/rolivier/anaconda3/envs/speech/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/jet/home/rolivier/anaconda3/envs/speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: W2VLatentExtractor.forward() missing 1 required positional argument: 'x'
```

Does it mean that this option is not required to run the script in parallel?

**Comment by TParcollet** [comment]
Hi, please don't use DataParallel but instead DistributedDataParallel for w2v2, we are slowly discontinuing the support of DP as advised by PyTorch.

**Comment by RaphaelOlivier** [comment]
Got it, thanks! That does seem to fix these issues. I was not aware that DataParallel was being depracated.
