### ISSUE TITLE
[Bug]: Exporting Tacotron2 into onnx file

### ISSUE THREAD

**Issue by mquillot** [speechbrain/speechbrain#1774]
### Describe the bug

Hello, 

I am trying to to export tacotron2 into onnx file. Following the [documentation of PyTorch](https://pytorch.org/docs/stable/onnx.html#example-alexnet-from-pytorch-to-onnx), I have chosen to use script() function. Unfortunately, this does not work and shows me an error. 

Here is my code (maybe some imports are forgotten): 
```python
import torch
from speechbrain.pretrained import Tacotron2

tacotron2 = Tacotron2.from_hparams(source="speechbrain/tts-tacotron2-ljspeech", savedir="tmpdir_tts")
scriptModule = torch.jit.script(tacotron2)
torch.onnx.export(scriptModule, ["hello"], "tacotron2.onnx", verbose=True)
```

Here you can find the resulting error:
```
Traceback (most recent call last):
  File "/home/mquillot/TTS_experiment/sb_experiment.py", line 26, in <module>
    scriptModule = torch.jit.script(tacotron2)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_script.py", line 1286, in script
    return torch.jit._recursive.create_script_module(
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_recursive.py", line 476, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_recursive.py", line 538, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_script.py", line 615, in _construct
    init_fn(script_module)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_recursive.py", line 516, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_recursive.py", line 538, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_script.py", line 615, in _construct
    init_fn(script_module)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_recursive.py", line 516, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_recursive.py", line 538, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_script.py", line 615, in _construct
    init_fn(script_module)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_recursive.py", line 516, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_recursive.py", line 393, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: Unsupported value kind: Tensor
```

Here you can find versions of my main python packages:
```
huggingface-hub==0.11.1
numpy==1.24.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
PyYAML==6.0
scipy==1.9.3
speechbrain==0.5.13
torch==1.13.1
torchaudio==0.13.1
```

I am working with Python 3.9.15 using conda environment.

Please, can you tell if I am doing something wrong or if some calculations are not compatible with onnx exporting?

Best regards,
Mathias.

### Expected behaviour

I am expecting the generation of an onnx file when I am using ```torch.onnx.export```. 

### To Reproduce

```python
import torch
from speechbrain.pretrained import Tacotron2

tacotron2 = Tacotron2.from_hparams(source="speechbrain/tts-tacotron2-ljspeech", savedir="tmpdir_tts")
scriptModule = torch.jit.script(tacotron2)
torch.onnx.export(scriptModule, ["hello"], "tacotron2.onnx", verbose=True)
```

### Versions

huggingface-hub==0.11.1
numpy==1.24.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
PyYAML==6.0
scipy==1.9.3
speechbrain==0.5.13
torch==1.13.1
torchaudio==0.13.1

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/mquillot/TTS_experiment/sb_experiment.py", line 26, in <module>
    scriptModule = torch.jit.script(tacotron2)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_script.py", line 1286, in script
    return torch.jit._recursive.create_script_module(
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_recursive.py", line 476, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_recursive.py", line 538, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_script.py", line 615, in _construct
    init_fn(script_module)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_recursive.py", line 516, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_recursive.py", line 538, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_script.py", line 615, in _construct
    init_fn(script_module)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_recursive.py", line 516, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_recursive.py", line 538, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_script.py", line 615, in _construct
    init_fn(script_module)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_recursive.py", line 516, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/mquillot/speechbrain/lib/python3.9/site-packages/torch/jit/_recursive.py", line 393, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: Unsupported value kind: Tensor
```

**Comment by TParcollet** [comment]
@BenoitWang @mravanelli any ideas?

**Comment by AsuMagic** [comment]
I looked into the issue.

It seems that the "unsupported value kind" errors arises when the compiler hits `get_mask_from_lengths`. It appears to get confused about the type for `max_len` and blows up while compiling `Decoder.infer`. I found that explicitly annotating the type with `: Optional[int]` solves it.

It then errors differently in `Tacotron2.forward`, because it really, really hates the tuple expansion for `inputs`. However, the rest of the code seems to assume the forward code path is not to be JITted anyway (`Decoder.forward` is annotated with `torch.jit.ignore`). If you annotate `Tacotron2.forward` with `@torch.jit.ignore` and `Tacotron2.infer` with `@torch.jit.export`, then `torch.jit.script(Tacotron2())` doesn't fail.

I have not tried actually using it, nor have I tried the ONNX conversion (which has more chances to fail still), but the above solves the TorchScript compile issue.

**Comment by mquillot** [comment]
Thank you @AsuMagic !

I tried your solution but I encountered other problems.


I added the following line in pretrained.interfaces at line 220. Indeed, the compilation of jit raised an error cause of the type of hparams :

```
self.text_to_sequence = self.hparams.text_to_sequence
```

Also, I replaced the call of text_to_sequence in text_to_seq method (line 2745):
```
sequence = self.text_to_sequence(txt, self.text_cleaners)
``` 

Then, I get the following error.

`
Module 'Tacotron2' has no attribute 'text_to_sequence' (This attribute exists on the Python module, but we failed to convert Python type: 'functools.partial' to a TorchScript type. Only tensors and (possibly nested) tuples of tensors, lists, or dictsare supported as inputs or outputs of traced functions, but instead got value of type partial.. Its type was inferred; try adding a type annotation for the attribute.):
`

If I ignore the text_to_seq (Pretrained.Interfaces.Tacotron2.text_to_seq) step with an ```@torch.jit.ignore```, the following error appears: 

`
torch.jit.frontend.NotSupportedError: keyword-arg expansion is not supported:
  File "/XXX/speechbrain/dataio/batch.py", line 125
`

Do you have any idea to solve this problem?

**Comment by AsuMagic** [comment]
Right, the errors seem to come from the JIT compile of the `pretrained.interfaces.Tacotron2` class rather than the `lobes.models.Tacotron2.Tacotron2` class. I only tested the latter.

What is your usecase for using an ONNX model? If you want to embed the model in some app or service written in a different language, the best course of action IMO is probably to rewrite the high-level interface (`pretrained.interfaces.Tacotron2`). You may also have to rewrite `text_to_sequence` in your app too: I can see it do a bunch of things like using regexes, which is probably super duper unsupported by the JIT.
