### ISSUE TITLE
[Bug]: fine tuning using multi-GPU

### ISSUE THREAD

**Issue by starcell** [speechbrain/speechbrain#1797]
### Describe the bug

When I run fine tuning ASR training with mulit-GPU(DDP), below error occures.

FileExistsError: [Errno 17] File exists: '/workspace/speechbrain/recipes/KdialectSpeech/ASR/Conformer/Fine-tune/../Inference/pretrained-model-src/kspon/custom.py' -> '../Inference/pretrained-model-save/kspon/custom.py'

### Expected behaviour

Run model training without error.

### To Reproduce

My run command 
```
python -m torch.distributed.launch --nproc_per_node=4 fine-tune-train.py hparams/conformer_medium.yaml --distributed_launch --distributed_backend='nccl'
```

My python code where error occures
```
pretrained_model = EncoderDecoderASR.from_hparams(
        source=source,
        savedir=savedir,
        run_opts={"device":"cuda"}
    )
```

### Versions

v0.5.13

### Relevant log output

```shell
root@f7a78deb39a6:/workspace/speechbrain/recipes/KdialectSpeech/ASR/Conformer/Fine-tune# python -m torch.distributed.launch --nproc_per_node=4 fine-tune-train.py hparams/conformer_medium.yaml --distributed_launch --distributed_backend='nccl' &
[1] 2652405
root@f7a78deb39a6:/workspace/speechbrain/recipes/KdialectSpeech/ASR/Conformer/Fine-tune# /opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

warnings.warn(
WARNING:torch.distributed.run:

Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.

hparams/conformer_medium.yaml
hparams/conformer_medium.yaml
hparams/conformer_medium.yaml
hparams/conformer_medium.yaml
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: results/Conformer/5555/jl
kdialectspeech_prepare - save_folder : ../../../Tokenizer/results/data_prepared/jl
kdialectspeech_prepare - skip : True
kdialectspeech_prepare - Skipping preparation, completed in previous run.
speechbrain.pretrained.fetching - Fetch 5000_unigram.model: Using existing file/symlink in results/Conformer/5555/jl/save/tokenizer.ckpt.
speechbrain.utils.parameter_transfer - Loading pretrained files for: tokenizer
speechbrain.pretrained.fetching - Fetch hyperparams.yaml: Using existing file/symlink in ../Inference/pretrained-model-save/kspon/hyperparams.yaml.
speechbrain.pretrained.fetching - Fetch custom.py: Linking to local file in /workspace/speechbrain/recipes/KdialectSpeech/ASR/Conformer/Fine-tune/../Inference/pretrained-model-src/kspon/custom.py.
Traceback (most recent call last):
Traceback (most recent call last):
  File "fine-tune-train.py", line 533, in <module>
  File "fine-tune-train.py", line 533, in <module>
    pretrained_model = EncoderDecoderASR.from_hparams(
  File "/workspace/speechbrain/speechbrain/pretrained/interfaces.py", line 377, in from_hparams
    pretrained_model = EncoderDecoderASR.from_hparams(
  File "/workspace/speechbrain/speechbrain/pretrained/interfaces.py", line 377, in from_hparams
    pymodule_local_path = fetch(
  File "/workspace/speechbrain/speechbrain/pretrained/fetching.py", line 113, in fetch
    pymodule_local_path = fetch(
  File "/workspace/speechbrain/speechbrain/pretrained/fetching.py", line 113, in fetch
    destination.symlink_to(sourcepath)
  File "/opt/conda/lib/python3.8/pathlib.py", line 1384, in symlink_to
    destination.symlink_to(sourcepath)
  File "/opt/conda/lib/python3.8/pathlib.py", line 1384, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
  File "/opt/conda/lib/python3.8/pathlib.py", line 446, in symlink
    self._accessor.symlink(target, self, target_is_directory)
  File "/opt/conda/lib/python3.8/pathlib.py", line 446, in symlink
    return os.symlink(a, b)
FileExistsError: [Errno 17] File exists: '/workspace/speechbrain/recipes/KdialectSpeech/ASR/Conformer/Fine-tune/../Inference/pretrained-model-src/kspon/custom.py' -> '../Inference/pretrained-model-save/kspon/custom.py'
    return os.symlink(a, b)
FileExistsError: [Errno 17] File exists: '/workspace/speechbrain/recipes/KdialectSpeech/ASR/Conformer/Fine-tune/../Inference/pretrained-model-src/kspon/custom.py' -> '../Inference/pretrained-model-save/kspon/custom.py'
speechbrain.pretrained.fetching - Fetch normalizer.ckpt: Using existing file/symlink in ../Inference/pretrained-model-save/kspon/normalizer.ckpt.
speechbrain.pretrained.fetching - Fetch asr.ckpt: Using existing file/symlink in ../Inference/pretrained-model-save/kspon/asr.ckpt.
speechbrain.pretrained.fetching - Fetch tokenizer.ckpt: Using existing file/symlink in ../Inference/pretrained-model-save/kspon/tokenizer.ckpt.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2652479 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2652482 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 2652480) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:


fine-tune-train.py FAILED
```

**Comment by anautsch** [comment]
Hi @starcell would you like to share more of your `fine-tune-train.py` file?

I started pickung up again on the audio data handling issue described in several other PRs & issues (to get it done eventually). See: https://github.com/speechbrain/speechbrain/pull/1303#issuecomment-1131467275

Thus far, pretrained models are just way of indicating how to use pretrained models, but w/o the intention to assist every user in their specific fine-tuning tasks (in a way that would imply a mirroring of the whole recipes folder structure which is beyond the point). Last week, I came to the realisation, it would be neat to have a minimal example (perhaps a template? ...now that I write about it...) where also your fine-tuning approach would be covered by the example of that template. If you like, please lets develop that together.

How did you initialise DDP?
Is the fetching part handled on the main process only, such that hparams are read from local disk by all child processes?
(reading into your stacktrace w/o reproducing the error)

**Comment by starcell** [comment]
Run command :
```
python -m torch.distributed.launch --nproc_per_node=4 fine-tune-train.py hparams/conformer_medium.yaml --distributed_launch --distributed_backend='nccl'
```


Error occeres when  EncoderDecoderASR.from_hparams() is called :
```
    pretrained_model = EncoderDecoderASR.from_hparams(
        source=source,
        savedir=savedir,
        run_opts={"device":"cuda"}
    )
```

My entire code :
```
#!/usr/bin/env python3

from torch.utils.tensorboard import SummaryWriter # 중요, 맨 

import os
import sys
import torch
import logging
from pathlib import Path
import speechbrain as sb
from hyperpyyaml import load_hyperpyyaml
from speechbrain.utils.distributed import run_on_main
from speechbrain.pretrained import EncoderDecoderASR
from speechbrain.utils.parameter_transfer import Pretrainer

logger = logging.getLogger(__name__)

# Define training procedure
class ASR(sb.core.Brain):
    def compute_forward(self, batch, stage):

        batch = batch.to(self.device)
        wavs, wav_lens = batch.sig
        tokens_bos, _ = batch.tokens_bos

        # Add augmentation if specified
        ### kdialectspeech, ksponspeech, librispeech 에서는 사용안함, template 예제에서 사용
        if stage == sb.Stage.TRAIN:
            if hasattr(self.modules, "env_corrupt"):
                wavs_noise = self.modules.env_corrupt(wavs, wav_lens)
                wavs = torch.cat([wavs, wavs_noise], dim=0)
                wav_lens = torch.cat([wav_lens, wav_lens])
                tokens_bos = torch.cat([tokens_bos, tokens_bos], dim=0)

        # compute features
        feats = self.hparams.compute_features(wavs)
        current_epoch = self.hparams.epoch_counter.current
        feats = self.modules.normalize(feats, wav_lens, epoch=current_epoch)

        if stage == sb.Stage.TRAIN:
            if hasattr(self.hparams, "augmentation"):
                feats = self.hparams.augmentation(feats)

        # forward modules
        src = self.modules.CNN(feats)
        enc_out, pred = self.modules.Transformer( # pred : decoder out
            src, tokens_bos, wav_lens, pad_idx=self.hparams.pad_index
        )

        # output layer for ctc log-probabilities
        logits = self.modules.ctc_lin(enc_out)
        p_ctc = self.hparams.log_softmax(logits)

        # output layer for seq2seq log-probabilities
        pred = self.modules.seq_lin(pred)
        p_seq = self.hparams.log_softmax(pred)

        # print(f'enc_out size : {enc_out.size()}')
        # Compute outputs
        hyps = None
        if stage == sb.Stage.TRAIN:
            hyps = None
        elif stage == sb.Stage.VALID:
            hyps = None
            current_epoch = self.hparams.epoch_counter.current
            if current_epoch % self.hparams.valid_search_interval == 0:
                # for the sake of efficiency, we only perform beamsearch with
                # limited capacity and no LM to give user some idea of
                # how the AM is doing
                hyps, _ = self.hparams.valid_search(enc_out.detach(), wav_lens)
        elif stage == sb.Stage.TEST:
            hyps, _ = self.hparams.test_search(enc_out.detach(), wav_lens) 
        return p_ctc, p_seq, wav_lens, hyps

    def compute_objectives(self, predictions, batch, stage):
        
        (p_ctc, p_seq, wav_lens, hyps,) = predictions

        ids = batch.id
        tokens_eos, tokens_eos_lens = batch.tokens_eos
        tokens, tokens_lens = batch.tokens

        if hasattr(self.modules, "env_corrupt") and stage == sb.Stage.TRAIN:
            tokens_eos = torch.cat([tokens_eos, tokens_eos], dim=0)
            tokens_eos_lens = torch.cat(
                [tokens_eos_lens, tokens_eos_lens], dim=0
            )
            tokens = torch.cat([tokens, tokens], dim=0)
            tokens_lens = torch.cat([tokens_lens, tokens_lens], dim=0)

        loss_seq = self.hparams.seq_cost(
            p_seq, tokens_eos, length=tokens_eos_lens
        )
        loss_ctc = self.hparams.ctc_cost(p_ctc, tokens, wav_lens, tokens_lens)
        loss = (
            self.hparams.ctc_weight * loss_ctc
            + (1 - self.hparams.ctc_weight) * loss_seq
        )
        if stage != sb.Stage.TRAIN:
            current_epoch = self.hparams.epoch_counter.current
            valid_search_interval = self.hparams.valid_search_interval
            if current_epoch % valid_search_interval == 0 or (
                stage == sb.Stage.TEST
            ):
                # Decode token terms to words
                predicted_words = [
                    tokenizer.decode_ids(utt_seq).split(" ") for utt_seq in hyps
                ]
                target_words = [wrd.split(" ") for wrd in batch.wrd]

                predicted_chars = [
                    list("".join(utt_seq)) for utt_seq in predicted_words
                ]
                target_chars = [list("".join(wrd.split())) for wrd in batch.wrd]
                self.wer_metric.append(ids, predicted_words, target_words)
                self.cer_metric.append(ids, predicted_chars, target_chars)

            # compute the accuracy of the one-step-forward prediction
            self.acc_metric.append(p_seq, tokens_eos, tokens_eos_lens)
        return loss

    def fit_batch(self, batch):
        # check if we need to switch optimizer
        # if so change the optimizer from Adam to SGD
        
        self.check_and_reset_optimizer()

        predictions = self.compute_forward(batch, sb.Stage.TRAIN)
        loss = self.compute_objectives(predictions, batch, sb.Stage.TRAIN)

        # normalize the loss by gradient_accumulation step
        (loss / self.hparams.gradient_accumulation).backward()

        if self.step % self.hparams.gradient_accumulation == 0:
            # gradient clipping & early stop if loss is not fini
            self.check_gradients(loss)

            self.optimizer.step()
            self.optimizer.zero_grad()

            # anneal lr every update
            self.hparams.noam_annealing(self.optimizer)

            if isinstance(
                self.hparams.train_logger,
                sb.utils.train_logger.TensorboardLogger,
            ):
                self.hparams.train_logger.log_stats(
                    stats_meta={"step": self.step}, train_stats={"loss": loss},
                )

        return loss.detach()

    def evaluate_batch(self, batch, stage): 
        
        with torch.no_grad():
            predictions = self.compute_forward(batch, stage=stage)
            loss = self.compute_objectives(predictions, batch, stage=stage)
        return loss.detach()

    def on_stage_start(self, stage, epoch):
	
        if stage != sb.Stage.TRAIN:
            self.acc_metric = self.hparams.acc_computer()
            self.wer_metric = self.hparams.error_rate_computer()
            # self.swer_metric = self.hparams.error_rate_computer()
            self.cer_metric = self.hparams.error_rate_computer()
        else:
            for module in [self.modules.CNN, self.modules.Transformer, self.modules.seq_lin, self.modules.ctc_lin]:
                for p in module.parameters():
                    p.requires_grad = True

    def on_stage_end(self, stage, stage_loss, epoch):
	
        # Compute/store important stats
        stage_stats = {"loss": stage_loss}
        if stage == sb.Stage.TRAIN:
            self.train_stats = stage_stats
        else:
            stage_stats["ACC"] = self.acc_metric.summarize()
            current_epoch = self.hparams.epoch_counter.current
            valid_search_interval = self.hparams.valid_search_interval
            if (
                current_epoch % valid_search_interval == 0
                or stage == sb.Stage.TEST
            ):
                stage_stats["WER"] = self.wer_metric.summarize("error_rate")
                # stage_stats["sWER"] = self.swer_metric.summarize("error_rate")
                stage_stats["CER"] = self.cer_metric.summarize("error_rate")

        # log stats and save checkpoint at end-of-epoch
        if stage == sb.Stage.VALID and sb.utils.distributed.if_main_process():

            # report different epoch stages according current stage
            current_epoch = self.hparams.epoch_counter.current
            if current_epoch <= self.hparams.stage_one_epochs:
                lr = self.hparams.noam_annealing.current_lr
                steps = self.hparams.noam_annealing.n_steps
            else:
                lr = self.hparams.lr_sgd
                steps = -1

            epoch_stats = {"epoch": epoch, "lr": lr, "steps": steps}
            self.hparams.train_logger.log_stats(
                stats_meta=epoch_stats,
                train_stats=self.train_stats,
                valid_stats=stage_stats,
            )
            self.checkpointer.save_and_keep_only(
                meta={"ACC": stage_stats["ACC"], "epoch": epoch},
                max_keys=["ACC"],
                num_to_keep=5,
            )

        elif stage == sb.Stage.TEST:
            self.hparams.train_logger.log_stats(
                stats_meta={"Epoch loaded": self.hparams.epoch_counter.current},
                test_stats=stage_stats,
            )
            with open(self.hparams.wer_file, "w") as w:
                # self.swer_metric.write_stats(w)
                self.wer_metric.write_stats(w)
                self.cer_metric.write_stats(w)

            # save the averaged checkpoint at the end of the evaluation stage
            # delete the rest of the intermediate checkpoints
            # ACC is set to 1.1 so checkpointer
            # only keeps the averaged checkpoint
            self.checkpointer.save_and_keep_only(
                meta={"ACC": 1.1, "epoch": epoch},
                max_keys=["ACC"],
                num_to_keep=1,
            )

    def check_and_reset_optimizer(self):
	
        current_epoch = self.hparams.epoch_counter.current
        if not hasattr(self, "switched"):
            self.switched = False
            if isinstance(self.optimizer, torch.optim.SGD):
                self.switched = True

        if self.switched is True:
            return

        if current_epoch > self.hparams.stage_one_epochs:
            self.optimizer = self.hparams.SGD(self.modules.parameters())

            if self.checkpointer is not None:
                self.checkpointer.add_recoverable("optimizer", self.optimizer)

            self.switched = True

    def on_fit_start(self):
	
        super().on_fit_start()

        # if the model is resumed from stage two, reinitialize the optimizer
        current_epoch = self.hparams.epoch_counter.current
        current_optimizer = self.optimizer
        if current_epoch > self.hparams.stage_one_epochs:
            del self.optimizer
            self.optimizer = self.hparams.SGD(self.modules.parameters())

            # Load latest checkpoint to resume training if interrupted
            if self.checkpointer is not None:

                # do not reload the weights if training is interrupted
                # right before stage 2
                group = current_optimizer.param_groups[0]
                if "momentum" not in group:
                    return

                self.checkpointer.recover_if_possible(
                    device=torch.device(self.device)
                )

    def on_evaluate_start(self, max_key=None, min_key=None):
        super().on_evaluate_start()

        ckpts = self.checkpointer.find_checkpoints(
            max_key=max_key, min_key=min_key
        )
        ckpt = sb.utils.checkpoints.average_checkpoints(
            ckpts, recoverable_name="model", device=self.device
        )

        self.hparams.model.load_state_dict(ckpt, strict=True)
        self.hparams.model.eval()


def dataio_prepare(hparams):
    data_folder = hparams["data_folder"]

    train_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
        csv_path=hparams["train_csv"], replacements={"data_root": data_folder},
    )

    if hparams["sorting"] == "ascending":
        # we sort training data to speed up training and get better results.
        train_data = train_data.filtered_sorted(sort_key="duration")
        # when sorting do not shuffle in dataloader ! otherwise is pointless
        hparams["train_dataloader_opts"]["shuffle"] = False

    elif hparams["sorting"] == "descending":
        train_data = train_data.filtered_sorted(
            sort_key="duration", reverse=True
        )
        # when sorting do not shuffle in dataloader ! otherwise is pointless
        hparams["train_dataloader_opts"]["shuffle"] = False

    elif hparams["sorting"] == "random":
        pass

    else:
        raise NotImplementedError(
            "sorting must be random, ascending or descending"
        )
        
    valid_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
        csv_path=hparams["valid_csv"], replacements={"data_root": data_folder},
    )
    valid_data = valid_data.filtered_sorted(sort_key="duration", reverse=True)

    test_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
        csv_path=hparams["test_csv"], replacements={"data_root": data_folder},
    )
    test_data = test_data.filtered_sorted(sort_key="duration", reverse=True)

    datasets = [train_data, valid_data, test_data]

    # We get the tokenizer as we need it to encode the labels when creating
    # mini-batches.
    tokenizer = hparams["tokenizer"]

    # 2. Define audio pipeline:
    @sb.utils.data_pipeline.takes("wav")
    @sb.utils.data_pipeline.provides("sig")
    def audio_pipeline(wav):
        sig = sb.dataio.dataio.read_audio(wav)
        return sig

    sb.dataio.dataset.add_dynamic_item(datasets, audio_pipeline)

    # 3. Define text pipeline:
    @sb.utils.data_pipeline.takes("wrd")
    @sb.utils.data_pipeline.provides(
        "wrd", "tokens_list", "tokens_bos", "tokens_eos", "tokens"
    )
    def text_pipeline(wrd):
        yield wrd
        tokens_list = tokenizer.encode_as_ids(wrd)
        yield tokens_list
        tokens_bos = torch.LongTensor([hparams["bos_index"]] + (tokens_list))
        yield tokens_bos
        tokens_eos = torch.LongTensor(tokens_list + [hparams["eos_index"]])
        yield tokens_eos
        tokens = torch.LongTensor(tokens_list)
        yield tokens

    sb.dataio.dataset.add_dynamic_item(datasets, text_pipeline)

    # 4. Set output:
    sb.dataio.dataset.set_output_keys(
        datasets, ["id", "sig", "wrd", "tokens_bos", "tokens_eos", "tokens"],
    )
    return train_data, valid_data, test_data, tokenizer


if __name__ == "__main__":
    # CLI:
    hparams_file, run_opts, overrides = sb.parse_arguments(sys.argv[1:])
    print(hparams_file)
    with open(hparams_file) as fin:
        hparams = load_hyperpyyaml(fin, overrides)

    # If distributed_launch=True then
    # create ddp_group with the right communication protocol
    sb.utils.distributed.ddp_init_group(run_opts)

    # 1.  # Dataset prep (parsing KsponSpeech)
    from kdialectspeech_prepare import prepare_kdialectspeech  # noqa

    # Create experiment directory
    sb.create_experiment_directory(
        experiment_directory=hparams["output_folder"],
        hyperparams_to_save=hparams_file,
        overrides=overrides,
    )

    # multi-gpu (ddp) save data preparation
    run_on_main(
        prepare_kdialectspeech,
        kwargs={
            "data_folder": hparams["data_folder"],
            "splited_wav_folder": hparams["splited_wav_folder"],
            "save_folder": hparams["data_folder"],
            "province_code": hparams["province_code"],
            "data_ratio": hparams["data_ratio"],
            "skip_prep": hparams["skip_prep"],
        },
    )

    # here we create the datasets objects as well as tokenization and encoding
    train_data, valid_data, test_data, tokenizer = dataio_prepare(hparams)

    run_on_main(hparams["pretrainer"].collect_files)
    hparams["pretrainer"].load_collected(device=run_opts["device"])

    provice_code = 'kspon'

    pretrained_model_src_dir = '../Inference/pretrained-model-src'
    pretrained_model_save_dir = '../Inference/pretrained-model-save'

    source = os.path.join(pretrained_model_src_dir, provice_code)
    savedir = os.path.join(pretrained_model_save_dir, provice_code)

    pretrained_model = EncoderDecoderASR.from_hparams(
        source=source,
        savedir=savedir,
        run_opts={"device":"cuda"}
    )

    modules = {"CNN": pretrained_model.mods.encoder.cnn, 
            "Transformer": pretrained_model.mods.transformer,
            "decoder": pretrained_model.hparams.decoder,
            "compute_features": pretrained_model.mods.encoder.compute_features, # we use the same features 
            "normalize": pretrained_model.mods.encoder.normalize,
            "seq_lin": pretrained_model.hparams.seq_lin,
            "ctc_lin": pretrained_model.hparams.ctc_lin,
            }

    model = ASR(modules, 
        hparams=hparams, 
        opt_class=hparams["Adam"], 
        checkpointer=hparams["checkpointer"],
        run_opts={"device":"cuda"}
        )

    model.tokenizer = pretrained_model.tokenizer

    # adding objects to trainer:
    # asr_brain.tokenizer = hparams["tokenizer"]

    # Training
    model.fit(
        model.hparams.epoch_counter,
        train_data,
        valid_data,
        train_loader_kwargs=hparams["train_dataloader_opts"],
        valid_loader_kwargs=hparams["valid_dataloader_opts"],
    )

    # Testing
    model.hparams.wer_file = os.path.join(
        hparams["output_folder"], "wer_test.txt"
    )
    model.evaluate(
        test_data,
        max_key="ACC",
        test_loader_kwargs=hparams["test_dataloader_opts"],
    )
```

**Comment by starcell** [comment]
@anautsch 
This error occures when EncoderDecoderASR.from_hparams() tries to link pretrained model files repeatedly.
I want to call this function in run_on_main(). I can't get pretrained model because run_on_main returns None.

**Comment by anautsch** [comment]
Good point.

Ok, so you use `collect_files` in `speechbrain/utils/parameter_transfer.py` directly `class Pretrainer` and in addition the `class Pretrained(torch.nn.Module)` interface. One of them might be too much. We have a confusing class naming scheme in SpeechBrain (Pretrainer vs Pretrained).

---

Regarding Pretrainer - related examples from LibriSpeech
https://github.com/speechbrain/speechbrain/blob/801b1501b0bde2a940fcb71af44b69b07eafb9f5/recipes/LibriSpeech/ASR/CTC/train_with_wav2vec.py#L364
https://github.com/speechbrain/speechbrain/blob/801b1501b0bde2a940fcb71af44b69b07eafb9f5/recipes/LibriSpeech/ASR/CTC/hparams/train_sb_wav2vec.yaml#L180

Yet, your example is using the pretrained interface directly - so - let's walk down that road :)

The pretrainer variant has two steps (from your code):
```python
run_on_main(hparams["pretrainer"].collect_files)
hparams["pretrainer"].load_collected(device=run_opts["device"])
```

The collection of files is handled in `run_on_main` - nothing is returned as you point out correctly. So, they use a second function that looks for the downloaded data, instantiates objects and loads parameters in
https://github.com/speechbrain/speechbrain/blob/801b1501b0bde2a940fcb71af44b69b07eafb9f5/speechbrain/utils/parameter_transfer.py#L236

---

How about this?

At some point, we introduced a `download_only` flag to the pretrained interface
https://github.com/speechbrain/speechbrain/blob/801b1501b0bde2a940fcb71af44b69b07eafb9f5/speechbrain/pretrained/interfaces.py#L360

If the pretrained model is at a different source than the model the pretrainer uses, you could try to call
```python
run_on_main(EncoderDecoderASR.from_hparams(source=source, savedir=savedir, download_only=True))
pretrained_model = EncoderDecoderASR.from_hparams(
    source=source,
    savedir=savedir,
    run_opts={"device":"cuda"}
)
```

Maybe we also need to introduce the `load_collected` function from Pretrainer to the Pretrained class (as it doesn't use symlinks at all). Let's see.

**Comment by starcell** [comment]
I have to train my data first now.
So, I correct fetching.py temporarily as below,
```
        if pathlib.Path(destination).exists():
            run_on_main(_missing_ok_unlink(destination))
        run_on_main(destination.symlink_to(sourcepath))
```
I can run fine-tune-train.py in DDP, but only one GPU is busy.
4 threads are running but only one GPU is busy.

![image](https://user-images.githubusercontent.com/64478170/211359107-c93c433f-2837-438c-8f5a-9c432b21ab6e.png)

**Comment by starcell** [comment]
You are right.
I didn't know about pretrained model well.
I read your comments, and tried to train with pretrained model file.
(I used below code that is in train_with_wav2vec.py 
```
   if "pretrainer" in hparams.keys():
        run_on_main(hparams["pretrainer"].collect_files)
        hparams["pretrainer"].load_collected(asr_brain.device)
```
)
It works.
I didn't modify model architecture now.

I am improving my ASR model performance with my data using pretrained model(trained using KsponSpeech dataset) first, and will try to fine-tune later.

I really appreciate your help and comments, they are very helpful.

I don't know about Speechbrain much yet, but If you need anything that I can help, just tell me.
I will try my best.

I may be helpful on especially Korean language.

Thank you very much.
