### ISSUE TITLE
[Bug]:  speechbrain.utils.depgraph.CircularDependencyError

### ISSUE THREAD

**Issue by fra1993** [speechbrain/speechbrain#1818]
### Describe the bug

When I try tu run asr recipe on my own data I get this error:

`raise CircularDependencyError(
speechbrain.utils.depgraph.CircularDependencyError: 48268a08-5237-4e08-bea3-1837330d2aa4 -> 48268a08-5237-4e08-bea3-1837330d2aa4`

I could not understand the meaning of it. Could you give me some insight? Thanks

### Expected behaviour

training transformer asr with own data and train.py script. Expected to train the model with no errors.

### Relevant log output

```shell
Traceback (most recent call last):
  File "transformer/train.py", line 486, in <module>
    asr_brain.fit(
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/speechbrain/speechbrain/core.py", line 1154, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/speechbrain/speechbrain/core.py", line 1006, in _fit_train
    for batch in t:
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
speechbrain.utils.depgraph.CircularDependencyError: Caught CircularDependencyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/speechbrain/speechbrain/dataio/dataset.py", line 167, in __getitem__
    return self.pipeline.compute_outputs({"id": data_id, **data_point})
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/speechbrain/speechbrain/utils/data_pipeline.py", line 464, in compute_outputs  
    self._prepare_run(data)
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/speechbrain/speechbrain/utils/data_pipeline.py", line 518, in _prepare_run
    self._exec_order = list(
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/speechbrain/speechbrain/utils/depgraph.py", line 245, in get_evaluation_order  
    for ind in toposort(start_ind, []):
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/speechbrain/speechbrain/utils/depgraph.py", line 235, in toposort
    for ind in toposort(to_ind, visited=here):
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/speechbrain/speechbrain/utils/depgraph.py", line 223, in toposort
    raise CircularDependencyError(
speechbrain.utils.depgraph.CircularDependencyError: 48268a08-5237-4e08-bea3-1837330d2aa4 -> 48268a08-5237-4e08-bea3-1837330d2aa4
```

**Comment by AsuMagic** [comment]
Can you show your `data_pipeline.takes`/`provides` definitions? I'm not familiar with this error but I wonder if the circular dependency would be in the provided keys (e.g. function `a` takes key `k0` and provides key `k1`, function `b` takes key `k1` and provides key `k0`).

**Comment by fra1993** [comment]
Hi, thanks for the support. My functions are like this:
`    # 2. Define audio pipeline:
    @sb.utils.data_pipeline.takes("wav")
    @sb.utils.data_pipeline.provides("sig")
    def audio_pipeline(wav):
        sig = sb.dataio.dataio.read_audio(wav)
        return sig
    sb.dataio.dataset.add_dynamic_item(valtest_datasets, audio_pipeline)

    @sb.utils.data_pipeline.takes("wav")
    @sb.utils.data_pipeline.provides("sig")
    def audio_pipeline_train(wav):
        # Speed Perturb is done here so it is multi-threaded with the
        # workers of the dataloader (faster).
        if hparams["speed_perturb"]:
            sig = sb.dataio.dataio.read_audio(wav)
            # factor = np.random.uniform(0.95, 1.05)
            # sig = resample(sig.numpy(), 16000, int(16000*factor))
            speed = sb.processing.speech_augmentation.SpeedPerturb(
                16000, [x for x in range(95, 105)]
            )
            sig = speed(sig.unsqueeze(0)).squeeze(0)  # torch.from_numpy(sig)
        else:
            sig = sb.dataio.dataio.read_audio(wav)
        return sig

    sb.dataio.dataset.add_dynamic_item([train_data], audio_pipeline_train)

    # 3. Define text pipeline:
    @sb.utils.data_pipeline.takes("words")
    @sb.utils.data_pipeline.provides(
        "words", "tokens_list", "tokens_bos", "tokens_eos", "tokens"
    )
    def text_pipeline(wrd):
        yield wrd
        tokens_list = tokenizer.encode_as_ids(wrd)
        yield tokens_list
        tokens_bos = torch.LongTensor([hparams["bos_index"]] + (tokens_list))
        yield tokens_bos
        tokens_eos = torch.LongTensor(tokens_list + [hparams["eos_index"]])
        yield tokens_eos
        tokens = torch.LongTensor(tokens_list)
        yield tokens

    sb.dataio.dataset.add_dynamic_item(datasets, text_pipeline)
`

However, by eliminating the `if root_ind in visited` statement in `speechbrain/utils/depgraph.py` removed the problem and the training runs just fine.

**Comment by anautsch** [comment]
This might not be the solution you want.

How does the yaml file look like?
Is there a mismatch between output units, tokenizer &/or labels to be encoded?
Does the data contain unfamiliar tokens provided in "words"?
Sometimes prepare scripts aim at 40+ tokens but the recipe makes use of some 30+ only.

**Comment by fra1993** [comment]
Well, the data I am using is actually a subset of librispeech therefore tokens and other parameters in the yamel file should work out of the box (the recipe is for librispeech).

**Comment by cassiotbatista** [comment]
Just adding my 10 cents, hope it helps: for me there was a mismatch in text pipeline `takes` decorator and the data JSON fields: decorator looks for keyword "wrd" ([which is the default in librispeech recipe](https://github.com/speechbrain/speechbrain/blob/develop/recipes/LibriSpeech/librispeech_prepare.py#L296)) whereas my custom data files were created with "words, [which is the default in mini_librispeech example](https://github.com/speechbrain/speechbrain/blob/develop/templates/speech_recognition/mini_librispeech_prepare.py#L136).
