### ISSUE TITLE
[Bug]: Multi-GPU support for Librispeech Transformer ASR 

### ISSUE THREAD

**Issue by fra1993** [speechbrain/speechbrain#1819]
### Describe the bug

Hi,

I was trying to train the transformer model on LibriSpeech recipe using multiple GPUS. However, I get a mismatch-dimension error from `data_parallel.py`.

I have the feeling that this depends on the batching and padding operation. 

### Expected behaviour

Merging models output with no error.

### To Reproduce

python train.py transformer.yaml --data_parallel_backend

### Relevant log output

```shell
Traceback (most recent call last):
  File "transformer/train.py", line 486, in <module>
    asr_brain.fit(
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/speechbrain/speechbrain/core.py", line 1154, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/speechbrain/speechbrain/core.py", line 1011, in _fit_train
    loss = self.fit_batch(batch)
  File "transformer/train.py", line 174, in fit_batch
    outputs = self.compute_forward(batch, sb.Stage.TRAIN)
  File "transformer/train.py", line 77, in compute_forward
    enc_out, pred = self.modules.Transformer(
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
AssertionError: Caught AssertionError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/speechbrain/speechbrain/lobes/models/transformer/TransformerASR.py", line 177, in forward
    encoder_out, _ = self.encoder(
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/speechbrain/speechbrain/lobes/models/transformer/Transformer.py", line 477, in forward
    output, attention = enc_layer(
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/speechbrain/speechbrain/lobes/models/transformer/Transformer.py", line 349, in forward
    output, self_attn = self.self_att(
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/speechbrain/speechbrain/nnet/attention.py", line 762, in forward
    output = self.att(
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 1167, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "/fs/scratch/users/francesco_nespoli/SpeechBrain/venv/lib/python3.8/site-packages/torch/nn/functional.py", line 5130, in multi_head_attention_forward
    assert key_padding_mask.shape == (bsz, src_len), \
AssertionError: expecting key_padding_mask shape of (87, 644), but got torch.Size([87, 442])
```

**Comment by Adel-Moumen** [comment]
Hello, 

Please do not use `data_parallel_backend`. This feature is now deprecated and you should use `torch.distributed.launch` instead.

Please take a look at https://speechbrain.readthedocs.io/en/latest/multigpu.html#multi-gpu-training-using-distributed-data-parallel-ddp :-)

**Comment by fra1993** [comment]
Hi, thanks for the answer! Apparently also `torch.distributed.launch` is deprecated. The new correct way of lauching multi-gpu scripts is through `torchrun`

**Comment by Adel-Moumen** [comment]
Hi, 

No don't worry about it. This is the correct way with SpeechBrain to use DDP.

Could you please tell me if now everything is working ? If so, please close the issue. Many thanks! 

Adel :-)

**Comment by fra1993** [comment]
Sure, Looks like working now! Thanks. PS: also `torchrun --nproc_per_node=$GPUS train.py $YAML` works fine, do you see any problem in using it?

**Comment by Adel-Moumen** [comment]
1. If it works as expected then you can continue with it BUT it you face any issues with it... then we might be unable to give you some helps concerning your issue... (so If you can, please use torch.distributed.launch) 
2. The batch size per GPU. :-)
