### ISSUE TITLE
[Bug]: SpeechBrain compatibility issue?

### ISSUE THREAD

**Issue by dioscuroi** [speechbrain/speechbrain#1839]
### Describe the bug

EncoderClassifier works well with CPU but fails with "cuFFT error: CUFFT_INTERNAL_ERROR" if it runs with CUDA. Can you please advise me how to solve the problem? Below is my working environment,

* Python 3.9.13
* Torch 1.13.1+cu117
* CUDA 12.0
* NVIDIA RX 4090
* OS : Ubuntu

### Expected behaviour

I don't know why the classifier works well with CPU but not with GPU...

### To Reproduce

```
from speechbrain.pretrained import EncoderClassifier

  classifier = EncoderClassifier.from_hparams(
      source="speechbrain/spkrec-ecapa-voxceleb",
      run_opts={"device": "cuda"},
  )

  filepath = '... wav filepath ...'

  signal, _ = librosa.load(filepath, sr=16000)
  signal = torch.from_numpy(signal[np.newaxis, :]).cuda()

  embed = classifier.encode_batch(signal)
```

Below is the error 

```
Traceback (most recent call last):
  File "/home/dobby/dobby-canvas/dobby-batch-worker/packages/autovc/speaker_embeddings.py", line 115, in <module>
    embed = classifier.encode_batch(signal)
  File "/home/dobby/git-repos/speechbrain/speechbrain/pretrained/interfaces.py", line 942, in encode_batch
    feats = self.mods.compute_features(wavs)
  File "/home/dobby/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dobby/git-repos/speechbrain/speechbrain/lobes/features.py", line 138, in forward
    STFT = self.compute_STFT(wav)
  File "/home/dobby/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dobby/git-repos/speechbrain/speechbrain/processing/features.py", line 161, in forward
    stft = torch.stft(
  File "/home/dobby/anaconda3/lib/python3.9/site-packages/torch/functional.py", line 632, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR

```

**Comment by Adel-Moumen** [comment]
Hello,

Could you please try with CUDA 11.8? 

Your issue seems related to https://github.com/pytorch/pytorch/issues/88038.

:-)

**Comment by dioscuroi** [comment]
Wow, thank you so much!! You are my hero!!

**Comment by Adel-Moumen** [comment]
Np. 

Let me know if you have any other questions :)
