### ISSUE TITLE
LibriParty/VAD Bug

### ISSUE THREAD

**Issue by haojiepan1** [speechbrain/speechbrain#1871]
### Describe the bug

cd recipes/LibriParty/VAD
python train.py hparams/train.yaml --data_folder=/path/to/LibriParty --musan_folder=/path/to/musan/ --commonlanguage_folder=/path/to/common_voice_kpd

Traceback (most recent call last):
  File "/ai/phj/research/VAD/vad/VAD/train.py", line 278, in <module>
    vad_brain.fit(
  File "/ai/tool/miniconda3/envs/vad/lib/python3.9/site-packages/speechbrain/core.py", line 1153, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/ai/tool/miniconda3/envs/vad/lib/python3.9/site-packages/speechbrain/core.py", line 1009, in _fit_train
    loss = self.fit_batch(batch)
  File "/ai/tool/miniconda3/envs/vad/lib/python3.9/site-packages/speechbrain/core.py", line 881, in fit_batch
    outputs = self.compute_forward(batch, Stage.TRAIN)
  File "/ai/phj/research/VAD/vad/VAD/train.py", line 50, in compute_forward
    wavs, targets, lens = augment_data(
  File "/ai/phj/research/VAD/vad/VAD/data_augment.py", line 334, in augment_data
    wav_samples_noise = get_samples_from_datasets(noise_datasets, wavs)
  File "/ai/phj/research/VAD/vad/VAD/data_augment.py", line 186, in get_samples_from_datasets
    wav_sample = dataset(wav_sample, len_sample)
  File "/ai/tool/miniconda3/envs/vad/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/ai/tool/miniconda3/envs/vad/lib/python3.9/site-packages/speechbrain/lobes/augment.py", line 446, in forward
    waveforms = self.add_noise(waveforms, lengths)
  File "/ai/tool/miniconda3/envs/vad/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/ai/tool/miniconda3/envs/vad/lib/python3.9/site-packages/speechbrain/processing/speech_augmentation.py", line 158, in forward
    noise_waveform, noise_length = self._load_noise(
  File "/ai/tool/miniconda3/envs/vad/lib/python3.9/site-packages/speechbrain/processing/speech_augmentation.py", line 188, in _load_noise
    dataset = ExtendedCSVDataset(
  File "/ai/tool/miniconda3/envs/vad/lib/python3.9/site-packages/speechbrain/dataio/legacy.py", line 92, in __init__
    super().__init__(data, dynamic_items, output_keys)
  File "/ai/tool/miniconda3/envs/vad/lib/python3.9/site-packages/speechbrain/dataio/dataset.py", line 151, in __init__
    static_keys = list(self.data[self.data_ids[0]].keys())
IndexError: list index out of range

### Expected behaviour

The above is the error I encountered when running the VAD script. May I ask how to run it normally！

**Comment by Adel-Moumen** [comment]
Hi @mravanelli, 

Could you please take a look? Thanks :-)

**Comment by elsobhano** [comment]
> Hi @mravanelli,
> 
> Could you please take a look? Thanks :-)

Could you please solve this error?

**Comment by HU-xiaobai** [comment]
hello I meet the same question, have you solved the problem?
