### ISSUE TITLE
[Bug]: IEMOCAP recipe FileNotFoundError

### ISSUE THREAD

**Issue by Janardhan2131** [speechbrain/speechbrain#1878]
### Describe the bug

I am training the wav2vec2 IEMOCAP recipe, but getting error:

**!python train_with_wav2vec2.py hparams/train_with_wav2vec2.yaml --data_folder="/content/drive/MyDrive/IEMOCAP_full_release**

torchvision is not available - cannot save figures
Downloading (…)rocessor_config.json: 100% 159/159 [00:00<00:00, 20.1kB/s]
Traceback (most recent call last):
  File "train_with_wav2vec2.py", line 239, in <module>
    hparams = load_hyperpyyaml(fin, overrides)
  File "/usr/local/lib/python3.8/site-packages/hyperpyyaml/core.py", line 184, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=yaml.Loader)
  File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 107, in construct_object
    for dummy in generator:
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 102, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/usr/local/lib/python3.8/site-packages/hyperpyyaml/core.py", line 464, in _construct_object
    return callable_(*args, **kwargs)
  File "/content/speechbrain/speechbrain/lobes/models/huggingface_wav2vec.py", line 116, in __init__
    self.feature_extractor = Wav2Vec2FeatureExtractor.from_pretrained(
  File "/usr/local/lib/python3.8/site-packages/transformers/feature_extraction_utils.py", line 329, in from_pretrained
    feature_extractor_dict, kwargs = cls.get_feature_extractor_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/transformers/feature_extraction_utils.py", line 452, in get_feature_extractor_dict
    with open(resolved_feature_extractor_file, "r", encoding="utf-8") as reader:
**FileNotFoundError: [Errno 2] No such file or directory: 'results/train_with_wav2vec2/1993/save/wav2vec2_checkpoint/models--facebook--wav2vec2-base/snapshots/0b5b8e868dd84f03fd87d01f9c4ff0f080fecfe8/preprocessor_config.json'**

### Expected behaviour

It should train the wav2vec2 model

### To Reproduce

%cd /content/speechbrain/recipes/IEMOCAP/emotion_recognition

!python train_with_wav2vec2.py hparams/train_with_wav2vec2.yaml --data_folder="/content/drive/MyDrive/IEMOCAP_full_release

**Comment by mravanelli** [comment]
We are aware of it. It looks like this is a bug introduced by Colab that
does not support relative paths anymore. I will go through all the
tutorials soon and change everything to absolute paths.

**Comment by mravanelli** [comment]
Essentially, if you use Colab you should replace

output_folder: !ref results/train_with_wav2vec2/<seed>  with  output_folder:
!ref /content/results/train_with_wav2vec2/<seed> in the yaml file.

Please, let me know if this works.

Best,

Mirco

**Comment by Janardhan2131** [comment]
Yes It works in this way.
But I want to download my results and model which are stored in content directory in colab
As training takes longer time, Runtime may gets disconnected , so all variables will lost and also results as well.

Here instead I want to store my results in drive. I am just specifying location path similar to above.
But getting below error:

**OSError: [Errno 95] Operation not supported: '/content/drive/MyDrive/Speechbrain/results/train_with_wav2vec2/1993/save/wav2vec2_checkpoint/models--facebook--wav2vec2-base/blobs/3f24dc078fcba55ee1d417a413847ead40c093a3' -> '/content/drive/MyDrive/Speechbrain/results/train_with_wav2vec2/1993/save/wav2vec2_checkpoint/models--facebook--wav2vec2-base/snapshots/0b5b8e868dd84f03fd87d01f9c4ff0f080fecfe8/preprocessor_config.json'**

**Comment by AsuMagic** [comment]
Google Colab will not let you create a symlink inside of a Google Drive mount. I'm not sure if this can be worked around at the moment.

A hacky way would be, after each epoch, to copy the newly created checkpoint into Google Drive from Python.

**Comment by Janardhan2131** [comment]
Ok Thank you
