### ISSUE TITLE
[Bug]: multigpu - depriciated

### ISSUE THREAD

**Issue by flckv** [speechbrain/speechbrain#2002]
### Describe the bug

In [documentation about multigpu](https://github.com/speechbrain/speechbrain/blob/8cd2871b6ac3840f0b20ec630efb6743beab617c/docs/multigpu.md?plain=1#L122) 

However, I receive an error message: 

".conda/envs/my_conda_113/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module `torch.distributed.launch is deprecated`
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions"

  warnings.warn(
Traceback (most recent call last):
  File "/home/felicia.kovacs/.conda/envs/vcheckworthy/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/felicia.kovacs/.conda/envs/vcheckworthy/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/felicia.kovacs/.conda/envs/vcheckworthy/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/felicia.kovacs/.conda/envs/vcheckworthy/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/felicia.kovacs/.conda/envs/vcheckworthy/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/felicia.kovacs/.conda/envs/vcheckworthy/lib/python3.9/site-packages/torch/distributed/run.py", line 714, in run
    config, cmd, cmd_args = config_from_args(args)
  File "/home/felicia.kovacs/.conda/envs/vcheckworthy/lib/python3.9/site-packages/torch/distributed/run.py", line 618, in config_from_args
    min_nodes, max_nodes = parse_min_max_nnodes(args.nnodes)
  File "/home/felicia.kovacs/.conda/envs/vcheckworthy/lib/python3.9/site-packages/torch/distributed/run.py", line 556, in parse_min_max_nnodes
    min_nodes = max_nodes = int(arr[0])
ValueError: invalid literal for int() with base 10: ''

### Expected behaviour

at the end I should have a pretrained model on multi node multi gpu on SLURM cluster

### To Reproduce

I am pretraining wav2vec with librispeech following the steps: https://github.com/speechbrain/speechbrain/blob/8cd2871b6ac3840f0b20ec630efb6743beab617c/recipes/LibriSpeech/self-supervised-learning/wav2vec2/README.md#go-

I don't have 16GPUs, my resource set up: 
#SBATCH --job-name=ol            # Job name
#SBATCH --output=/home/flck/output.%A_.txt   # Standard output and error log
#SBATCH --nodes=1                   # Run all processes on a single node   2
#SBATCH --ntasks=4                 # Run on a single CPU   4
#SBATCH --mem=128G                   # Total RAM to be used  128
#SBATCH --cpus-per-task=8          # Number of CPU cores #--cpus-per-task=8  
#SBATCH --gres=gpu:1                # Number of GPUs (per node) #151966: 4
#SBATCH -p gpu                      # Use the gpu partition
#SBATCH --time=12:00:00             # Specify the time needed for your experiment
#SBATCH --qos=gpu-8                 # To enable the use of up to 8 GPUs

LISTNODES=`scontrol show hostname $SLURM_JOB_NODELIST`
MASTER=`echo $LISTNODES | cut -d" " -f1`

# torchrun (new version for distributed learning)
# torch.distributed.launch (old)

python -m torch.distributed.launch --nproc_per_node=4 --nnodes=${2} --node_rank=${SLURM_NODEID} --master_addr=${MASTER} --master_port=5555 /home/felicia.kovacs/speechbrain/recipes/LibriSpeech/self-supervised-learning/wav2vec2/train_sb_wav2vec2.py /home/flck/speechbrain/recipes/LibriSpeech/self-supervised-learning/wav2vec2/hparams/wav2vec2_base.yaml --skip_prep=True --find_unused_parameters --max_grad_norm 0.0 --data_folder=/l/users/flck/peoples_speech_/train/datasets/LibriSpeech/LibriSpeech --train_splits=["train-clean-100"] 
# --distributed_launch
#see : https://speechbrain.readthedocs.io/en/latest/multigpu.html#multi-node-setup-with-slurm

### Versions

- `transformers` version: 4.29.2
- Platform: Linux-5.4.204-ql-generic-12.0-19-x86_64-with-glibc2.31
- Python version: 3.9.7
- Huggingface_hub version: 0.14.1
- Safetensors version: not installed
- PyTorch version (GPU?): 1.11.0 (False)

**Comment by Adel-Moumen** [comment]
Hello, 

Please stay with torch.distributed.launch (see: https://speechbrain.readthedocs.io/en/latest/multigpu.html). We will not upgrade to torch.run until this is stable and that torch.distributed.launch is up in new PyTorch versions. 

Best.
