### ISSUE TITLE
[Bug]: AttributeError: module 'numpy' has no attribute 'typeDict'

### ISSUE THREAD

**Issue by tuanct1997** [speechbrain/speechbrain#2035]
### Describe the bug

Due to the requirements of speechbrain, numpy is >=1.17.0. However, I think from 1.21.0 and above, `np.typeDict is a deprecated alias for np.sctypeDict and has been so for over 14 years` but still can work up to 1.23.0. 

This error will happen directly when try to `import speechbrain` at the beginning. 
I suggest to add requirements as `1.17.0 <= numpy <= 1.23.0`

### Expected behaviour

`AttributeError: module 'numpy' has no attribute 'typeDict'`

### To Reproduce

```python
import speechbrain as sb
```

### Relevant log output

Sb: 0.5.14
Numpy: 1.24.0

**Comment by AsuMagic** [comment]
Can you provide a backtrace for the error? I can't seem to find a reference to `typeDict` in SB as of the current `develop` or as of `0.5.14`.

**Comment by tuanct1997** [comment]
Hi, 

after look at the log, I think the problem comes from scipy. I have the scipy version 1.4.1. 

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/__init__.py", line 4, in <module>
    from .core import Stage, Brain, create_experiment_directory, parse_arguments
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/core.py", line 36, in <module>
    from speechbrain.utils.distributed import run_on_main
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/utils/__init__.py", line 11, in <module>
    from . import *  # noqa
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/utils/bleu.py", line 7, in <module>
    from speechbrain.utils.metric_stats import MetricStats
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/utils/metric_stats.py", line 15, in <module>
    from speechbrain.dataio.dataio import (
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/dataio/__init__.py", line 11, in <module>
    from . import *  # noqa
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/dataio/preprocess.py", line 4, in <module>
    from speechbrain.processing.speech_augmentation import Resample
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/processing/speech_augmentation.py", line 20, in <module>
    from speechbrain.dataio.dataloader import make_dataloader
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/dataio/dataloader.py", line 45, in <module>
    from speechbrain.dataio.sampler import ReproducibleRandomSampler
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/dataio/sampler.py", line 25, in <module>
    from scipy.stats import lognorm
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/scipy/stats/__init__.py", line 384, in <module>
    from .stats import *
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/scipy/stats/stats.py", line 179, in <module>
    from scipy.spatial.distance import cdist
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/scipy/spatial/__init__.py", line 97, in <module>
    from .kdtree import *
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/scipy/spatial/kdtree.py", line 8, in <module>
    import scipy.sparse
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .base import *
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/scipy/sparse/base.py", line 8, in <module>
    from .sputils import (isdense, isscalarlike, isintlike,
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/scipy/sparse/sputils.py", line 17, in <module>
    supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/scipy/sparse/sputils.py", line 17, in <listcomp>
    supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typeDict'`

However, if I re-install scipy version again (same 1.4.1) it works. So I suppose the scipy has update all the variable for all version.

**Comment by tuanct1997** [comment]
Hi @AsuMagic , 
after check the log. The problem was caused by scipy version. I have scipy==1.4.1 (minimum version for sb's requirements). 

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/__init__.py", line 4, in <module>
    from .core import Stage, Brain, create_experiment_directory, parse_arguments
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/core.py", line 36, in <module>
    from speechbrain.utils.distributed import run_on_main
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/utils/__init__.py", line 11, in <module>
    from . import *  # noqa
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/utils/bleu.py", line 7, in <module>
    from speechbrain.utils.metric_stats import MetricStats
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/utils/metric_stats.py", line 15, in <module>
    from speechbrain.dataio.dataio import (
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/dataio/__init__.py", line 11, in <module>
    from . import *  # noqa
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/dataio/preprocess.py", line 4, in <module>
    from speechbrain.processing.speech_augmentation import Resample
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/processing/speech_augmentation.py", line 20, in <module>
    from speechbrain.dataio.dataloader import make_dataloader
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/dataio/dataloader.py", line 45, in <module>
    from speechbrain.dataio.sampler import ReproducibleRandomSampler
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/speechbrain/dataio/sampler.py", line 25, in <module>
    from scipy.stats import lognorm
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/scipy/stats/__init__.py", line 384, in <module>
    from .stats import *
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/scipy/stats/stats.py", line 179, in <module>
    from scipy.spatial.distance import cdist
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/scipy/spatial/__init__.py", line 97, in <module>
    from .kdtree import *
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/scipy/spatial/kdtree.py", line 8, in <module>
    import scipy.sparse
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .base import *
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/scipy/sparse/base.py", line 8, in <module>
    from .sputils import (isdense, isscalarlike, isintlike,
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/scipy/sparse/sputils.py", line 17, in <module>
    supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/scipy/sparse/sputils.py", line 17, in <listcomp>
    supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
  File "/users/tnguyen/miniconda3/envs/newenv/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typeDict'`

I have checked scipy version and test. So I would like to suggest update the requirement for scipy to `scipy>=1.5.1`. From 1.5.0 and before, there will be a problem with new numpy.

**Comment by Adel-Moumen** [comment]
Hello @tuanct1997, 

Thanks for opening this issue. Could you please open a PR and propose a fix? I tried and indeed there's an issue with numpy versions. 

Thanks! 

Adel

**Comment by tuanct1997** [comment]
Hi @Adel-Moumen ,

I haven't have the time yet to test my solution. But I think the easiest solution could be fixed the version of `numpy <= 1.23.0`. I will make a PR if I found an alternative solution asap if at that time there is no proposal yet.

Thank you for your understanding.

Tuan

**Comment by Adel-Moumen** [comment]
hmmmm I'm unable to reproduce the issue it seems... could you please double check ? 

https://colab.research.google.com/drive/1rtmXpXIr_HCpm7Uks6Z15XY-AUC85v99?usp=sharing

**Comment by tuanct1997** [comment]
I found out the problem here. It's quite easy fix. The problem was caused by huggingface_hub library. We could fix it by set the requirements from `huggingface_hub >= 0.7.0` to` huggingface_hub >= 0.8.0`
