### ISSUE TITLE
[Bug]: failed receipes test for LibriSpeech train_hf_whisper.yaml

### ISSUE THREAD

**Issue by bd793fcb** [speechbrain/speechbrain#2036]
### Describe the bug

the receipes test for train_hf_whisper.yml does not pass

### Expected behaviour

the checked in test should pass

### To Reproduce

```python
python -c 'from tests.utils.recipe_tests import run_recipe_tests; print("TEST FAILED!") if not(run_recipe_tests(filters_fields=["Hparam_file"], filters=[["recipes/LibriSpeech/ASR/transformer/hparams/train_hf_whisper.yaml"]], do_checks=False, run_opts="--device=cuda")) else print("TEST PASSED")'
```

### Versions

71536a8001061c580c43d547450073080fa7d843

### Relevant log output

```shell
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: tests/tmp/LibriSpeech_row_31
speechbrain.core - Info: auto_mix_prec arg from hparam file is used
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - 37.8M trainable parameters in ASR
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
speechbrain.utils.epoch_loop - Going into epoch 1
speechbrain.core - Exception:
Traceback (most recent call last):
  File "~/speechbrain/recipes/LibriSpeech/ASR/transformer/train_with_whisper.py", line 316, in <module>
    asr_brain.fit(
  File "~/speechbrain/speechbrain/core.py", line 1252, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "~/speechbrain/speechbrain/core.py", line 1105, in _fit_train
    loss = self.fit_batch(batch)
  File "~/speechbrain/speechbrain/core.py", line 973, in fit_batch
    outputs = self.compute_forward(batch, Stage.TRAIN)
  File "~/speechbrain/recipes/LibriSpeech/ASR/transformer/train_with_whisper.py", line 53, in compute_forward
    enc_out, logits, _ = self.modules.whisper(wavs, bos_tokens)
  File "~/miniconda3/envs/ml/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "~/speechbrain/speechbrain/lobes/models/huggingface_whisper.py", line 166, in forward
    out_encoder = self.forward_encoder(wav)
  File "~/speechbrain/speechbrain/lobes/models/huggingface_whisper.py", line 189, in forward_encoder
    return self._get_encoder_states(wav)
  File "~/speechbrain/speechbrain/lobes/models/huggingface_whisper.py", line 200, in _get_encoder_states
    mel = self._get_mel(wav)
  File "~/speechbrain/speechbrain/lobes/models/huggingface_whisper.py", line 217, in _get_mel
    mels = self._log_mel_spectrogram(mels)
  File "~/speechbrain/speechbrain/lobes/models/huggingface_whisper.py", line 249, in _log_mel_spectrogram
    mel_spec = filters @ magnitudes
RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [2, 80] but got: [2, 201].
```

### Additional context

the shape for filters & magnitudes:
torch.Size([201, 80])
torch.Size([2, 201, 3000])

**Comment by Adel-Moumen** [comment]
Hello,

Please downgrade your transformer version. The issue is coming from this external toolkit and we are currently working on this. 

Best.

**Comment by Adel-Moumen** [comment]
Hello,

Please run: `pip install transformers==4.26.0`

Best.
