### ISSUE TITLE
convert "AISHELL-1/ASR/transformer" to onnx or nvidia tensorRT engine

### ISSUE THREAD

**Issue by Corcoy** [speechbrain/speechbrain#2078]
### Describe the bug

I got this failed attempt to convert "AISHELL-1/ASR/transformer" to ONNX:
![image](https://github.com/speechbrain/speechbrain/assets/125660628/f56ebb72-6f7c-4638-9f83-19ff5582cace)
My code example：

`asr_model= EncoderDecoderASR.from_hparams(source="speechbrain/asr-wav2vec2-transformer-aishell", ` `savedir="pretrained_models/asr-transformer-aishell")`
`asr_model.eval()`
`wavs = torch.rand(1,34492)`
`wav_lens = torch.ones(1)`
`scores = asr_model.forward(wavs, wav_lens)`
`input1 = torch.rand(1,34492)`
`input2 = torch.ones(1)`
`torch.onnx.export(asr_model,(input1,input2),'./onnx/speech_transformer.onnx', verbose=True,opset_version=15)`

### Expected behaviour

I need an onnx file that can run under onnx runtime.best can convert it to TensorRT engine file

**Comment by Corcoy** [comment]
Is there any way to solove it?I need to deploy this model with tensorRT.

**Comment by AsuMagic** [comment]
Looking at the [ONNX changelog](https://github.com/onnx/onnx/releases) it seems that the STFT operator was implemented in version `17`.  
As to whether `torch.onnx` supports that, I don't know, and I don't have more personal experience to help, sadly. But you may first want to update torch and other dependencies to the latest version if that is not the case already.

**Comment by AsuMagic** [comment]
Coincidentally I was reading another issue and read that PyTorch does not support these version 17 operators. See: https://github.com/speechbrain/speechbrain/discussions/2019#discussioncomment-6163398

**Comment by mitchelldehaven** [comment]
STFT is onnx exportable, you just need `return_complex=False` in the torch.stft definition (as onnx supports STFT, but not with complex values).

**Comment by Corcoy** [comment]
> STFT is onnx exportable, you just need `return_complex=False` in the torch.stft definition (as onnx supports STFT, but not with complex values).
thank you.I will give it a try

**Comment by mitchelldehaven** [comment]
> Using the following repro:
> 
> ```python
> from speechbrain.pretrained import EncoderDecoderASR
> import torch
> 
> asr_model= EncoderDecoderASR.from_hparams(source="speechbrain/asr-wav2vec2-transformer-aishell", savedir="pretrained_models/asr-transformer-aishell")
> asr_model.eval()
> wavs = torch.rand(1,34492)
> wav_lens = torch.ones(1)
> scores = asr_model.forward(wavs, wav_lens)
> input1 = torch.rand(1,34492)
> input2 = torch.ones(1)
> torch.onnx.export(asr_model,(input1,input2),'./onnx/speech_transformer.onnx', verbose=True)
> ```
> 
> and PyTorch 2.1.1, I get a bunch of warnings and a different error:
> 
> ```
> Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-large-100k-voxpopuli and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0']
> You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
> speechbrain.lobes.models.huggingface_wav2vec - wav2vec 2.0 is frozen.
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/transformers/models/wav2vec2/modeling_wav2vec2.py:592: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   if attn_weights.size() != (bsz * self.num_heads, tgt_len, src_len):
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/transformers/models/wav2vec2/modeling_wav2vec2.py:631: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   if attn_output.size() != (bsz * self.num_heads, tgt_len, self.head_dim):
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/dataio/dataio.py:791: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   max_len = length.max().long().item()  # using arange to generate mask
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/dataio/dataio.py:794: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
>   ).expand(len(length), max_len) < length.unsqueeze(1)
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/dataio/dataio.py:802: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
>   mask = torch.as_tensor(mask, dtype=dtype, device=device)
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/decoders/seq2seq.py:751: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   min_decode_steps = int(enc_states.shape[1] * self.min_decode_ratio)
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/decoders/seq2seq.py:752: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   max_decode_steps = int(enc_states.shape[1] * self.max_decode_ratio)
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/decoders/ctc.py:100: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   last_char = [gi[-1] for gi in g] if prefix_length > 0 else [0] * len(g)
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/decoders/ctc.py:100: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
>   last_char = [gi[-1] for gi in g] if prefix_length > 0 else [0] * len(g)
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/decoders/ctc.py:173: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   if prefix_length == 0:
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/decoders/ctc.py:192: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   start = max(1, prefix_length)
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/decoders/seq2seq.py:619: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   if eos_indices.shape[0] > 0:
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/decoders/seq2seq.py:620: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
>   for index in eos_indices:
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/decoders/seq2seq.py:622: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   index = index.item()
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/decoders/ctc.py:100: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
>   last_char = [gi[-1] for gi in g] if prefix_length > 0 else [0] * len(g)
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/decoders/seq2seq.py:666: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
>   top_lengths += [len(hyp) for hyp in hyps]
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/decoders/seq2seq.py:671: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
>   top_lengths = torch.tensor(
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/decoders/seq2seq.py:684: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
>   topk_log_probs = [top_log_probs[index.item()] for index in indices]
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/decoders/seq2seq.py:684: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   topk_log_probs = [top_log_probs[index.item()] for index in indices]
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/decoders/seq2seq.py:1566: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
>   for p in prediction:
> /home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/speechbrain/decoders/seq2seq.py:1567: TracerWarning: Converting a tensor to a Python list might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   res = filter_seq2seq_output(p.tolist(), eos_id=eos_id)
> Traceback (most recent call last):
>   File "/home/sdelang/projects/src/python/sbnb/issue-2078.py", line 11, in <module>
>     torch.onnx.export(asr_model,(input1,input2),'./onnx/speech_transformer.onnx', verbose=True)
>   File "/home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/torch/onnx/utils.py", line 516, in export
>     _export(
>   File "/home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/torch/onnx/utils.py", line 1596, in _export
>     graph, params_dict, torch_out = _model_to_graph(
>                                     ^^^^^^^^^^^^^^^^
>   File "/home/sdelang/pyenv/pytorch-cpu-stable/lib/python3.11/site-packages/torch/onnx/utils.py", line 1182, in _model_to_graph
>     _C._jit_pass_onnx_assign_output_shape(
> RuntimeError: ArrayRef: invalid index Index = 0; Length = 0
> ```
> 
> The warnings are a potential concern to actually properly port the model to ONNX, but I am not sure what the error here is actually due to. The only match for that exact error on google is this PyTorch issue [pytorch/pytorch#39762](https://github.com/pytorch/pytorch/issues/39762), but the fix for it got merged long ago. It also doesn't seem to give context as to what source code in the model has caused the issue, so that might be fun to debug.
> 
> I am not sure if this means the `stft` error does not occur or if I'm having a new issue that occurs earlier.
> 
> Either way, I think it would need someone to do a few significant changes to the model for it to work.

I think your running into something else. I don't think Wav2vec uses STFT (since it operates on the raw waveform).

**Comment by asumagic** [comment]
That's true, but OP had the error regardless. I imagine something about augmentation may have been involving a STFT (even if it's always gated behind a stage == train check), but I can't find it at a glance. Not going to worry about it too much for now.
