### ISSUE TITLE
IndexError: Out of range: piece id is out of range

### ISSUE THREAD

**Issue by solene-evain** [speechbrain/speechbrain#2106]
### Describe the bug

```
100%|██████████| 41428/41428 [02:08<00:00,  2.17it/s, train_loss=1.56]
  1%|          | 62/11456 [00:56<1:56:25,  1.63it/s]Traceback (most recent call last):
  File "/gpfsssd/scratch/rech/rdl/ucu46wr/LREC/ALLSPONTANEOUS/SB_train_with_wav2vec.py", line 403, in <module>
    asr_brain.fit(
  File "/linkhome/rech/genlig01/ucu46wr/.local/lib/python3.10/site-packages/speechbrain/core.py", line 1265, in fit
    self._fit_valid(valid_set=valid_set, epoch=epoch, enable=enable)
  File "/linkhome/rech/genlig01/ucu46wr/.local/lib/python3.10/site-packages/speechbrain/core.py", line 1168, in _fit_valid
    loss = self.evaluate_batch(batch, stage=Stage.VALID)
  File "/gpfsssd/scratch/rech/rdl/ucu46wr/LREC/ALLSPONTANEOUS/SB_train_with_wav2vec.py", line 144, in evaluate_batch
    loss = self.compute_objectives(predictions, batch, stage=stage)
  File "/gpfsssd/scratch/rech/rdl/ucu46wr/LREC/ALLSPONTANEOUS/SB_train_with_wav2vec.py", line 79, in compute_objectives
    predicted_words = self.tokenizer(sequence, task="decode_from_list")
  File "/linkhome/rech/genlig01/ucu46wr/.local/lib/python3.10/site-packages/speechbrain/tokenizers/SentencePiece.py", line 455, in __call__
    return [self.sp.decode_ids(utt_seq).split(" ") for utt_seq in batch]
  File "/linkhome/rech/genlig01/ucu46wr/.local/lib/python3.10/site-packages/speechbrain/tokenizers/SentencePiece.py", line 455, in <listcomp>
    return [self.sp.decode_ids(utt_seq).split(" ") for utt_seq in batch]
  File "/linkhome/rech/genlig01/ucu46wr/.conda/envs/SB15/lib/python3.10/site-packages/sentencepiece/__init__.py", line 837, in DecodeIds
    return self.Decode(input=input, out_type=out_type, **kwargs)
  File "/linkhome/rech/genlig01/ucu46wr/.conda/envs/SB15/lib/python3.10/site-packages/sentencepiece/__init__.py", line 780, in Decode
    return self._DecodeIds(input)
  File "/linkhome/rech/genlig01/ucu46wr/.conda/envs/SB15/lib/python3.10/site-packages/sentencepiece/__init__.py", line 337, in _DecodeIds
    return _sentencepiece.SentencePieceProcessor__DecodeIds(self, ids)
IndexError: Out of range: piece id is out of range.

```
Cette erreur m'arrive à la 7e époque... 
J'ai pu trouver une erreur similaire ici: #2032 et j'ai bien regardé, la taille de mon vocab et de neurones en sortie est bien la même: 76

J'utilise la recette CommonVoice/ASR/CTC, sur mes propres données.

### Expected behaviour

Une erreur dans mes données devrait remonter dès la 1e époque, non? 

### To Reproduce

[CV_yaml.txt](https://github.com/speechbrain/speechbrain/files/12289288/CV_yaml.txt)

### Versions

Dernière version de SB: 0.5.15

**Comment by Adel-Moumen** [comment]
Hello @solene-evain, 

Without access to your data it will be hard for me to reproduce your issue. 

Usually, this error come from a mismatch between the output neuron's of your Acoustic Model and the vocabulary size. 

To debug this the only solution is to put some loggers everywhere after your ctc_lin until you raise the issue.

**Comment by Adel-Moumen** [comment]
Hello @solene-evain, 

How are you? Do you have any news to share please? Thanks. 

Adel

**Comment by Adel-Moumen** [comment]
Hello @solene-evain, 

Thanks for the "good" news. 

One side note: I am working on #2010 which should add some stability in training. It mainly targets fp16 / bf16 but should also apply a bit on fp32. Maybe at some point you'd like to try this. This is not ready yet to be merged, but you can have a look if you'd like. 

What should we do with this issue? Do you think we should close it?

Thanks again. 

Best, 
Adel

**Comment by solene-evain** [comment]
Yes, this one should be closed. Other problems are not related.
I'm gonna check the issue you mentioned. 

Thanks!

Solène
