### ISSUE TITLE
unable to run pytest tests

### ISSUE THREAD

**Issue by clonesangram87** [speechbrain/speechbrain#2131]
### Describe the bug

while running the below mentioned command received error.

PS C:\Users\Asus\Speech_Recognition_System\speechbrain> pytest tests
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Scripts\pytest.exe\__main__.py", line 7, in <module>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\config\__init__.py", line 105, in main
    config = _prepareconfig(args, plugins)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\config\__init__.py", line 257, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
                                                         ^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\helpconfig.py", line 90, in pytest_cmdline_parse
    config = outcome.get_result()
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\config\__init__.py", line 836, in pytest_cmdline_parse
    self.parse(args)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\config\__init__.py", line 1044, in parse
    self._preparse(args, addopts=addopts)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\config\__init__.py", line 992, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\pluggy\manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
             ^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\importlib\metadata\__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\assertion\rewrite.py", line 143, in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\assertion\rewrite.py", line 330, in _rewrite_test
    co = compile(tree, fn, "exec", dont_inherit=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: required field "lineno" missing from alias

### Expected behaviour

command executed successfully

### To Reproduce

pytest tests

**Comment by pplantinga** [comment]
A similar error to this was due to outdated pytest version. `lint-requirements.txt` has been updated, try the newer version of file or just try manually upgrading pytest.

**Comment by Adel-Moumen** [comment]
Hey @clonesangram87, any news please? Thanks.

**Comment by Adel-Moumen** [comment]
Hello, 

It's been quite some time without any updates or news on this issue. Consequently, I'm taking the step to close it. Feel free to reopen it if you are still facing the issue. 

Best,
Adel
