### ISSUE TITLE
Indexing error with DynamicBatchSampling

### ISSUE THREAD

**Issue by Deathekirl** [speechbrain/speechbrain#2235]
### Describe the bug

When I try to use DynamicBatchSampler, it fails with the error:
`TypeError: list indices must be integers or slices, not list`

### Expected behaviour

No error.

### To Reproduce

Here is a minimal example:

https://colab.research.google.com/drive/1OPKTvQpLkhIcn75Ny7TihPHlbfHiQMT1?usp=sharing

I include this simple CSV file that you can quickly import on colab, but the bug should happen with any file.
[train.csv](https://github.com/speechbrain/speechbrain/files/13299380/train.csv)

### Environment Details

I encountered the bug while using SpeechBrain 0.5.14. Upgrading to 0.5.15 did not solve the problem. I tried using the development version (i.e. I runned `pip install git+https://github.com/speechbrain/speechbrain.git@develop`) but it didn't seem to help either.

Torch: 1.12.1. Upgrading to torch 2.1 didn't help

### Relevant Log Output

```shell
[...]
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
speechbrain.utils.epoch_loop - Going into epoch 1
speechbrain.dataio.sampler - DynamicBatchSampler: Generating dynamic batches
speechbrain.core - Exception:
Traceback (most recent call last):
  File "/users/lmaison/experiment_capacity/5.quebec_learning/slurm/../src/train_dynamic_batching.py", line 383, in <module>
    asr_brain.fit(
  File "/users/lmaison/.conda/envs/sb_lucas/lib/python3.9/site-packages/speechbrain/core.py", line 1225, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/users/lmaison/.conda/envs/sb_lucas/lib/python3.9/site-packages/speechbrain/core.py", line 1073, in _fit_train
    for batch in t:
  File "/users/lmaison/.conda/envs/sb_lucas/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/users/lmaison/.conda/envs/sb_lucas/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/users/lmaison/.conda/envs/sb_lucas/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/users/lmaison/.conda/envs/sb_lucas/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/users/lmaison/.conda/envs/sb_lucas/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/users/lmaison/.conda/envs/sb_lucas/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/users/lmaison/.conda/envs/sb_lucas/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/users/lmaison/.conda/envs/sb_lucas/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/users/lmaison/.conda/envs/sb_lucas/lib/python3.9/site-packages/speechbrain/dataio/dataset.py", line 163, in __getitem__
    data_id = self.data_ids[index]
TypeError: list indices must be integers or slices, not list
```

### Additional Context

This is my first time trying to use DynamicBatchSampler.
I followed the tutorial first, then tried to use it in a real-world example. That's when I encountered the error.

I simplified the script in the minimal example as much as possible to try to isolate the error.

**Comment by TParcollet** [comment]
I can reproduce the bug, but I don't really get why torch is not reporting a proper integer in that case. @Adel-Moumen any idea?

**Comment by Deathekirl** [comment]
I found the mistake here. I wrote
`dataloader = sb.dataio.dataloader.make_dataloader(train_data, sampler=sampler)`

instead of
`dataloader = sb.dataio.dataloader.make_dataloader(train_data, batch_sampler=sampler)`

I'm closing the issue since this is not related to Speechbrain.
