### ISSUE TITLE
Something went wrong while I was training

### ISSUE THREAD

**Issue by kevin00616** [speechbrain/speechbrain#2239]
### Describe the bug

I am training ECAPA-TDNN. The data set I use is voxceleb1, but I have added some of my voice data into it. 
I am not sure if what I am doing is correct, so I want to ask if there is any teaching.

In addition, I would like to ask what happened in the following content?

### Expected behaviour

I can train normally

### Relevant Log Output

```shell
(speechbrain) kalvin00616@DGX-Station:~/Desktop/speechbrain/recipes/VoxCeleb/SpeakerRec$ python -m torch.distributed.launch train_speaker_embeddings.py hparams/train_ecapa_tdnn.yaml --distributed_launch
/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
/home/kalvin00616/Desktop/speechbrain/data/voxceleb1/rirs_noises.zip exists. Skipping download
/home/kalvin00616/Desktop/speechbrain/data/voxceleb1/rirs_noises.zip exists. Skipping download
/home/kalvin00616/Desktop/speechbrain/data/voxceleb1/rirs_noises.zip exists. Skipping download
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: /home/kalvin00616/Desktop/speechbrain/recipes/VoxCeleb/SpeakerRec/results/1986
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - The --ckpt_interval_minutes option saves only on the main process to avoid race conditions. If you need to save an intra-epoch checkpoint on multiple processes (e.g. FSDP), consider switching to intervals based on # of steps with the argument --ckpt_interval_steps.
speechbrain.core - 22.2M trainable parameters in SpeakerBrain
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
speechbrain.utils.epoch_loop - Going into epoch 1
  0%|                                                                                                                                                                       | 0/32768 [00:00<?, ?it/s]/home/kalvin00616/Desktop/speechbrain/speechbrain/dataio/encoder.py:723: UserWarning: CategoricalEncoder.expect_len was never called: assuming category count of 7206 to be correct! Sanity check your encoder using `.expect_len`. Ensure that downstream code also uses the correct size. If you are sure this does not apply to you, use `.ignore_len`.
  f"{self.__class__.__name__}.expect_len was never called: "
/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/autograd/__init__.py:175: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [192, 6144, 1], strides() = [6144, 1, 6144]
bucket_view.sizes() = [192, 6144, 1], strides() = [6144, 1, 1] (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484809535/work/torch/csrc/distributed/c10d/reducer.cpp:312.)
  allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
torch.nn.parallel.distributed - Reducer buckets have been rebuilt in this iteration.                                                                                                                  
torch.nn.parallel.distributed - Reducer buckets have been rebuilt in this iteration.                                                                                                                  
  5%|██████▌                                                                                                                                 | 1596/32768 [58:50<19:09:23,  2.21s/it, train_loss=15.5]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train_speaker_embeddings.py", line 257, in <module>
    valid_loader_kwargs=hparams["dataloader_options"],
  File "/home/kalvin00616/Desktop/speechbrain/speechbrain/core.py", line 1385, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/kalvin00616/Desktop/speechbrain/speechbrain/core.py", line 1219, in _fit_train
    for batch in t:
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/kalvin00616/Desktop/speechbrain/speechbrain/dataio/batch.py", line 125, in __init__
    padded = PaddedData(*padding_func(values, **padding_kwargs))
  File "/home/kalvin00616/Desktop/speechbrain/speechbrain/utils/data_utils.py", line 456, in batch_pad_right
    raise IndexError("All tensors must have same number of dimensions")
IndexError: All tensors must have same number of dimensions
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2813342) of binary: /home/kalvin00616/anaconda3/envs/speechbrain/bin/python
Traceback (most recent call last):
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/run.py", line 755, in run
    )(*cmd_args)
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```

**Comment by TParcollet** [comment]
Hi, "https://github.com/keras-team/tf-keras/issues/124" This error tells you that something arriving to the padding has different dimensions. To debug that problem, have a look at the audio_pipeline and text_pipeline function and print the shape of the tensors that you are returning (these tensor then go into this padding function). It is most likely that you have an issue with mono / stereo channel in your audio :-)

**Comment by kevin00616** [comment]
Thank you for your reminder. 
I checked my audio file later and found that there was indeed a problem. 
After the correction, it can run.

**Comment by arrrrr3186** [comment]
> Hi, "IndexError: All tensors must have same number of dimensions" This error tells you that something arriving to the padding has different dimensions. To debug that problem, have a look at the audio_pipeline and text_pipeline function and print the shape of the tensors that you are returning (these tensor then go into this padding function). It is most likely that you have an issue with mono / stereo channel in your audio :-)

Thanks, it worked
