### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered on own data + voxceleb1 data set for training

### ISSUE THREAD

**Issue by kevin00616** [speechbrain/speechbrain#2248]
### Describe the bug

As in the title, I am using my own data + voxceleb1 data set for training,
But I got some problem,I have corrected my audio file and converted it all into single-track format data.
But it still encountered the issue described below, and I'm not sure what happened. Please help me.

### Expected behaviour

Training can proceed normally.

### Relevant Log Output

```shell
kalvin00616/Desktop/speechbrain/speechbrain/dataio/encoder.py:723: UserWarning: CategoricalEncoder.expect_len was never called: assuming category count of 7206 to be correct! Sanity check your encoder using `.expect_len`. Ensure that downstream code also uses the correct size. If you are sure this does not apply to you, use `.ignore_len`.
  f"{self.__class__.__name__}.expect_len was never called: "
/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/autograd/__init__.py:175: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [192, 6144, 1], strides() = [6144, 1, 6144]
bucket_view.sizes() = [192, 6144, 1], strides() = [6144, 1, 1] (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484809535/work/torch/csrc/distributed/c10d/reducer.cpp:312.)
  allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
torch.nn.parallel.distributed - Reducer buckets have been rebuilt in this iteration.                                                                                                                  
torch.nn.parallel.distributed - Reducer buckets have been rebuilt in this iteration.                                                                                                                  
  5%|██████▌                                                                                                                                 | 1596/32768 [31:13<10:09:40,  1.17s/it, train_loss=15.5]/opt/conda/conda-bld/pytorch_1659484809535/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [29,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1659484809535/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [61,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1659484809535/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [93,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1659484809535/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [125,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
  5%|██████▌                                                                                                                                 | 1596/32768 [31:13<10:10:00,  1.17s/it, train_loss=15.5]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train_speaker_embeddings.py", line 257, in <module>
    valid_loader_kwargs=hparams["dataloader_options"],
  File "/home/kalvin00616/Desktop/speechbrain/speechbrain/core.py", line 1385, in fit
    self._fit_train(train_set=train_set, epoch=epoch, enable=enable)
  File "/home/kalvin00616/Desktop/speechbrain/speechbrain/core.py", line 1225, in _fit_train
    loss = self.fit_batch(batch)
  File "/home/kalvin00616/Desktop/speechbrain/speechbrain/core.py", line 1091, in fit_batch
    if self.check_gradients(loss):
  File "/home/kalvin00616/Desktop/speechbrain/speechbrain/core.py", line 1139, in check_gradients
    if not torch.isfinite(loss):
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[W CUDAGuardImpl.h:113] Warning: CUDA warning: device-side assert triggered (function destroyEvent)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 249477) of binary: /home/kalvin00616/anaconda3/envs/speechbrain/bin/python
Traceback (most recent call last):
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/run.py", line 755, in run
    )(*cmd_args)
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kalvin00616/anaconda3/envs/speechbrain/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
train_speaker_embeddings.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-15_10:28:19
  host      : DGX-Station
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 249477)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 249477
=======================================================
```

**Comment by Adel-Moumen** [comment]
Hello @kevin00616,

Are you still facing this problem? I think one way to debug this problem is to use `--device=cpu` until getting the error. This way you will get a more informative error... 

Best.

**Comment by asumagic** [comment]
Closed since inactive and I agree with @Adel-Moumen, this is likely a bug from the custom recipe, likely due to some vocabulary mismatch (judging from the failing scatter-gather kernel). The CPU mode and the provided CUDA debug mode is likely to be helpful identifying the root cause in those cases. Can be reopened if this is arguably a recipe bug that someone else can confirm.
