### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zqiu30** [speechbrain/speechbrain#2286]
### Describe the bug

code:
```
!python train_speaker_embeddings.py hparams/train_x_vectors.yaml --data_folder= /content/speechbrain/recipes/VoxCeleb/SpeakerRec/your_data_folder/RIRS_NOISES/pointsource_noises --number_of_epochs=15 --device='cpu'
```

error:
```
Downloading https://www.dropbox.com/scl/fi/a5zg4588mefxzq2cleuux/RIRS_NOISES.zip?rlkey=01ymylca0an1nc7tlpdt2bjif&dl=1 to /content/speechbrain/recipes/VoxCeleb/SpeakerRec/your_data_folder/RIRS_NOISES/pointsource_noises/rirs_noises.zip
RIRS_NOISES.zip?rlkey=01ymylca0an1nc7tlpdt2bjif&dl=1: 816MB [00:12, 64.0MB/s]              
Extracting /content/speechbrain/recipes/VoxCeleb/SpeakerRec/your_data_folder/RIRS_NOISES/pointsource_noises/rirs_noises.zip to /content/speechbrain/recipes/VoxCeleb/SpeakerRec/your_data_folder/RIRS_NOISES/pointsource_noises
/content/speechbrain/recipes/VoxCeleb/SpeakerRec/your_data_folder/RIRS_NOISES/pointsource_noises/rirs_noises.zip exists. Skipping download
/content/speechbrain/recipes/VoxCeleb/SpeakerRec/your_data_folder/RIRS_NOISES/pointsource_noises/rirs_noises.zip exists. Skipping download
results/xvect_augment/1986/save/veri_test2.txt exists. Skipping download
Getting file list...
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/content/speechbrain/recipes/VoxCeleb/SpeakerRec/train_speaker_embeddings.py", line 235, in <module>
    train_data, valid_data, label_encoder = dataio_prep(hparams)
  File "/content/speechbrain/recipes/VoxCeleb/SpeakerRec/train_speaker_embeddings.py", line 140, in dataio_prep
    train_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
  File "/content/speechbrain/speechbrain/dataio/dataset.py", line 409, in from_csv
    return cls(data, dynamic_items, output_keys)
  File "/content/speechbrain/speechbrain/dataio/dataset.py", line 153, in __init__
    static_keys = list(self.data[self.data_ids[0]].keys())
IndexError: list index out of range
```

### Expected behaviour

I'm trying to use pre-trained model via Colab. However, it did not work as expected.

**Comment by PrashanthHawk** [comment]
can you provide the code to reproduce this error

**Comment by asumagic** [comment]
It seems like it's failing to find any file in the data folder you specified. To my understanding, the VoxCeleb dataset should exist there, but it looks like it isn't, or is not placed correctly.  
Did you follow the VoxCeleb SpeakerRec recipe [README](https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxCeleb/SpeakerRec/README.md) and follow the steps (specifically preparation)?

**Comment by zqiu30** [comment]
Oh, thank you for reminding. I also thought that was the issue but the dataset is no longer available. I'm using another model in CommonLanguage now.
