### ISSUE TITLE
speechbrain inference classifier error 

### ISSUE THREAD

**Issue by JGanson** [speechbrain/speechbrain#2457]
### Describe the bug

problem appears on the speechbrain.inference.classifiers

when run classify_batch, the self.mods report "AttributeError: 'ModuleDict' object has no attribute 'compute_features'"

dient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
speechbrain.lobes.models.huggingface_transformers.huggingface - Wav2Vec2Model is frozen.
Traceback (most recent call last):
  File "C:\Users\JGanson\Desktop\DeepLearning\ASR\code\torch\wav2vec_speechbrain.py", line 18, in <module>
    prediction = model.classify_batch(signal)
  File "C:\Users\JGanson\anaconda3\envs\nlp\lib\site-packages\speechbrain\inference\classifiers.py", line 249, in classify_batch
    X_stft = self.mods.compute_stft(wavs)
  File "C:\Users\JGanson\anaconda3\envs\nlp\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ModuleDict' object has no attribute 'compute_stft

### Expected behaviour

my code just simple loading the pretrained model and run, so it shouldn't get this bug

### To Reproduce

from speechbrain.inference.classifiers import AudioClassifier
import numpy as np
import torch 

# Load the pre-trained model
model = AudioClassifier.from_hparams(source="speechbrain/emotion-recognition-wav2vec2-IEMOCAP", savedir="tmpdir")
data = np.load("data/IEMOCAP_audio.npy",allow_pickle=True).item()
model.hparams.label_encoder.ignore_len()

audio = data['audio']

input = audio[0]

signal = torch.tensor(input)

signal = signal.unsqueeze(0)  # Add a batch dimension

prediction = model.classify_batch(signal)

### Environment Details

torch                     2.0.1+cu117              pypi_0    pypi
torchaudio                2.0.2+cu117              pypi_0    pypi
torchvision               0.15.2+cu117             pypi_0    pypi
speechbrain               1.0.0                    pypi_0    pypi

**Comment by ajesujoba** [comment]
Hi @TParcollet , is it possible to do batched inference using -- custom inferences?
