### ISSUE TITLE
Couldn't find appropriate backend to handle uri example.wav and format None.

### ISSUE THREAD

**Issue by Frederic-Zhou** [speechbrain/speechbrain#2579]
### Describe the bug

Here's a detailed description of the issue you're encountering along with the relevant error message, translated into English:

---

### Issue Description

I am following the tutorial from [this Colab notebook](https://colab.research.google.com/drive/1mhvu5eyEzNBBhNC6sknG-kgD2ZQ6NEyI?usp=sharing#scrollTo=bE5JwtDuitfs) step by step. However, I encountered a problem at the first step of the code execution. Below is the code and the `pyproject.toml` configuration I am using.

### Code

```python
import speechbrain as sb
from speechbrain.dataio.dataio import read_audio
from IPython.display import Audio

from speechbrain.inference.ASR import EncoderDecoderASR

asr_model = EncoderDecoderASR.from_hparams(
    source="speechbrain/asr-crdnn-rnnlm-librispeech",
    savedir="pretrained_models/asr-crdnn-rnnlm-librispeech",
)
asr_model.transcribe_file("./content/example.wav")
signal = read_audio("./content/example.wav").squeeze()
Audio(signal, rate=16000)
```

### `pyproject.toml`

```toml
[tool.poetry]
name = "s2st-with-speechbrain"
version = "0.1.0"
description = ""
authors = ["Frederic"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
speechbrain = "^1.0.0"
ipython = "^8.25.0"
torch = "^2.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Environment
- **ffmpeg version**: 7.0.1
- **macOS version**: 15 (ARM version)

### Error Message

```plaintext
torchvision is not available - cannot save figures
SpeechBrain could not find any working torchaudio backend. Audio files may fail to load. Follow this link for instructions and troubleshooting: https://pytorch.org/audio/stable/index.html
SpeechBrain could not find any working torchaudio backend. Audio files may fail to load. Follow this link for instructions and troubleshooting: https://pytorch.org/audio/stable/index.html
Traceback (most recent call last):
  File "/Users/zeta/workspace/s2st_with_speechbrain/test.py", line 11, in <module>
    asr_model.transcribe_file(
  File "/Users/zeta/Library/Caches/pypoetry/virtualenvs/s2st-with-speechbrain-wrzyle28-py3.11/lib/python3.11/site-packages/speechbrain/inference/ASR.py", line 77, in transcribe_file
    waveform = self.load_audio(path, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zeta/Library/Caches/pypoetry/virtualenvs/s2st-with-speechbrain-wrzyle28-py3.11/lib/python3.11/site-packages/speechbrain/inference/interfaces.py", line 282, in load_audio
    signal, sr = torchaudio.load(str(path), channels_first=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zeta/Library/Caches/pypoetry/virtualenvs/s2st-with-speechbrain-wrzyle28-py3.11/lib/python3.11/site-packages/torchaudio/_backend/utils.py", line 204, in load
    backend = dispatcher(uri, format, backend)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zeta/Library/Caches/pypoetry/virtualenvs/s2st-with-speechbrain-wrzyle28-py3.11/lib/python3.11/site-packages/torchaudio/_backend/utils.py", line 116, in dispatcher
    raise RuntimeError(f"Couldn't find appropriate backend to handle uri {uri} and format {format}.")
RuntimeError: Couldn't find appropriate backend to handle uri example.wav and format None.
```

### Expected behaviour

I think it should execute as successfully as described in the docs

**Comment by asumagic** [comment]
Hello, can you try following those steps in our docs? https://speechbrain.readthedocs.io/en/latest/audioloading.html (looks like I had a copy-paste fail in those logs, it meant to point to this rather than the torchaudio docs...)

We haven't had feedback from macOS users so I am curious if you can find a solution. You mention your ffmpeg version, but odds are that torchaudio isn't finding it. This ffmpeg version should be supported by torchaudio.

**Comment by Frederic-Zhou** [comment]
I know the reason for this error is because when torchaudio checks the version of ffmpeg, it only supports 6, 5, and 4, and I have version 7 installed locally.
So, install soundfile to solve the ffmpeg version mismatch.

**Comment by asumagic** [comment]
Ah, I misremembered the supported ffmpeg version range. Anyway, since the issue is resolved, I will close this issue since it is setup-related rather than a bug in SpeechBrain code/docs.
