### ISSUE TITLE
Consistently fails after running for a while. Tried WAV MP3 formats.

### ISSUE THREAD

**Issue by phalexo** [speechbrain/speechbrain#2706]
### Describe the bug

Resampling the audio from 48000 Hz to 16000 Hz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/developer/PROJECTS/speechbrain/speechbrain/inference/separation.py", line 124, in separate_file
    est_sources = self.separate_batch(batch)
  File "/home/developer/PROJECTS/speechbrain/speechbrain/inference/separation.py", line 62, in separate_batch
    est_mask = self.mods.masknet(mix_w)
  File "/home/developer/mambaforge/envs/SpeechBrain/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/developer/mambaforge/envs/SpeechBrain/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/developer/PROJECTS/speechbrain/speechbrain/lobes/models/dual_path.py", line 1067, in forward
    x = self.dual_mdl[i](x)
  File "/home/developer/mambaforge/envs/SpeechBrain/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/developer/mambaforge/envs/SpeechBrain/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/developer/PROJECTS/speechbrain/speechbrain/lobes/models/dual_path.py", line 918, in forward
    inter = self.inter_mdl(inter)
  File "/home/developer/mambaforge/envs/SpeechBrain/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/developer/mambaforge/envs/SpeechBrain/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/developer/PROJECTS/speechbrain/speechbrain/lobes/models/dual_path.py", line 638, in forward
    return self.mdl(x + pos_enc)[0]
RuntimeError: The size of tensor a (10594) must match the size of tensor b (2500) at non-singleton dimension 1

### Expected behaviour

It runs without failing, and separates two voices.

### Environment Details

speechbrain 1.0.1

### Additional Context

The input file is about 15MB, two people speaking, taking turns, one female, one male. No noise or music or reverb.

**Comment by asumagic** [comment]
It's pretty likely that the model was not engineered for such long sequences (`2500` is the default limit on transformers in SB).  
Given how long your sequence is, it's likely that the memory or computational cost would grow too high either way.

I am not personally very familiar with the speech separation task, so I am not sure what is the preferred workaround.  
If you can afford splitting up the input audio to that would likely solve it.

I don't know if this would work, but if this needs to be done automatically, you could try splitting the input audio in chunks of e.g. 30 seconds, that have overlaps of, say, 10 seconds at the start/end of these chunks.  
You would infer on these 50s chunks, cut off the first and last 10s, and stitch everything at the end. Having these overlaps likely would reduce artifacts from chunking.

**Comment by jakeinflab** [comment]
issue like #1255
