### ISSUE TITLE
Italian Hugging Face ASR Models neet

### ISSUE THREAD

**Issue by wredan** [speechbrain/speechbrain#2757]
### Describe the bug

Hi, amazing work so far with SpeechBrain!

I am implementing an ASR model focused on the Italian language using SpeechBrain. My first step was to try the pretrained models available on Hugging Face.

![image](https://github.com/user-attachments/assets/0966f0c7-9998-4e74-8726-f5a7112c89cc)

- `speechbrain/asr-whisper-medium-commonvoice-it` does not work out of the box when following the README instructions. I managed to make it work by modifying the `hyperparams.yaml` file as follows:

```
decoder: !new:speechbrain.decoders.seq2seq.S2SWhisperGreedySearcher
    model: !ref <whisper>
    # bos_index: !ref <timestamp_index>
    # eos_index: !ref <eos_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>
```
- `speechbrain/asr-transducer-commonvoice-14-it` is not working on CUDA but performs well on Colab. When using the CUDA option, I encounter the following error:

```
Traceback (most recent call last):
  File "test_script.py", line 63, in transcribe_audio_files
    sentence = asr_model.transcribe_file(audio_path)
  File "path_to_environment/lib/python3.11/site-packages/speechbrain/inference/ASR.py", line 93, in transcribe_file
    predicted_words, predicted_tokens = self.transcribe_batch(
  File "path_to_environment/lib/python3.11/site-packages/speechbrain/inference/ASR.py", line 162, in transcribe_batch
    predicted_tokens, _, _, _ = self.mods.decoder(*inputs)
  File "path_to_environment/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "path_to_environment/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "path_to_environment/lib/python3.11/site-packages/speechbrain/decoders/transducer.py", line 149, in forward
    hyps = self.searcher(tn_output)
  File "path_to_environment/lib/python3.11/site-packages/speechbrain/decoders/transducer.py", line 381, in transducer_beam_search_decode
    out_PN, hidden = self._forward_PN(
  File "path_to_environment/lib/python3.11/site-packages/speechbrain/decoders/transducer.py", line 590, in _forward_PN
    out_PN = layer(out_PN)
  File "path_to_environment/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "path_to_environment/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "path_to_environment/lib/python3.11/site-packages/speechbrain/nnet/embedding.py", line 118, in forward
    return self.Embedding(x.long())
  File "path_to_environment/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "path_to_environment/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "path_to_environment/lib/python3.11/site-packages/torch/nn/modules/sparse.py", line 190, in forward
    return F.embedding(
  File "path_to_environment/lib/python3.11/site-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

```
- `speechbrain/asr-crdnn-commonvoice-it` and `speechbrain/asr-crdnn-commonvoice-14-it` are working quite well actually. They do not fully complete the transcription but at least provide partial text output.

- `speechbrain/asr-wav2vec2-commonvoice-it` does not perform well on the sample I provided (details in the Colab).

- `speechbrain/asr-wav2vec2-commonvoice-14-it` performs great both on Colab and on CUDA.

### Expected behaviour

Working seameless with the pretrained models provided into SpeechBrain HF repos.

### To Reproduce

https://colab.research.google.com/drive/1xw7p0QD1Lg6pWTmNwVTERs02Yzo1vxgs?usp=sharing

### Environment Details

speechbrain v1.0.2 (local)

### Additional Context

If I'm missing something, could you guys point me out to the right docs to follow? Thank you in advance.

**Comment by Adel-Moumen** [comment]
>  speechbrain/asr-transducer-commonvoice-14-it is not working on CUDA but performs well on Colab. When using the CUDA option, I encounter the following error:

Hey, how are you passing the cuda device? Can I see the code? thanks :)

**Comment by wredan** [comment]
Hi!

yes sure, here is the snippet:

```py
    model_info = MODELS[args.model]
    asr_model = model_info["class"].from_hparams(
        source=model_info["source"],
        savedir=f"pretrained_models/{args.model}",
        run_opts={"device": "cuda"}
    )
```
The `model_info["class"]` is `EncoderDecoderASR` for the `transducer`. I’m using the same script to test the models.

Thank you for the support!

**Comment by TParcollet** [comment]
@Adel-Moumen any news on that?

**Comment by TParcollet** [comment]
@wredan could you let me know if it's fixed? We've merged a PR recently fixing an error like that.

**Comment by wredan** [comment]
Hi, I'm quite busy right now, but I’ll try to take a look at it in the next few weeks. Thanks for the update

**Comment by raphael10-collab** [comment]
Looking for updates:
It seems that the ASR Models in HuggingFace for Italian Language are not supported, when trying to convert them to gguf
