### ISSUE TITLE
`S2SWhisperGreedySearch` not found

### ISSUE THREAD

**Issue by njfamirm** [speechbrain/speechbrain#2786]
### Describe the bug

When simply want transcribe audio
get this logs ( in the log output section )

### Expected behaviour

work fine without error

### To Reproduce

```python
from speechbrain.inference.ASR import WhisperASR

def load_model():
    model_name = "speechbrain/asr-whisper-large-v2-commonvoice-fa"
    asr_model = WhisperASR.from_hparams(source=model_name, savedir="pretrained_models/model")
    return asr_model

def predict(asr_model, audio_path):
    transcription = asr_model.transcribe_file(audio_path)
    return transcription
```

```python
import sys
import json
from io import StringIO
from predict import load_model, predict
from metrics import calculate_wer

model = load_model()

audio_path = '../assets/audio-01.wav'
ground_truth_path = '../assets/audio-01.txt'

# Read the ground truth text
with open(ground_truth_path, 'r') as file:
    ground_truth = file.read()

transcription = predict(model, audio_path)

wer_score = calculate_wer(ground_truth, transcription)

output_data = {
    'transcription': transcription,
    'werAfterNormalization': wer_score,
njfamirm marked this conversation as resolved.
    'normalizedTranscription': transcription,
    'werAfterNormalization': wer_score
}

# Write JSON output to a file
with open('result.json', 'w', encoding='utf-8') as f:
    json.dump(output_data, f, ensure_ascii=False, indent=4)

# Read and print the JSON output
with open('result.json', 'r', encoding='utf-8') as f:
    json_output = f.read()

print(json_output)
```

### Environment Details

CPython 3.11.11
Github action using ubuntu latest

### Relevant Log Output

```shell
Run cd speech-brain-asr-whisper-large-v2-commonvoice-fa
INFO:speechbrain.utils.quirks:Applied quirks (see `speechbrain.utils.quirks`): [disable_jit_profiling, allow_tf32]
INFO:speechbrain.utils.quirks:Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []
INFO:speechbrain.utils.fetching:Fetch hyperparams.yaml: Fetching from HuggingFace Hub 'speechbrain/asr-whisper-large-v2-commonvoice-fa' if not cached
INFO:speechbrain.utils.fetching:Fetch custom.py: Fetching from HuggingFace Hub 'speechbrain/asr-whisper-large-v2-commonvoice-fa' if not cached
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]
0it [00:00, ?it/s]
/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/transformers/modeling_utils.py:442: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(checkpoint_file, map_location="cpu")
WARNING:speechbrain.lobes.models.huggingface_transformers.huggingface:speechbrain.lobes.models.huggingface_transformers.huggingface - WhisperModel is frozen.
WARNING:speechbrain.lobes.models.huggingface_transformers.whisper:speechbrain.lobes.models.huggingface_transformers.whisper - whisper encoder-decoder is frozen.
Traceback (most recent call last):
  File "/home/runner/work/persian-asr-benchmark/persian-asr-benchmark/speech-brain-asr-whisper-large-v2-commonvoice-fa/main.py", line 7, in <module>
    model = load_model()
            ^^^^^^^^^^^^
  File "/home/runner/work/persian-asr-benchmark/persian-asr-benchmark/speech-brain-asr-whisper-large-v2-commonvoice-fa/predict.py", line 5, in load_model
    asr_model = WhisperASR.from_hparams(source=asr_model_name, savedir="pretrained_models/model")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/speechbrain/inference/interfaces.py", line 508, in from_hparams
    hparams = load_hyperpyyaml(
              ^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/hyperpyyaml/core.py", line 188, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 116, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 120, in construct_document
    data = self.construct_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 633, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/hyperpyyaml/core.py", line 472, in _construct_object
    raise ImportError("There is no such class as %s" % callable_string)
ImportError: There is no such class as speechbrain.decoders.seq2seq.S2SWhisperGreedySearch
```

### Additional Context

https://github.com/search?q=repo%3Aspeechbrain%2Fspeechbrain+speechbrain.decoders.seq2seq.S2SWhisperGreedySearch&type=code

Single place use `S2SWhisperGreedySearch` not `S2SWhisperGreedySearcher`

**Comment by njfamirm** [comment]
any one check this issue?

**Comment by Adel-Moumen** [comment]
> any one check this issue?

Yes. I started modifying all the yamls, but I still need to fix a couple of them.

**Comment by Adel-Moumen** [comment]
Hello @njfamirm, I did modified all the Yamls, can you please check if now everything is good on your side? Thanks.

**Comment by njfamirm** [comment]
> Hello [@njfamirm](https://github.com/njfamirm), I did modify all the Yamls, can you please check if now everything is good on your side? Thanks.

Hi, thanks Adel
Sorry, I didn't have a chance to test.
