### ISSUE TITLE
train_speaker_embeddings audio pipeline does not check for out of range values

### ISSUE THREAD

**Issue by piraka9011** [speechbrain/speechbrain#492]
It looks like in `train_speaker_embeddings.py` for the SpeakerRec recipe, the [following line] can cause this error:

```sh
Original Traceback (most recent call last):
  File "/home/allabana/.virtualenvs/sprain/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/allabana/.virtualenvs/sprain/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/allabana/.virtualenvs/sprain/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/allabana/stt_ws/speechbrain/speechbrain/dataio/dataset.py", line 166, in __getitem__
    return self.pipeline.compute_outputs(data_point)
  File "/home/allabana/stt_ws/speechbrain/speechbrain/utils/data_pipeline.py", line 456, in compute_outputs
    return self._compute(data, self._exec_order, self.output_mapping)
  File "/home/allabana/stt_ws/speechbrain/speechbrain/utils/data_pipeline.py", line 488, in _compute
    values = item(*args)  # Call the DynamicItem to produce output
  File "/home/allabana/stt_ws/speechbrain/speechbrain/utils/data_pipeline.py", line 73, in __call__
    return self.func(*args)
  File "train_speaker_embeddings.py", line 138, in audio_pipeline
    start = random.randint(0, duration_sample - snt_len_sample - 1)
  File "/usr/lib/python3.8/random.py", line 248, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.8/random.py", line 226, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0, -16320, -16320)
```

it looks like there should be a check if the calculated `duration_sample - snt_len_sample`  is < 0 and either: skip the sample or return 0.

```py
start = 0 if start_range < 0 else random.randint(0, start_range)
```

**Comment by mravanelli** [comment]
The recipes of voxceleb has been reviewed over the last couple of weeks. Some of the points raised here are fixed. Thank you!

**Comment by pnsafari** [comment]
Hi, I got the same error with the recipes on the master branch for voxceleb2. Do I have to do something beforehand for the data preparation?
