### ISSUE TITLE
RuntimeError: Backend "sox_io" is not one of available backends: ['soundfile']

### ISSUE THREAD

**Issue by TasTugberk** [speechbrain/speechbrain#588]
I installed SpeechBrain as mentioned [here.](https://speechbrain.readthedocs.io/en/latest/installation.html) But when I import it, I get the following error:

`..\anaconda3\lib\site-packages\torchaudio\extension\extension.py:13: UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "..\anaconda3\lib\site-packages\speechbrain\__init__.py", line 4, in <module>
    from .core import Stage, Brain, create_experiment_directory, parse_arguments
  File "..\anaconda3\lib\site-packages\speechbrain\core.py", line 32, in <module>
    from speechbrain.utils.distributed import run_on_main
  File "..\anaconda3\lib\site-packages\speechbrain\utils\__init__.py", line 11, in <module>
    from . import *  # noqa
  File "..\anaconda3\lib\site-packages\speechbrain\utils\Accuracy.py", line 7, in <module>
    from speechbrain.dataio.dataio import length_to_mask
  File "..\anaconda3\lib\site-packages\speechbrain\dataio\__init__.py", line 11, in <module>
    from . import *  # noqa
  File "..\anaconda3\lib\site-packages\speechbrain\dataio\dataio.py", line 24, in <module>
    torchaudio.set_audio_backend(
  File "..\anaconda3\lib\site-packages\torchaudio\backend\utils.py", line 52, in set_audio_backend
    raise RuntimeError(
RuntimeError: Backend "sox_io" is not one of available backends: ['soundfile'].`

When I search for this error, what I found is: _"sox" and "sox_io" backends require C++ extension module, which is included in Linux/macOS binary distributions. These backends are not available on Windows._, which is mentioned [here.](https://pytorch.org/audio/stable/backend.html#availability) So my question is; can I use SpeechBackend on Windows enviroment. (Windows 10 - Python 3.8) Thanks.

**Comment by mravanelli** [comment]
It looks like you are using windows, right?
If so you have to change to torchaudio backend from sox-io to soundfile
(there is a PR active that automatically checks the operating system and
chooses the right backend automatically).

**Comment by TasTugberk** [comment]
Yes, I use Windows, thank you for quick response.
