### ISSUE TITLE
How can I use the model with c++ language

### ISSUE THREAD

**Issue by hk0901** [speechbrain/speechbrain#617]
hello, I want the use the model (speaker recognize)  with cpp，Is there a convenient way to achieve it

**Comment by TParcollet** [comment]
Hi,

This is a very good question. On-device and optimised inference are on our short-term to-do list. However, for now, I would say that SpeechBrain is extremely close to raw PyTorch. Hence, any solution that PyTorch provides to use C++ should work with SpeechBrain. Honestly, if you try it, we would love to here from your feedback to better design things that need to be changed.

**Comment by mravanelli** [comment]
Model compilation is feasible now in PyTorch thanks to TorchScript and the just-in-time (JIT) compiler. The speechbrain modules are almost all jitable (see the torch.jit.trace lines that we add in many unittests). We only have to work on the beamsearch part.

**Comment by luciddream-tsin** [comment]
Hello, everyone!
When I try to convert the model to c++ (TorchScript) like this:
```cpp

import torch.cuda
import torchaudio
from speechbrain.pretrained import Tacotron2
from speechbrain.pretrained import HIFIGAN

print(torch.cuda.is_available())
# Intialize TTS (tacotron2) and Vocoder (HiFIGAN)
tacotron2 = Tacotron2.from_hparams(source="./", savedir="tmpdir_tts")
hifi_gan = HIFIGAN.from_hparams(source="./", savedir="tmpdir_vocoder")

# Running the TTS
mel_output, mel_length, alignment = tacotron2.encode_text("unprecedented")

#-----------tmp--------beg--------
traced_tacotron2 = torch.jit.trace(tacotron2, "unprecedented")
#-----------tmp--------end--------

# Running Vocoder (spectrogram-to-waveform)
waveforms = hifi_gan.decode_batch(mel_output)

# Save the waverform
torchaudio.save('example_TTS.wav',waveforms.squeeze(1), 22050)

```
The demo work fine, but after I add a tracing line( between tmp comment), I get this error:
```shell
/usr/bin/python3.10 /media/tsin/LDDA/code/pithon/trial/main.py 
False
Traceback (most recent call last):
  File "/media/tsin/LDDA/code/pithon/trial/main.py", line 15, in <module>
    traced_script_module_1 = torch.jit.trace(tacotron2, "unprecedented")
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py", line 759, in trace
    return trace_module(
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py", line 960, in trace_module
    module = make_module(mod, _module_class, _compilation_unit)
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py", line 586, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py", line 1085, in __init__
    tmp_module._modules[name] = make_module(
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py", line 586, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py", line 1085, in __init__
    tmp_module._modules[name] = make_module(
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py", line 586, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py", line 1085, in __init__
    tmp_module._modules[name] = make_module(
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py", line 577, in make_module
    return torch.jit._recursive.create_script_module(
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 476, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 393, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: Couldn't find method: 'forward__0' on class: '__torch__.torch.nn.modules.rnn.LSTM (of Python compilation unit at: 0x55b7f11f9880)'

Process finished with exit code 1

``` 

Any ideas?

**Comment by luciddream-tsin** [comment]
OS: ubuntu 22.04
Pytorch 1.13.1+cu117 cpu

**Comment by AsuMagic** [comment]
@luciddream-tsin You should probably move this to its own issue as it's only tangentially related to this one.
