### ISSUE TITLE
Training LibreASR LM, Cudnn Error happens

### ISSUE THREAD

**Issue by sridhar1ga** [speechbrain/speechbrain#787]
hi, When I was training LibriSpeech ASR Language model, this error is happening, What might be the issue, Thanks

python train.py RNNLM.yaml
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: /asrltrc/ganesh/spb_exp/Libre/LM/results/RNNLM/
root - generating datasets...
datasets.builder - Using custom data configuration default-410ea46aba2d7db9
datasets.builder - Reusing dataset text (/home/asr/.cache/huggingface/datasets/text/default-410ea46aba2d7db9/0.0.0/e16f44aa1b321ece1f87b07977cc5d70be93d69b20486d6dacd62e12cf25c9a5)
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 255, in <module>
    lm_brain = LM(
  File "/home/asr/spb/speechbrain/core.py", line 476, in __init__
    self.modules = torch.nn.ModuleDict(modules).to(self.device)
  File "/home/asr/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/home/asr/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/asr/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/asr/.local/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 186, in _apply
    self.flatten_parameters()
  File "/home/asr/.local/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 172, in flatten_parameters
    torch._cudnn_rnn_flatten_weight(
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

**Comment by mravanelli** [comment]
Hi, this looks like a problem with your GPU. Are you able to simply run the following code without errors?
>>> import torch
>>> torch.rand(10, device='cuda')

**Comment by sridhar1ga** [comment]
Hello,
I ran those commands and they worked fine. I have given the output below.

```bash
(spb) asr@ltrcgpu:~$ python
Python 3.8.10 (default, May 19 2021, 18:05:58) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.rand(10, device='cuda')
tensor([0.2570, 0.3983, 0.1486, 0.8994, 0.7859, 0.0431, 0.0474, 0.6916, 0.1371,
        0.1126], device='cuda:0')
```

**Comment by mravanelli** [comment]
Did you fix that? This looks a GPU problem more than a speechbrain one
