### ISSUE TITLE
ImportError: There is no such class as recipes.LibriSpeech.LM.pretrained.pretrained.LM

### ISSUE THREAD

**Issue by Sar-Dar** [speechbrain/speechbrain#826]
When I run ``SpeechBrain/recipes/LibriSpeech/ASR/transducer/train.py`` ocurred ImportError like this:
``
Traceback (most recent call last):
  File "train.py", line 367, in <module>
    hparams = load_hyperpyyaml(fin, overrides)
  File "/home/sardar/anaconda3/envs/SpeechBrain/lib/python3.8/site-packages/hyperpyyaml/core.py", line 182, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=yaml.Loader)
  File "/home/sardar/anaconda3/envs/SpeechBrain/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/sardar/anaconda3/envs/SpeechBrain/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/home/sardar/anaconda3/envs/SpeechBrain/lib/python3.8/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/home/sardar/anaconda3/envs/SpeechBrain/lib/python3.8/site-packages/yaml/constructor.py", line 107, in construct_object
    for dummy in generator:
  File "/home/sardar/anaconda3/envs/SpeechBrain/lib/python3.8/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/sardar/anaconda3/envs/SpeechBrain/lib/python3.8/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/sardar/anaconda3/envs/SpeechBrain/lib/python3.8/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/sardar/anaconda3/envs/SpeechBrain/lib/python3.8/site-packages/yaml/constructor.py", line 102, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/home/sardar/anaconda3/envs/SpeechBrain/lib/python3.8/site-packages/hyperpyyaml/core.py", line 420, in _construct_object
    raise ImportError("There is no such class as %s" % callable_string)
ImportError: There is no such class as recipes.LibriSpeech.LM.pretrained.pretrained.LM
``

**Comment by mravanelli** [comment]
It looks like the `LibriSpeech/ASR/transducer` recipe is outdated. @aheba could you please take a look at that?

**Comment by TParcollet** [comment]
Thanks, @Sar-Dar, we fixed the issue.
