### ISSUE TITLE
Error running WSJ0-2MIX recipe 

### ISSUE THREAD

**Issue by jwr1995** [speechbrain/speechbrain#849]
I was trying to run the WSJ0-2MIX recipe in Python 3.8 in Windows. I keep getting this error log for all the models
`:\Users\will9\AppData\Local\Programs\Python\Python38\lib\site-packages\torchaudio\extension\extension.py:13: UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
  0%|                                                                                        | 0/20000 [00:00<?, ?it/s]
speechbrain.core - Exception:
Traceback (most recent call last):
  File ".\train.py", line 604, in <module>
    separator.fit(
  File "c:\users\will9\onedrive\projects\speechbrain\speechbrain\core.py", line 1021, in fit
    for batch in t:
  File "C:\Users\will9\AppData\Local\Programs\Python\Python38\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "c:\users\will9\onedrive\projects\speechbrain\speechbrain\dataio\dataloader.py", line 175, in __iter__
    iterator = super().__iter__()
  File "C:\Users\will9\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "C:\Users\will9\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\will9\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 914, in __init__
    w.start()
  File "C:\Users\will9\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\will9\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\will9\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "C:\Users\will9\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\will9\AppData\Local\Programs\Python\Python38\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'dataio_prep.<locals>.audio_pipeline_mix'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\will9\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\will9\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input`

**Comment by TParcollet** [comment]
Hi, the problem is that we do not have any member using windows. Hopefully someone from the community can help.
