### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Mlallena** [speechbrain/speechbrain#881]
I am trying to install speechbrain in my computer, but I'm having problems with the installation even though I'm following the instructions. Any idea on how to solve it?

This is what I get when I try the last step (`pip install --editable .`):
```
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/miguel/Desktop/languageIDKaldi2/speechbrain
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/miguel/.local/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-qmx7nr7v/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (48 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/home/miguel/.local/lib/python3.6/site-packages/pip/__main__.py", line 29, in <module>
      from pip._internal.cli.main import main as _main
    File "/home/miguel/.local/lib/python3.6/site-packages/pip/_internal/cli/main.py", line 4, in <module>
      import logging
    File "/home/miguel/.local/lib/python3.6/site-packages/logging/__init__.py", line 618
      raise NotImplementedError, 'emit must be implemented '\
                               ^
  SyntaxError: invalid syntax
  Error in sys.excepthook:
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
      from apport.fileutils import likely_packaged, get_recent_crashes
    File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
      from apport.report import Report
    File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
      import apport.fileutils
    File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 25, in <module>
      from apport.packaging_impl import impl as packaging
    File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
      import apt
    File "/usr/lib/python3/dist-packages/apt/__init__.py", line 26, in <module>
      from apt.package import Package
    File "/usr/lib/python3/dist-packages/apt/package.py", line 24, in <module>
      import logging
    File "/home/miguel/.local/lib/python3.6/site-packages/logging/__init__.py", line 618
      raise NotImplementedError, 'emit must be implemented '\
                               ^
  SyntaxError: invalid syntax
  
  Original exception was:
  Traceback (most recent call last):
    File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/home/miguel/.local/lib/python3.6/site-packages/pip/__main__.py", line 29, in <module>
      from pip._internal.cli.main import main as _main
    File "/home/miguel/.local/lib/python3.6/site-packages/pip/_internal/cli/main.py", line 4, in <module>
      import logging
    File "/home/miguel/.local/lib/python3.6/site-packages/logging/__init__.py", line 618
      raise NotImplementedError, 'emit must be implemented '\
                               ^
  SyntaxError: invalid syntax
  ----------------------------------------
WARNING: Discarding file:///home/miguel/Desktop/languageIDKaldi2/speechbrain. Command errored out with exit status 1: /usr/bin/python3 /home/miguel/.local/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-qmx7nr7v/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/bin/python3 /home/miguel/.local/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-qmx7nr7v/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
```

EDIT: Also, when I attempt to install speechbrain directly with PIP, I get another error:
```
ERROR: Could not find a version that satisfies the requirement speechbrain (from versions: none)
ERROR: No matching distribution found for speechbrain
```
This one is particularly curious, since both pypi.org and your own github page explicitly indicate that it can be installed using pip. Suggestions?

**Comment by mravanelli** [comment]
That looks like a problem with your environment. Did you try to create a conda environment with python >=3.8?

**Comment by lumaku** [comment]
From your error message:
```
    File "/home/miguel/.local/lib/python3.6/site-packages/logging/__init__.py", line 618
```
The path says that your logging moduls is loaded from a user package.
`logging` is a default python 3 module, your user package has import priority over your system package but obviously has a bug.
To solve, uninstall or remove your user package.

**Comment by mravanelli** [comment]
Does it solve the problem?

**Comment by Mlallena** [comment]
You need python 3.8 for speechbrain to work? Damn, I didn't see that in the notes.

I'll see what I can do.

**Comment by Mlallena** [comment]
OK, after some tests, I managed to make it work. The first machine I tried this with didn't work out because the GPU didn't have enough memory, but trying elsewhere worked - even if that comes with its own set of problems, which I'll detail in a different issue thread.
