### ISSUE TITLE
Training  speech enhancement model

### ISSUE THREAD

**Issue by helloazman** [speechbrain/speechbrain#910]
Hi,i first installed speechbrain and cloned codes from this repository https://github.com/speechbrain/speechbrain/tree/develop/templates/enhancement.After running the training python train.py train.yaml --data_folder path with this command i faced "RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same" this error.As i don't have enough knowledge about the codes ,can anyone help me where to edit the files to solve the error?
This is the exception:
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 280, in <module>
    se_brain.fit(
  File "/home/azman/texttospeech/denoise/speechbrain/speechbrain/core.py", line 1068, in fit
    loss = self.evaluate_batch(batch, stage=Stage.VALID)
  File "/home/azman/texttospeech/denoise/speechbrain/speechbrain/core.py", line 930, in evaluate_batch
    loss = self.compute_objectives(out, batch, stage=stage)
  File "train.py", line 112, in compute_objectives
    self.stoi_metric.append(
  File "/home/azman/texttospeech/denoise/speechbrain/speechbrain/utils/metric_stats.py", line 83, in append
    scores = self.metric(*args, **kwargs).detach()
  File "/home/azman/texttospeech/denoise/speechbrain/speechbrain/nnet/loss/stoi_loss.py", line 153, in stoi_loss
    y_true, y_pred = resampler(y_true), resampler(y_pred)
  File "/home/azman/miniconda3/envs/denoise/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/azman/miniconda3/envs/denoise/lib/python3.8/site-packages/torchaudio/transforms.py", line 716, in forward
    return _apply_sinc_resample_kernel(
  File "/home/azman/miniconda3/envs/denoise/lib/python3.8/site-packages/torchaudio/functional/functional.py", line 1387, in _apply_sinc_resample_kernel
    resampled = torch.nn.functional.conv1d(waveform[:, None], kernel, stride=orig_freq)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

**Comment by mravanelli** [comment]
My suggestion is to take a look at the speech enhancement tutorial [here](https://speechbrain.github.io/tutorial_enhancement.html) that uses the exact same template on google Colab.  There might be however a device mismatch happening when using the GPU rather than the CPU. What do you think @pplantinga?

**Comment by mravanelli** [comment]
Thank you for noticing. It was just Reample not put on the right device. I fixed it in the development branch.
