### ISSUE TITLE
LibriSpeech LM: datasets package cannot handle "None" values

### ISSUE THREAD

**Issue by aviadb** [speechbrain/speechbrain#954]
python train.py hparams/RNNLM.yaml 
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: results/RNN/2223
root - generating datasets...
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train.py", line 188, in <module>
    train_data, valid_data, test_data = dataio_prepare(hparams)
  File "train.py", line 118, in dataio_prepare
    datasets = load_dataset(
  File "/home/aviadb/miniconda3/envs/sb38/lib/python3.8/site-packages/datasets/load.py", line 819, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/aviadb/miniconda3/envs/sb38/lib/python3.8/site-packages/datasets/load.py", line 701, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/aviadb/miniconda3/envs/sb38/lib/python3.8/site-packages/datasets/builder.py", line 1049, in __init__
    super(GeneratorBasedBuilder, self).__init__(*args, **kwargs)
  File "/home/aviadb/miniconda3/envs/sb38/lib/python3.8/site-packages/datasets/builder.py", line 268, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/home/aviadb/miniconda3/envs/sb38/lib/python3.8/site-packages/datasets/builder.py", line 370, in _create_builder_config
    builder_config = self.BUILDER_CONFIG_CLASS(**config_kwargs)
TypeError: __init__() got an unexpected keyword argument 'lm_corpus_path'

the "lm_corpus_path" in the yaml file is set to null

Any ideas?

**Comment by TParcollet** [comment]
Hi, well, if you don't want to train a LM, I guess that you should just remove this part instead.

**Comment by aviadb** [comment]
The current value is set to null. According to the comment, null value means downloading.
Any idea how to fix that hyper-parameter?

In case I want to skip training. Will a pretrained LM work with different trained ASR engines?

**Comment by Adel-Moumen** [comment]
Hello, 

I'm closing this issue due to https://github.com/speechbrain/speechbrain/issues/1302#issuecomment-1484745888 . Feel free to reopen if needed. 

Best.
