### ISSUE TITLE
Encode unknown label during eval epoch spkrec-ecapa-TDNN

### ISSUE THREAD

**Issue by asr-lord** [speechbrain/speechbrain#998]
When the first epoch ends, I've an error in the evaluation because there are some speakers/labels that are not present on label_encoder.txt

```
(.venv) root@8ad8297faf3e:/home/diarization/speechbrain/recipes/VoxCeleb/SpeakerRec# time python train_speaker_embeddings.py hparams/train_ecapa_tdnn.yaml
/home/diarization/data/voxceleb/data/augmented/rirs_noises.zip exists. Skipping download
/home/diarization/data/voxceleb/data/augmented/rirs_noises.zip exists. Skipping download
/home/diarization/data/voxceleb/data/augmented/rirs_noises.zip exists. Skipping download
results/ecapa_augment/1986/save/veri_test2.txt exists. Skipping download
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: results/ecapa_augment/1986
speechbrain.core - Info: ckpt_interval_minutes arg from hparam file is used
speechbrain.core - 23.7M trainable parameters in SpeakerBrain
speechbrain.utils.checkpoints - Would load a checkpoint here, but none found yet.
speechbrain.utils.epoch_loop - Going into epoch 1
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 96438/96438 [02:11<00:00,  2.41it/s, train_loss=7.32]
  2%|███▎                                                                                                                                            | 285/12597 [00:07<05:30, 37.24it/s]
speechbrain.core - Exception:
Traceback (most recent call last):
  File "train_speaker_embeddings.py", line 249, in <module>
    speaker_brain.fit(
  File "/home/diarization/speechbrain/speechbrain/core.py", line 1063, in fit
    for batch in tqdm(
  File "/root/.venv/lib/python3.8/site-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/root/.venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/root/.venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/root/.venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/root/.venv/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/diarization/speechbrain/speechbrain/dataio/encoder.py", line 446, in encode_label
    return self.lab2ind[label]
KeyError: 'id274srt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.venv/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/.venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/.venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/diarization/speechbrain/speechbrain/dataio/dataset.py", line 165, in __getitem__
    return self.pipeline.compute_outputs({"id": data_id, **data_point})
  File "/home/diarization/speechbrain/speechbrain/utils/data_pipeline.py", line 455, in compute_outputs
    return self._compute(data, self._exec_order, self.output_mapping)
  File "/home/diarization/speechbrain/speechbrain/utils/data_pipeline.py", line 487, in _compute
    values = item(*args)  # Call the DynamicItem to produce output
  File "/home/diarization/speechbrain/speechbrain/utils/data_pipeline.py", line 154, in __call__
    out = next(self.current_generator)
  File "train_speaker_embeddings.py", line 175, in label_pipeline
    spk_id_encoded = label_encoder.encode_sequence_torch([spk_id])
  File "/home/diarization/speechbrain/speechbrain/dataio/encoder.py", line 512, in encode_sequence_torch
    [self.encode_label(label, allow_unk) for label in sequence]
  File "/home/diarization/speechbrain/speechbrain/dataio/encoder.py", line 512, in <listcomp>
    [self.encode_label(label, allow_unk) for label in sequence]
  File "/home/diarization/speechbrain/speechbrain/dataio/encoder.py", line 456, in encode_label
    raise KeyError(
KeyError: 'Cannot encode unknown label id274srt. You have not called add_unk() to add a special unk-label for unknown labels.'


real    2m36.923s
user    3m27.136s
sys     0m5.796s

```

But in the code you only encoder the train_data speakers:
https://github.com/speechbrain/speechbrain/blob/2ec4839746970875fc763aa354c44a3356685ef6/recipes/VoxCeleb/SpeakerRec/train_speaker_embeddings.py#L182-L187

So to avoid this error I've to add valid_data?
```
    label_encoder.load_or_create(
        path=lab_enc_file, from_didatasets=[train_data, valid_data], output_key="spk_id",
    )

**Comment by mravanelli** [comment]
When training the model that learns the speaker embeddings, you have to make sure all the speakers are available in the training set. This doesn't look the same for your dataset.

**Comment by rohaantahir** [comment]
Hi @mravanelli I am also using this recipe and dataset I am using is VoxCeleb1 + CustomDataset. I am facing the similar issue the ids associated with my custom dataset is giving key error while all data is present in the dataset directory. Previously I was able to train the model with custom dataset but now I think new update is causing this issue. Could you please tell us how to use add_unk() ?

**Comment by rohaantahir** [comment]
@mravanelli your response would be highly obliged. Please respond thanks.

**Comment by Natavan-A** [comment]
Good day,
Any news on adding unknown label? 
It would be really great to use also in speaker identification (templates/speaker_id). This way the identification of speakers will become open-set, rather than closed-set.

**Comment by rohaantahir** [comment]
@Natavan-A I worked on the speaker identification and make a dynamic module for it. In which I am saving the sample embeddings of speaker in a csv and then comparing that embedding vector with input to identify speaker. Hope this helps you

**Comment by Natavan-A** [comment]
@rohaantahir very insightful, thank you very much!

**Comment by TParcollet** [comment]
Hi, we could use some help to think and design this feature. Important work will restart very soon on SpeechBrain as we will push a major version by the end of the Summer. As the toolkit is run by academics, we unfortunately have periods where everyone is teaching ahah.

**Comment by goreng2** [comment]
I found Why `keyerror` raised.

Maybe some of your custom-dataset are shorter than 3 seconds (default `seg_dur` argument).

Audio files that shorter than 3 seconds don't record to csv
Check this code: https://github.com/speechbrain/speechbrain/blob/d2e9f2e2f2872f61d775e830fd932df79696908c/recipes/VoxCeleb/voxceleb_prepare.py#LL312C5-L312C5

`label_encoder.txt` made by `train_data`.
So, If `train_data` has short audio files and `dev_data` has some long audio files, `label_encoder.txt` don't has `dev_data`'s label.

**Comment by Adel-Moumen** [comment]
Hello, 

Please see https://github.com/speechbrain/speechbrain/issues/998#issuecomment-1547314555. Could you please try and get back to us if it solved your issue? 

Thanks. 
Adel
